### ISSUE TITLE
cannot install using pod

### ISSUE THREAD

**Issue by ShRoO0oM** [Yummypets/YPImagePicker#1]
i'm getting [!] Unable to find a specification for `YPImagePicker` and when I force source using : 
pod 'YPImagePicker',:git => 'https://github.com/Yummypets/YPImagePicker'

it says no such module for Stevia and when I add stevia to project I get lots of syntax error

**Comment by SalmanGhumsani** [comment]
Swift 3.x

Now you can download the code and find the `Source` folder and copy `Source` into your project after that install `Stevia` with `pod 'SteviaLayout'` and run it :)

**Comment by wegweiser6** [comment]
me too, can not install pod  'YPImagePicker'
is 'SteviaLayout'   'YPImagePicker' ?

**Comment by s4cha** [comment]
Hello @mohammadZ74, @SalmanGhumsani, @wegweiser6 

The pod installation is broken at the moment but I will let you know when it's back up.
In the meantime, installing through Carthage should work though.

Sorry for the inconvenience :/

Cheers,

**Comment by s4cha** [comment]
@mohammadZ74  @SalmanGhumsani @wegweiser6 
The pod installation is now up and running but we still have issues with assets and translations.
This must be something bundle related since it works fine using Carthage :/
I need to look into this, I already had something similar on another project.

**Comment by s4cha** [comment]
@mohammadZ74 @SalmanGhumsani @wegweiser6 
Cocoapods integration is now fixed in 2.0.1 :)

**Comment by BilalAkram** [comment]
Carthage ain't working properly . 
-I added the YPImagePicker project through Carthage in my project and it shows the following error "dyld: Library not loaded: stevia and image not found" at build time.
-it also didn't add the framework files for both  YPImagePicker and Stevia
And my project is build in swift 3.2 , so how can I use this library in my project using cocoa pods ???

**Comment by s4cha** [comment]
Hi @BilalAkram,

YPImagePicker depends on Stevia, which needs to be linked as well.
In Build Phases > Carthage Run Script > Input files
Make sure you have :
`$(SRCROOT)/Carthage/Build/iOS/YPImagePicker.framework`
`$(SRCROOT)/Carthage/Build/iOS/Stevia.framework`
and that those are also linked under `Link Binary with Libraries`

Concerning the swift version, not sure if Swift 3.2 code is allowed to use a swift 4 library :/

Please excuse the late reply,

Sacha

**Comment by r-a-o** [comment]
Hi, is there a specific reason for dynamically linking Stevia? Since its dynamically linked, its messing with my project's other autolayout library (EasyPeasy). I am unable to use this repo because the dependency is dynamically linked. Any solution? Can we remove dynamic linking of Stevia?
@s4cha
