### ISSUE TITLE
Filter for taken video

### ISSUE THREAD

**Issue by alisafilip** [Yummypets/YPImagePicker#101]
Hello,
I can see the filters for the photos. Can we set filters on video, too?
Thanks.

**Comment by s4cha** [comment]
Hi @alisafilip this is not supported at the moment but this is on our roadmap :)

**Comment by alisafilip** [comment]
When can we expect for this?

**Comment by NikKovIos** [comment]
Not in the nearest future(

**Comment by NikKovIos** [comment]
Too old issue. Feel free to open new.
