### ISSUE TITLE
Preview Recorded video?

### ISSUE THREAD

**Issue by djaygit** [Yummypets/YPImagePicker#102]

**Comment by s4cha** [comment]
@djaygit This is actually being implemented as part of https://github.com/Yummypets/YPImagePicker/pull/47
Stay tuned :)

**Comment by s4cha** [comment]
@djaygit in 3.0.0 you can now preview the video you just captured :) 
https://github.com/Yummypets/YPImagePicker/releases/tag/3.0.0
