### ISSUE TITLE
Mutiple selection

### ISSUE THREAD

**Issue by praveen4D2** [Yummypets/YPImagePicker#103]
Please update the mutiple selection (image & videos) option and also maintain whenever change the album folder also the selection states can maintain. Please update its as soon as possible. Waiting for your update .

**Comment by praveen4D2** [comment]
I used the pre release mode of multiple selection but it does not maintain folder that is , when i change the folder the selection is applied for another folder also. I attached the screen shot . Kindly update the multiple selection update.
![screen shot 2018-05-02 at 6 10 01 pm](https://user-images.githubusercontent.com/34230288/39523683-186da522-4e34-11e8-8bb8-59ebed5ad54a.png)
![screen shot 2018-05-02 at 6 09 42 pm](https://user-images.githubusercontent.com/34230288/39523685-18a6b510-4e34-11e8-80f8-3e308ec24f67.png)

**Comment by devender54321** [comment]
Update library with multiple image selection

**Comment by praveen4D2** [comment]
Please Update multiple selection

**Comment by s4cha** [comment]
@praveen4D2 @devender54321 
Multiple selection is still in development and not suited for production yet.
Please be patient :)

**Comment by praveen4D2** [comment]
Please update Multiple selection ASAP

**Comment by devender54321** [comment]
yes sir we are waiting for it for our app

**Comment by praveen4D2** [comment]
Thanks for responding, When you guys will complete this multiple selection feature?

**Comment by NikKovIos** [comment]
@praveen4D2 you can clone it directly from the multipleSelection branch already now. The basic implementation is ready. But it still need some bugfixes.

**Comment by praveen4D2** [comment]
Thanks for responding
But kindly update the multiple selection feature as soon as possible

**Comment by praveen4D2** [comment]
Thanks for responding
But kindly update the multiple selection feature as soon as possible

**Comment by cwestMobile** [comment]
@praveen4D2 cmon man just be patient. You've asked like 6 times in the last few days. They have been working on it for a long time, it'll happen when it happens.

**Comment by s4cha** [comment]
https://github.com/Yummypets/YPImagePicker/releases/tag/3.0.0 🎉
