### ISSUE TITLE
Strange crash

### ISSUE THREAD

**Issue by AndreiBoariu** [Yummypets/YPImagePicker#106]
Here is the report:
http://crashes.to/s/8af761e87ac

**Comment by AndreiBoariu** [comment]
`Fatal Exception: NSInvalidArgumentException`
`0  CoreFoundation                 0x184582d8c __exceptionPreprocess`
`1  libobjc.A.dylib                0x18373c5ec objc_exception_throw`
`2  AVFoundation                   0x18a05a124 __copy_helper_block_.845`
`3  libdispatch.dylib              0x183e74ae4 _dispatch_client_callout`
`4  libdispatch.dylib              0x183e7d640 _dispatch_queue_barrier_sync_invoke_and_complete`
`5  AVFoundation                   0x18a059fec -[AVCaptureFigVideoDevice setActiveColorSpace:]`
`6  Foundation                     0x184ee8568 -[NSObject(NSKeyValueObservingPrivate) _changeValueForKeys:count:maybeOldValuesDict:usingBlock:]`
`7  Foundation                     0x184f10534 -[NSObject(NSKeyValueObservingPrivate) _changeValueForKey:key:key:usingBlock:]`
`8  Foundation                     0x184f9497c _NSSetLongLongValueAndNotify`
`9  AVFoundation                   0x18a0767c8 -[AVCaptureSession _updateDeviceActiveFormatsAndActiveConnections]`
`10 AVFoundation                   0x18a074cc8 -[AVCaptureSession _buildAndRunGraph]`
`11 AVFoundation                   0x18a06edcc -[AVCaptureSession _commitConfiguration]`
`12 AVFoundation                   0x18a0709b8 -[AVCaptureSession addOutput:]`
`13 YPImagePicker                  0x1041b5ae4 YPPhotoCapture.setupCaptureSession() -> () (YPPhotoCaptureDefaults.swift:38)`
`14 YPImagePicker                  0x1041b63f8 partial apply for YPPhotoCapture.(setup(with : UIView) -> ()).(closure #1) (YPPhotoCaptureDefaults.swift:19)`
`15 YPImagePicker                  0x1041b6f98 _T0Ieg_IeyB_TR (YPPickerVC.swift)`
`16 libdispatch.dylib              0x183e74b24 _dispatch_call_block_and_release`
`17 libdispatch.dylib              0x183e74ae4 _dispatch_client_callout`
`18 libdispatch.dylib              0x183e7ea38 _dispatch_queue_serial_drain$VARIANT$mp`
`19 libdispatch.dylib              0x183e7f380 _dispatch_queue_invoke$VARIANT$mp`
`20 libdispatch.dylib              0x183e7fd4c _dispatch_root_queue_drain_deferred_wlh$VARIANT$mp`
`21 libdispatch.dylib              0x183e8811c _dispatch_workloop_worker_thread$VARIANT$mp`
`22 libsystem_pthread.dylib        0x1841a7e70 _pthread_wqthread`
`23 libsystem_pthread.dylib        0x1841a7b08 start_wqthread`

**Comment by NikKovIos** [comment]
You should describe the steps to reproduce the crash.

**Comment by s4cha** [comment]
@AndreiBoariu Thanks for providing the crashlytics log, this is very helpful. Indeed, if you could find the steps that reproduce the crash in a deterministic way that would be even better :). By the way, very glad ClaimItApp uses the picker !!

**Comment by AndreiBoariu** [comment]
@NikKovIos @s4cha Thanks guys for reply!
Sorry because I did not provide any steps, but I am not very sure how to catch this.
I big words, I think it refers to #32 . User opens picker, but because it takes too long time to enable session, user taps on recording video, or take picture and this crash happens.

Guys, really appreciate your efforts to help with this great library. It helps our app a lot (60k users).
You did a great job.

**Comment by s4cha** [comment]
@AndreiBoariu please excuse the late reply, the 3.4.0 release should fix your issue :)
https://github.com/Yummypets/YPImagePicker/releases/tag/3.4.0

Thanks for the kind words !
