### ISSUE TITLE
only video from the library

### ISSUE THREAD

**Issue by kerimsener** [Yummypets/YPImagePicker#110]
how to get only videos from the library?

**Comment by DullBottle** [comment]
I have the same problems，any one have some ideas?

**Comment by s4cha** [comment]
@abdulkrm & @DullBottle This is not possible at the moment but this is something that's on our roadmap short term :)

**Comment by DullBottle** [comment]
@s4cha thx for reply :)

**Comment by s4cha** [comment]
Actually https://github.com/Yummypets/YPImagePicker/pull/107 just got merged which is going to enable this feature soon! Thank @portellaa  :)

**Comment by s4cha** [comment]
https://github.com/Yummypets/YPImagePicker/releases/tag/3.0.0 🎉

**Comment by s4cha** [comment]
The new api is
```swift
config.libraryMediaType = .video
```

Enjoy :)
