### ISSUE TITLE
Add video cropping option

### ISSUE THREAD

**Issue by chintanMaisuriya** [Yummypets/YPImagePicker#112]
When we need to select and upload video from application, there should be an option of video cropping into YPImagepicker so users can easily select video of any duration instead of current option we're applying of duration-limit. It would be useful feature. Hope you guys will look into this ASAP.

Thank you :)

**Comment by s4cha** [comment]
@chintanMaisuriya We're actually working on video trimming in the multipleSelection PR here https://github.com/Yummypets/YPImagePicker/pull/47 :)

**Comment by s4cha** [comment]
@chintanMaisuriya in the latest release `3.0.0` we have now Video cropping and video trimming.
you can restrict video time beforehand by using: 
```swift
config.videoFromLibraryTimeLimit = 60 // 60 seconds max selection
config.videoMinimumTimeLimit = 3.0 // 3 seconds min selection
```
Then the user is free to trim the video
```swift
config.trimmerMaxDuration = 10 // user selects a 10s max portion
config.trimmerMinDuration = 1 // user selects a 1s min portion
```

Cheers !

Closing this for now, don't hesitate to reopen if needed :)

**Comment by TomWFox** [comment]
Hi,

I set the following config:
```
config.video.libraryTimeLimit = 200
config.video.trimmerMaxDuration = 40
```

But if I select a video of 1 minute don't trim it and press done there is no message saying that the video needs to be trimmed.

**Comment by pduvall** [comment]
Further to Tom's previous comment, there is still no apparent way to enforce a max duration limit on videos while also allowing longer videos from the library to be trimmed to that same max duration. This would be very helpful for some common use cases, and most of the necessary functionality to accomplish this is already implemented in the library.
