### ISSUE TITLE
Dismiss without animation

### ISSUE THREAD

**Issue by MehdiBrandoMahdloo** [Yummypets/YPImagePicker#113]
Hello! 
I need to dismiss the Picker view without the animation ("YPPickerVC class, line 299).
Can you add the parameter so it can be set to true or false?
It may be very useful!
Thank you again for your awesome library!
Cheers!

**Comment by s4cha** [comment]
@WeDrinkInAssembly This is a very good point!
Actually users will be responsible for dismissing the picker themselves in the future versions. This gives more control, such as animation as you pointed out.
I'll ping you when it's live :)

**Comment by s4cha** [comment]
@WeDrinkInAssembly this should be resolved in https://github.com/Yummypets/YPImagePicker/releases/tag/3.1.0 :)
Thanks for taking the time to report the issue 👍

**Comment by s4cha** [comment]
@WeDrinkInAssembly closing this for now as this is supported in the latest releases, feel free to reopen if needed :)
