### ISSUE TITLE
Latest Version not updated

### ISSUE THREAD

**Issue by praveen4D2** [Yummypets/YPImagePicker#116]
Hi,
I am trying to update latest version of library using pod but the same version has updated.

**Comment by s4cha** [comment]
Hey @praveen4D2 my bad, Carthage was up, but not Cocoapods, could you try again now please?

**Comment by praveen4D2** [comment]
Hi,
I again tried but its not updated , kindly fix the issue ?

**Comment by s4cha** [comment]
Hi @praveen4D2,
The pod is up here https://cocoapods.org/pods/YPImagePicker.
I just tried integrating it through Cocoapods on my side and it worked well.
Have you tried running `pod repo update` before calling `pod update` ?

Let me know how this goes,

**Comment by 10000TB** [comment]
@s4cha  seems still not updated.   One direct indication is: `libraryMediaType` is not a member of 'YPImagePickerConfiguration' (from pod). But the source within example has that definition.

**Comment by 10000TB** [comment]
ACK: latest Pod works for me.  Thanks @s4cha

**Comment by s4cha** [comment]
Awesome ! @praveen4D2 can we close this?

**Comment by s4cha** [comment]
Closing this for now, don't hesitate to reopen if needed :)
