### ISSUE TITLE
Module compiled with Swift 4.1 cannot be imported in Swift 4.0.3:

### ISSUE THREAD

**Issue by ljs19923** [Yummypets/YPImagePicker#117]
I got this error... do you know why ?

**Comment by cwestMobile** [comment]
You probably aren't on the latest version of Xcode. I had this same error and updated versions to get it to go away. Cheers.

**Comment by s4cha** [comment]
Hey @JulienLevallois, I think @cwestMobile is right.
I assume you are using Carthage.
If you don't want to use the latest version of Xcode (with which the pre-packaged framework was built) . You can force Carthage to build locally, (with your Xcode version)
Just run `carthage update --no-use-binaries`

Hope this helps,

**Comment by s4cha** [comment]
@JulienLevallois Were you able to solve the issue?

**Comment by ljs19923** [comment]
Yes its okay thanks

**Comment by s4cha** [comment]
Great! Closing this then :)
