### ISSUE TITLE
Creates a new duplicated photo after cropping, even if nothing changed

### ISSUE THREAD

**Issue by mirjalolbahodirov** [Yummypets/YPImagePicker#118]
In my situation, `config.showsCrop = .rectangle(ratio: 1.0)`
If I select photo which is already square, ImagePicker shows cropping step.
After this I changed nothing and clicked **Save** button (there is not other option to pick photo in this step).
I successfully chose a photo, but I got another **duplicate** of the chosen photo in the album

Thanks in advance! 😃

**Comment by mirjalolbahodirov** [comment]
Sorry, I found `config.shouldSaveNewPicturesToAlbum = false`
My bad 👎

**Comment by NikKovIos** [comment]
Btw, if you need to let user take only square, there is another option for this in the framework. With it the crop rect would be taken from the library. However, I think that the photo shouldn’t be saved if it’s already cropped and not filtered.

**Comment by mirjalolbahodirov** [comment]
Yes you are right. It would be better if the library did not save the unchanged photo

**Comment by s4cha** [comment]
@mirjalolbahodirov 
Indeed
```swift
var config = YPImagePickerConfiguration()
config.library.onlySquare = true
// config.onlySquareImagesFromCamera = true // default
// config.showsCrop = .rectangle(ratio: 1.0) // becomes useless
let picker = YPImagePicker(configuration: config)
```
This will yield only squared photos :)

**Comment by s4cha** [comment]
By default with the above conf, filtered photos will be saved, you can use `config.shouldSaveNewPicturesToAlbum = false` to make sure nothing is saved \o/

**Comment by s4cha** [comment]
Feel free to reopen if needed :)
