### ISSUE TITLE
Camera flash doesn't work on iOS 10.3.3

### ISSUE THREAD

**Issue by yybot1** [Yummypets/YPImagePicker#120]
iPhone 5c, iOS 10.3.3, YPImagePicker 3.0.0, Xcode 9.3.1

Camera flash doesn't work when turning on.  And if swap front/back camera then click the flash button, the flash button will disappear.

**Comment by s4cha** [comment]
@yybot1, Just tried, not happening on my side (iPhone X)
Do you have other devices around to confirm this is only happening on iPhone 5c?
I am going to try on other devices in the meantime :)
Cheers,

**Comment by s4cha** [comment]
@yybot1 Works fine on iPhone6 (iOS11). Is there a way you could try on iOS 11?

**Comment by yybot1** [comment]
Currently, I only have iPhone 5c around. Older devices cannot update to iOS 11, so I think iOS 10 still needs to be supported. As the title says, I just reported flash doesn't work on iOS 10.3.3, older devices still use this version. It seems other features work fine on iOS 10, just the flash doesn't work.

**Comment by s4cha** [comment]
@yybot1 I don't have one around, would you mind taking a crack at solving it?

**Comment by s4cha** [comment]
@yybot1 this should be fixed in This is now solved in https://github.com/Yummypets/YPImagePicker/releases/tag/4.0.0. If it's not feel free to reopen :)
