### ISSUE TITLE
Asking for all permissions on the first screen

### ISSUE THREAD

**Issue by DamascenoRafael** [Yummypets/YPImagePicker#122]
Currently as soon as the picker is displayed all the permissions related to the selection methods are displayed, even if they are not related to the screen that is shown at launch.

For example even my launch screen being the library, when the picker is opened the permission to use the camera is already displayed.

I believe it would be interesting if the use permissions were only shown when really needed. If my launch screen is the library it only makes sense to ask permission for this access and if the user switches to the camera screen ask for the related permissions.

Thanks for the great lib.

**Comment by NikKovIos** [comment]
Thought about it too.

**Comment by DamascenoRafael** [comment]
Any idea how we can achieve this?

**Comment by s4cha** [comment]
@DamascenoRafael Pretty busy this week to tackle any feature but I'll have time to give it a shot next week. Honestly don't know if we can request single permissions via Apple api. I'd have to look into it.

**Comment by s4cha** [comment]
@DamascenoRafael I'm looking at it at the moment :)

**Comment by DamascenoRafael** [comment]
Great @s4cha! If the first screen is `.photo` the permission for the `library` will not be requested. The problem seems to be only the `.photo` request (maybe `.video` too) that is always requested if it is between the screens.

**Comment by s4cha** [comment]
@DamascenoRafael This is live as of 3.3.0 :) https://github.com/Yummypets/YPImagePicker/releases/tag/3.3.0
