### ISSUE TITLE
Help needed for translations

### ISSUE THREAD

**Issue by s4cha** [Yummypets/YPImagePicker#124]
Hey guys, as you may know `3.0.0` came with some extra features and extra wordings.

We are missing some translations and that would be awesome if you could help us fill in the gaps !

### Dutch
"YPImagePickerCrop" = "Crop";
"YPImagePickerProcessing" = "Processing..";
@CIronfounderson 

### Brazilian
"YPImagePickerProcessing" = "Processing..";
@DamascenoRafael

### Turkish
"YPImagePickerCrop" = "Crop";
"YPImagePickerProcessing" = "Processing..";
@tahaburak 

### Arabic
"YPImagePickerAlbums" = "Albums";
"YPImagePickerCancel" = "Cancel";
"YPImagePickerCover" = "Cover";
"YPImagePickerCrop" = "Crop";
"YPImagePickerDone" = "Done";
"YPImagePickerOk" = "Ok";
"YPImagePickerProcessing" = "Processing..";
"YPImagePickerSave" = "Save";
"YPImagePickerTrim" = "Trim";
"YPImagePickerVideoTooShort" = "The video must be at least %@ seconds";
"YPImagePickerWarningItemsLimit" = "The limit is %d photos or videos";
@hanikeddah

### German
"YPImagePickerCrop" = "Crop";
"YPImagePickerProcessing" = "Processing..";
@Anarchoschnitzel 

### Italian
"YPImagePickerProcessing" = "Processing..";
@Viktormax

**Comment by NikKovIos** [comment]
I LOVE that international collaboration =)

**Comment by MV-EricDeHaan** [comment]
"YPImagePickerCrop" = "Crop" => "Bijsnijden"
"YPImagePickerProcessing" = "Processing.." => "Verwerken..."
@CIronfounderson
