### ISSUE TITLE
Crashes (and black square) when Photo Library permission is denied

### ISSUE THREAD

**Issue by artemsmikh** [Yummypets/YPImagePicker#13]
When I open the picker for the first time it asks me for permissions. If I deny the first request (Photo Library), then allow the second (Camera usage) and then deny the third one (Microphone) then, at first, it shows a black square instead of a camera preview (although the camera permission was granted). If I switch to the photo library picker (which is unaccessible due to denied permission and it's ok) and then switch again to the camera preview it shows normally.
And then, if I took a photo, it'll crash with this message: 

> This application is not allowed to access Photo data.

It happens even when the `shouldSaveNewPicturesToAlbum` is set to `false`

The full crash stack trace:

> [Generic] *** This application is not allowed to access Photo data. (
	0   PhotoLibraryServices                0x000000018fad5f38 <redacted> + 1096
	1   Photos                              0x000000019091b63c <redacted> + 84
	2   Photos                              0x00000001908ec664 <redacted> + 128
	3   Photos                              0x0000000190903834 <redacted> + 196
	4   YPImagePicker                       0x0000000106247c28 _T013YPImagePicker9FSAlbumVCCfETo + 176
	5   libobjc.A.dylib                     0x0000000181822ef4 <redacted> + 148
	6   libobjc.A.dylib                     0x0000000181830638 objc_destructInstance + 88
	7   libobjc.A.dylib                     0x0000000181830690 object_dispose + 16
	8   UIKit                               0x000000018bad78f4 <redacted> + 156
	9   UIKit                               0x000000018b88de7c <redacted> + 1776
	10  YPImagePicker                       0x0000000106247b30 _T013YPImagePicker9FSAlbumVCCfD + 220
	11  YPImagePicker                       0x0000000106247b68 _T013YPImagePicker9FSAlbumVCCfDTo + 40
	12  libswiftCore.dylib                  0x00000001066a9798 _ZN5swift12metadataimpl14ValueWitnessesINS0_17ObjCRetainableBoxEE12destroyArrayEPNS_11OpaqueValueEmPKNS_14TargetMetadataINS_9InProcessEEE + 36
	13  libswiftCore.dylib                  0x000000010643aa7c _T0s23_ContiguousArrayStorageCfD + 60
	14  libswiftCore.dylib                  0x00000001066a7280 _swift_release_dealloc + 28
	15  YPImagePicker                       0x000000010626a648 _T013YPImagePicker13FSBottomPagerCfETo + 80
	16  libobjc.A.dylib                     0x0000000181822ef4 <redacted> + 148
	17  libobjc.A.dylib                     0x0000000181830638 objc_destructInstance + 88
	18  libobjc.A.dylib                     0x0000000181830690 object_dispose + 16
	19  UIKit                               0x000000018bad78f4 <redacted> + 156
	20  UIKit                               0x000000018b88de7c <redacted> + 1776
	21  YPImagePicker                       0x00000001062a1c50 _T013YPImagePickerAACfETo + 120
	22  libobjc.A.dylib                     0x0000000181822ef4 <redacted> + 148
	23  libobjc.A.dylib                     0x0000000181830638 objc_destructInstance + 88
	24  libobjc.A.dylib                     0x0000000181830690 object_dispose + 16
	25  UIKit                               0x000000018bad78f4 <redacted> + 156
	26  UIKit                               0x000000018b88de7c <redacted> + 1776
	27  UIKit                               0x000000018b8987e4 <redacted> + 488
	28  UIKit                               0x000000018ba6b730 <redacted> + 372
	29  libobjc.A.dylib                     0x0000000181822ef4 <redacted> + 148
	30  libobjc.A.dylib                     0x0000000181830638 objc_destructInstance + 88
	31  libobjc.A.dylib                     0x0000000181830690 object_dispose + 16
	32  UIKit                               0x000000018ba66f1c <redacted> + 64
	33  UIKit                               0x000000018c2abcc4 <redacted> + 64
	34  UIKit                               0x000000018ba66ba8 <redacted> + 24
	35  libsystem_blocks.dylib              0x0000000181d35a60 _Block_release + 160
	36  UIKit                               0x000000018c39dbec <redacted> + 116
	37  libobjc.A.dylib                     0x0000000181822ef4 <redacted> + 148
	38  libobjc.A.dylib                     0x0000000181830638 objc_destructInstance + 88
	39  libobjc.A.dylib                     0x0000000181830690 object_dispose + 16
	40  UIKit                               0x000000018b833b90 <redacted> + 64
	41  UIKit                               0x000000018b833b40 <redacted> + 88
	42  libobjc.A.dylib                     0x0000000181822ef4 <redacted> + 148
	43  libobjc.A.dylib                     0x0000000181830638 objc_destructInstance + 88
	44  libobjc.A.dylib                     0x0000000181830690 object_dispose + 16
	45  UIKit                               0x000000018b832334 <redacted> + 1340
	46  UIKit                               0x000000018b831de4 <redacted> + 120
	47  UIKit                               0x000000018b75770c <redacted> + 312
	48  UIKit                               0x000000018b757418 <redacted> + 296
	49  UIKit                               0x000000018b7574b8 <redacted> + 456
	50  QuartzCore                          0x00000001862fbd6c <redacted> + 284
	51  libdispatch.dylib                   0x0000000106f7145c _dispatch_client_callout + 16
	52  libdispatch.dylib                   0x0000000106f76050 _dispatch_main_queue_callback_4CF + 1192
	53  CoreFoundation                      0x00000001822b7f20 <redacted> + 12
	54  CoreFoundation                      0x00000001822b5afc <redacted> + 2012
	55  CoreFoundation                      0x00000001821d62d8 CFRunLoopRunSpecific + 436
	56  GraphicsServices                    0x0000000184067f84 GSEventRunModal + 100
	57  UIKit                               0x000000018b783880 UIApplicationMain + 208
	58  myExample                              0x0000000104eedd08 main + 76
	59  libdyld.dylib                       0x0000000181cfa56c <redacted> + 4
)

**Comment by s4cha** [comment]
@artemsmikh I just reproduced the issue, thanks for the detailed explanation :)
I'm on it! In the mean time there is v2.2.0 that improves denied permissions if you missed it https://github.com/Yummypets/YPImagePicker/releases/tag/2.2.0

**Comment by s4cha** [comment]
This is V weird :/ I thought the crash was happening when we try to save the pic, but no it's when the Picker is destroyed. Still searching but nothing for the moment. maybe it's an Apple bug ? -> http://www.openradar.me/22376207

**Comment by artemsmikh** [comment]
Hmm. I can't reproduce this issue now. Have you done something to fix it?

**Comment by s4cha** [comment]
@artemsmikh Indeed I fixed it a couple days ago but haven't made a version yet so it's weird it's fixed on your side :)
https://github.com/Yummypets/YPImagePicker/commit/eac13d97112831e1f2f520d10ea8a58123849438
Are you using the latest code or Carthage/ Cocoapods ?

**Comment by s4cha** [comment]
@artemsmikh 2.4.0 release should solve you issue, at least the crash :)

https://github.com/Yummypets/YPImagePicker/releases/tag/2.4.0

Have a fantastic day !

**Comment by s4cha** [comment]
Closing this for now, feel free to reopen if it ever comes back :)
