### ISSUE TITLE
After multiple selection enable paging of images

### ISSUE THREAD

**Issue by cwestMobile** [Yummypets/YPImagePicker#135]
I noticed yesterday evening that if you select 2+ images when you reach the page to review the images, while scrolling through paging is not enabled. This just feels a little weird, I can take a crack at it for you guys if you would like it implemented. If you have any questions I'll send a video.

Cheers.

**Comment by NikKovIos** [comment]
Sorry, but i didn't understand, where is a bug.

**Comment by s4cha** [comment]
@NikKovIos I think it refers to the paging in the gallery scrollview.
Looking at Instagram app, paging only occurs when coming back, scrolling from right to left. This shouldn't be to hard to implement :)

**Comment by s4cha** [comment]
@cwestMobile This should be ok in 3.4.0 https://github.com/Yummypets/YPImagePicker/releases/tag/3.4.0 🚀 🚀

**Comment by s4cha** [comment]
Closing this for now, please reopen if the latest version is not what you expected :)
