### ISSUE TITLE
Camera doesn't work second time, if there are two screens ` Gallery and Photo.

### ISSUE THREAD

**Issue by GShushanik** [Yummypets/YPImagePicker#136]
iPhone 6s, iOS 11.3.1, YPImagePicker 3.1.0 (commit: a1ee2edcfd074b54c33ef0cbd0b6273b4dfa3856), Xcode 9.3.1
After giving access to camera and photo, Gallery and Photo tab updated well. But after rebuilding app again I see Photo tab frozen (camera not working).
I tested it on demo project, and change only this configuration
config.screens = [.library, .photo]

Thanks in advance.

![image uploaded from ios](https://user-images.githubusercontent.com/23483940/40726310-84f196aa-6436-11e8-8c6c-b258615a1ec4.png)

**Comment by s4cha** [comment]
@GShushanik maybe this is linked to https://github.com/Yummypets/YPImagePicker/issues/32
?
I don't reproduce in on my side following your explanation :/
Do you reproduce it everytime?
Also can you try the same on another device model ?
Cheers,

**Comment by GShushanik** [comment]
@s4cha I tried it on other devices, but couldn't reproduce it.  :/
I've restart my device and it seems work well. 😮 
Thanks.

**Comment by s4cha** [comment]
@GShushanik Great thanks! Let's Close this for now and we'll see if that comes back :)
