### ISSUE TITLE
Cropping not work with video recording.

### ISSUE THREAD

**Issue by pngo-hypewell** [Yummypets/YPImagePicker#137]
Seem now, the cropping feature only work for video on library, right ?
Or I need enable something to do that ?

**Comment by s4cha** [comment]
@pngo-hypewell you mean the extra view to trim the video ?

**Comment by s4cha** [comment]
@pngo-hypewell any chance you have `config.showsFilters = false` 
Actually this setting displays both filters (for photos) and trimming feature (for videos)
I think This should be distinct settings in a future release.

@NikKovIos ?

**Comment by pngo-hypewell** [comment]
@s4cha I mean the **square cropping** (_not video trimming_) for video recording. Now, after recording a video, it shows the trimming page and I can't make the video square.

I agree that **showsFilters** and **showsVideoTrimming** should be distinct settings.

P/S: The square cropping is working very well with video from library.

**Comment by s4cha** [comment]
@pngo-hypewell Ahhhhhh got it :)
Thanks for you input on the unrelated topic then 👍 
Would forcing taking squared video upfront work? I can't really picture a use case where you would take a non squared video then crop it. 

In the case where you would want the user to choose squared or not, I think doing it upfront with a toggle on the camera view would make more sense.

Hope I'm clear (it's late :p)

Cheers!

**Comment by pngo-hypewell** [comment]
You can see the attachment. When I record, I assume it's a square video. But the result is a fullscreen video. It should be square for the current version.

![videogif](https://user-images.githubusercontent.com/35468242/40813903-0bf25b6a-64f2-11e8-9075-17220db94edb.gif)

**Comment by NikKovIos** [comment]
Fixed in https://github.com/Yummypets/YPImagePicker/releases/tag/3.4.1 
Fill free to reopen ;)

**Comment by nitingohel** [comment]
I am not sure but the issue is there. as you can see there is crop review there after choosing video from gallery or record then on next it show full video not cropped video. check the attached video so you guys can notice the bug.

Crop working for image very well not crop not working for video anymore.

looking for solution please 



https://user-images.githubusercontent.com/5137595/120064912-53464280-c08c-11eb-8e1b-1221933344f4.mov
