### ISSUE TITLE
can customise the  Camera and Video View layout  height

### ISSUE THREAD

**Issue by eslammohamed99** [Yummypets/YPImagePicker#138]

**Comment by s4cha** [comment]
@eslammohamed99 Could you provide a bit more information please?

**Comment by eslammohamed99** [comment]
can i increase the height of the camera layout instead of the square layout
to take more space from the view

**Comment by NikKovIos** [comment]
If you mean to increase the height of the camera in the Photo and Video capture screens, than i think it could be a good feature. 
For example as setting the aspect ratio for the height. If 1:1 then the camera view would be with the full screen height. 

@s4cha i think we should add a template for the new issues, what do you think? Also what do you think about this suggestion?

**Comment by s4cha** [comment]
Well considering the number of issues yes a template would be great :)
Concerning the feature, yep I think this makes sense 👍

**Comment by NikKovIos** [comment]
Closing. Further discuss here https://github.com/Yummypets/YPImagePicker/issues/176
