### ISSUE TITLE
It looks like compression is not being implemented

### ISSUE THREAD

**Issue by lewisloofis** [Yummypets/YPImagePicker#140]
Hello,

I think I found another weird thing in this library. So whenever I change preset, either to AVAssetExportPresetMediumQuality or AVAssetExportPresetLowQuality my video size is still big, and when I look for your repository, you hardcoded the preset name to AVAssetExportPresetPassthrough so it is not using my video quality config. It's in AVAsset+Extensions.swift, func export

```swift
// Should this be my config.videoCompression setup?
guard let exportSession = AVAssetExportSession(asset: self, presetName: AVAssetExportPresetPassthrough) else {
            throw YPTrimError("Could not create an export session")
        }
```

**Comment by s4cha** [comment]
@lewisloofis Indeed!
Compression works fine with videos form the library but the setting was not applied when taking videos directly. The fix you suggest is the way to go indeed :) Going to make the change

**Comment by s4cha** [comment]
https://github.com/Yummypets/YPImagePicker/commit/27377f63d240ad27340b4c37ec934b5587cadf32

**Comment by lewisloofis** [comment]
Looks perfect, when it will be available?

**Comment by s4cha** [comment]
@lewisloofis I'm going to try and make a new version by tomorrow end of day :)

**Comment by s4cha** [comment]
Should be good as of 3.2.0 https://github.com/Yummypets/YPImagePicker/releases/tag/3.2.0
Thanks a ton for your help!

**Comment by s4cha** [comment]
Closing this as it should be fixed in latest release, feel free to reopen if needed!
Kudos for the eagle eye 🍻 !!
