### ISSUE TITLE
Pod install error for Pre release version

### ISSUE THREAD

**Issue by vivekkadam03** [Yummypets/YPImagePicker#143]
I tried to install Pre release version with -> pod 'YPImagePicker', :git => 'https://github.com/Yummypets/YPImagePicker.git', :branch => 'multipleSelection'

But it is showing something like this...
![screen shot 2018-06-07 at 7 03 41 pm](https://user-images.githubusercontent.com/40030828/41102911-934c5028-6a85-11e8-832f-2ca49ec87ba7.png)
Please help me out from this issue...

**Comment by s4cha** [comment]
@vivekkadam03 the latest version already includes the multiple selection :)
