### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by pdee2131** [Yummypets/YPImagePicker#144]
Cant use this library in swift 3

**Comment by s4cha** [comment]
@pdee2131 Good question, I believe this is not in our roadmap. Not 100percent sure of how we would approach that but I guess this would be too time consuming to maintain.
If you want to take a crack at it through a PR though, feel free :)

**Comment by pdee2131** [comment]
@s4cha i have been able to use the library but the last thing is to get the image after applying the filter
after clicking the done the app crashes. 


 picker.didFinishPicking { [unowned picker] items, _ in
            if let photo = items.singlePhoto {
                print(photo.fromCamera) // Image source (camera or library)
                print(photo.image) // Final image selected by the user
                print(photo.originalImage) // original image selected by the user, unfiltered
                print(photo.modifiedImage) // Transformed image, can be nil
                print(photo.exifMeta) // Print exif meta data of original image.
            }
            picker.dismiss(animated: true, completion: nil)
        }

this part of the code is not working ... there is no member in PickerVC as didFinishPicking

![screen shot 2018-06-12 at 16 28 51](https://user-images.githubusercontent.com/10502787/41303509-f616190c-6e5c-11e8-9285-c61236a3d9c9.png)

**Comment by s4cha** [comment]
@pdee2131 Weird, do you have any crash log by any chance?

**Comment by s4cha** [comment]
Also, does your `.plist` has the following entries ?
```xml
<key>NSCameraUsageDescription</key>
<string>yourWording</string>
<key>NSPhotoLibraryUsageDescription</key>
<string>yourWording</string>
<key>NSMicrophoneUsageDescription</key>
<string>yourWording</string>
```

**Comment by NikKovIos** [comment]
@s4cha imho we should use apple's policy about deprecations and not supporting legacy versions
What do you think about this? 

Concerning the issue. The app not seems to crash here. Please give a log and a line where it crashes. It could be because [unowned self] too.

**Comment by s4cha** [comment]
@NikKovIos Agreed Things move fast and supporting swift 3 will not be worth the invested time for our small team :)
