### ISSUE TITLE
YPAlbumVC , YPPickerVC 's close button  miss setting tintColor

### ISSUE THREAD

**Issue by boboxiaodd** [Yummypets/YPImagePicker#145]
https://github.com/Yummypets/YPImagePicker/blob/9e9cceaabf27514cda37a96b60c3d98d1ea7b89a/Source/YPPickerVC.swift#L256

insert this code:
````swift
navigationItem.leftBarButtonItem?.tintColor  = YPConfig.colors.tintColor
````

and
https://github.com/Yummypets/YPImagePicker/blob/9e9cceaabf27514cda37a96b60c3d98d1ea7b89a/Source/Pages/Gallery/YPAlbumVC.swift#L41
insert this code:
````swift
navigationItem.leftBarButtonItem?.tintColor  = YPConfig.colors.tintColor
````

**Comment by NikKovIos** [comment]
Could you please create a PR?
