### ISSUE TITLE
Cannot run Sample Project

### ISSUE THREAD

**Issue by Appswage** [Yummypets/YPImagePicker#149]
Installing via pods or a clone gives the following error when trying to run the example project. I don't use Carthage. 

`/Users/brower/Library/Developer/Xcode/DerivedData/YPImagePickerExample-coxmzlypcqvlhmdsbwsumvjvzusg/Build/Intermediates.noindex/YPImagePickerExample.build/Debug-iphoneos/YPImagePickerExample.build/Script-99428A261E7BE18700B765A9.sh: line 2: /usr/local/bin/carthage: No such file or directory`

**Comment by s4cha** [comment]
@Appswage Indeed, the sample project uses Carthage internally with the 
`/usr/local/bin/carthage copy-frameworks` script. 
I am going to look into it. In the meantime, you can install Carthage here https://github.com/Carthage/Carthage/releases/download/0.29.0/Carthage.pkg and this should work.
Thanks a ton for the report :)

**Comment by s4cha** [comment]
@Appswage If you clone again this should work now :)
