### ISSUE TITLE
Type 'UILayoutPriority' (aka 'Float') has no member 'defaultHigh'

### ISSUE THREAD

**Issue by Deepakepaisa** [Yummypets/YPImagePicker#15]
Respective Team,  
there is a error "Type 'UILayoutPriority' (aka 'Float') has no member 'defaultHigh"
in  Stevia+Constraints.swift class. Please guide us to solve that.

**Comment by s4cha** [comment]
Hi @Deepakepaisa this must have happened with swift 4, we'll update it in the next few days :)

**Comment by s4cha** [comment]
Hi @Deepakepaisa seems like you need to use Swift 4 with the release you're using. This warning happens when Stevia is built with Swift 3.2.

Hope this helps :)

**Comment by s4cha** [comment]
@Deepakepaisa Were you able to fix the issue ?

**Comment by s4cha** [comment]
?

**Comment by JigneshParekh7165** [comment]
Respective Team,
there is a error "Type 'UILayoutPriority' (aka 'Float') has no member 'defaultHigh"
in Stevia+Constraints.swift class. Please guide us to solve that. how can I fix this issue.

**Comment by s4cha** [comment]
Hi @Deepakepaisa, @JigneshParekh7165 , do you have the issue when testing the library with 
`pod try YPImagePicker` ?

**Comment by sebastienboulogne** [comment]
hi @s4cha even when compiling in swift 4 (Build settings => swift version => 4.0), i have the same problem :(
Is it possible to use your pod while compiling with Swift 3.2 ? Thanks man ;)

**Comment by sebastienboulogne** [comment]
trying to get the Swift 3 version with : pod 'YPImagePicker', '~> 1.2.1'
but get an error :( 
How to get the Swift 3 version ? thx

**Comment by sebastienboulogne** [comment]
Take a look Guys : https://useyourloaf.com/blog/easier-swift-layout-priorities/

**Comment by sebastienboulogne** [comment]
@s4cha You mentioned that we had to build in Swift 4 to avoid this error but even compiling in Swift, i still have the same error :(

**Comment by s4cha** [comment]
@sebastienboulogne 
Sorry for taking so long to reply.

There might be a way but Swift 3 is not officially supported.
Could you document the whole process? The way you download and your Xcode version please, so that I can try and reproduce it on my end?

Cheers,

**Comment by s4cha** [comment]
@sebastienboulogne, @Deepakepaisa, @JigneshParekh7165 Are you still experiencing the issue? and if so can you go into details about your installation process and all the versions involved? It's very hard to find the cause when I cannot reproduce it :/ 
Cheers,

**Comment by NikKovIos** [comment]
Closed due to lack of activity. Feel free to reopen 🤪
