### ISSUE TITLE
Two issues on multi selection mode

### ISSUE THREAD

**Issue by barisozr** [Yummypets/YPImagePicker#151]
1) When I clicked the image (collectionview didSelect) in gallery page, which was opened after selection of images, it crashed. Added breakpoint and saw that the crash occurred at line 72 in YPPhotoFiltersVC.swift file. I didn't want to filter, which I set in configuration, but it still opened. 

The shared configuration that I used;
```
func setup() {
        var config = YPImagePickerConfiguration()
        func setupLibrary() {
            config.library.mediaType = .photo
            config.library.onlySquare = false
            config.library.maxNumberOfItems = 5
            config.library.skipSelectionsGallery = false
        }
        func setupCamera() {
            config.targetImageSize = .original
            config.usesFrontCamera = true
            config.showsFilters = false
            config.filters = []
            config.shouldSaveNewPicturesToAlbum = true
            config.showsCrop = .none
            var screens:[YPPickerScreen] = [.library]
            if UIImagePickerController.isSourceTypeAvailable(.camera) {
                screens.append(.photo)
            }
            config.screens = screens
        }
        setupLibrary()
        setupCamera()
        config.startOnScreen = .library
        config.hidesStatusBar = false
        YPImagePickerConfiguration.shared = config
}
```

2) I tried to bypass the crash by changing the setting with `config.library.skipSelectionsGallery = true`. But this time, when I selected multi images and pressed next button, then the `didFinishPicking` function of the image picker was called twice.

**Comment by s4cha** [comment]
@barisozr Thanks for the detailed report! This surely looks like a bug indeed.
the didFinishPicking calls twice just got fixed so It'll be in the next version (ppbly later today).
I am going to look into it :)

**Comment by s4cha** [comment]
@barisozr https://github.com/Yummypets/YPImagePicker/commit/828aa47c0aca9fb9ffe6ad7f2069cbee0f1551a0 will fix 1 :)
2 should be fixed already in 3.2.0 -->  https://github.com/Yummypets/YPImagePicker/releases/tag/3.2.0

**Comment by barisozr** [comment]
@s4cha seems ok, I'll test and let you know :)

**Comment by s4cha** [comment]
@barisozr The second, "config.filters = []" crash is committed already so it'll be fixed in the next version :) (probably later today)
