### ISSUE TITLE
Send an asset Directly for Editing?

### ISSUE THREAD

**Issue by Appswage** [Yummypets/YPImagePicker#152]
I realize this is a "picker" but of course there are other features here for trimming, cropping, etc. Is it possible to send a video or image asset directly for editing versus having to go through the initial picker flow? In other words to instantiate it with an asset.

**Comment by luthfifr** [comment]
I need to do exactly as @Appswage described, can somebody help us?

**Comment by NikKovIos** [comment]
You have an Asset and need to init it like YPImage or YPVideo and present only filters, right? Or describe the flow you need.

**Comment by luthfifr** [comment]
@NikKovIos exactly, that’s what I mean, I already have an Asset (photo or video) and I want to use only the filter, and rest of the flow (after the filter) stays the same.

**Comment by Appswage** [comment]
@NikKovIos - I would suggest the process looks the same as everything you can do once an asset is selected in the existing process. So this means cropping, trimming and filters. Today you tap on an asset (video or image) and then you can manipulate it. This entry point would essentially start with an already selected asset and from there you can do everything you do as of today. Thanks.

**Comment by s4cha** [comment]
I've never thought of it but it is a very interesting use case indeed :)

**Comment by NikKovIos** [comment]
Too old issue. Feel free to open new.
