### ISSUE TITLE
Video Metadata

### ISSUE THREAD

**Issue by Appswage** [Yummypets/YPImagePicker#154]
There does not appear to be a way to get metadata on the video such as creation date or location. Is it possible to get the PHAsset back with the video (assuming it's from the library) so that metadata can be pulled?

**Comment by Appswage** [comment]
I had an immediate need around this so I added the functionality myself. I am passing back the `PHAsset `having extended the `YPMediaAsset`. I can now easily get to all metadata. This did not take terribly long on my side and I am not familiar at all with the code base. I imagine it will take those who are, a very short period. I am happy to share my updates here if needed. Thanks a lot for this library and hopefully this addition can be useful.

**Comment by NikKovIos** [comment]
Yeap, i think it can be useful, but this property must be in YPMediaVideo. Create a PR 🙏🏻

**Comment by s4cha** [comment]
@Appswage, Do you absolutely need the full `PHAsset` or a  `exifMeta : [String : Any]?` property would suffice?
This is what we did on `YPMediaPhoto` so we'll try to be consistent :)

**Comment by s4cha** [comment]
@Appswage  Would these info work for you? 
[
 "com.apple.quicktime.location.ISO6709" : "+45.5159-001.1255+008.684/",
"com.apple.quicktime.make" : "Apple",
"com.apple.quicktime.model" : "iPhone X",
"com.apple.quicktime.software": "11.3",
"com.apple.quicktime.creationdate": "2018-06-02T23:19:39+0200"
]

**Comment by Appswage** [comment]
@s4cha - Personally I find a PHAsset more useful and flexible. With a PHAsset you can read metadata in a structured way and perform updates or other functions. I think this is easier and quicker than parsing through the JSON, manually correcting for hemisphere for GPS data, etc. Completely understand wanting to be consistent and I am not trying to pollute this great library, but you get a lot more flexibility and usability with the PHAsset. Thanks for the consideration!

**Comment by s4cha** [comment]
@Appswage No problem, I actually share the point of view that giving the PHAsset is straightforward and will cover all the future needs 👍 
Quick question, how do you access the metadata in your case? from what I found I needed to get the AVAsset from the PHAsset first ? Maybe I'm missing something.
Cheers,

**Comment by Appswage** [comment]
@s4cha - You do not need to create an AVAsset from the PHAsset in order to get the metadata. You get it directly from the PHAsset. When I added to this library I had it return the PHAsset along with the URL and camera boolean. I called that PHAsset `asset` in the return. So with that mind here is how you would get a coordinate from the PHAsset:

`let lat = video.asset?.location?.coordinate.latitude`

I also did make the PHAsset and optional as I believe you wouldn't have this data if the media was just shot live and not stored in the library. In those cases I just take the current date/time and current location from outside this library.

**Comment by Appswage** [comment]
As a follow-on. The library doesn't appear to save a video captured within the library, to the device. Is the intention to let the developer handle this if they want via the returned URL? If yes, then no issue. If there is an intention to save a newly created video to the library, then it would also be good to hand back the PHAsset from that rather than nil as I indicated above I am currently doing with my quick patch.

**Comment by s4cha** [comment]
@Appswage, Thanks a ton for the info, we are going to take your approach :)

Concerning saving Videos taken live, this is indeed in the roadmap and tracked here:
https://github.com/Yummypets/YPImagePicker/issues/56

**Comment by s4cha** [comment]
`video.asset` is available in production versions so closing this. Feel free to reopen if needed :)
