### ISSUE TITLE
New Images Don't Save Without Interaction

### ISSUE THREAD

**Issue by Appswage** [Yummypets/YPImagePicker#158]
If you take a new picture within the library and tap "Next" until the library processes are done, the photo is not saved to the phone. The only way to get it to save is to tap a filter which includes "Normal" after which it will save. If the photo is newly taken, it should save regardless of whether a filter is selected.

**Comment by Appswage** [comment]
Below is my quick hack update to this in `YPImagePicker`. Now if a picture is **newly** taken in the library and no changes are made to it, it will still save as long as the shouldSave boolean is true. 

```
 case .photo(let photo):
                let completion = { (photo: YPMediaPhoto) in
                    let mediaItem = YPMediaItem.photo(p: photo)
                    // Save new image to the photo album
                    if YPConfig.shouldSaveNewPicturesToAlbum
                    {
                        var modifiedImage = photo.modifiedImage
                        if photo.fromCamera && modifiedImage == nil {
                            modifiedImage = photo.originalImage
                        }
                        if modifiedImage != nil {
                            YPPhotoSaver.trySaveImage(modifiedImage!, inAlbumNamed: YPConfig.albumName)
                        }
                    }
                    self.didSelect(items: [mediaItem])
                }
```

**Comment by s4cha** [comment]
Once again thanks for the report and the working fix, this is VERY much appreciated 🙏 !
