### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by hixfield** [Yummypets/YPImagePicker#159]
What is the recommended way to style the presented UI?
- different color of the navigation bar
- different fonts of the items in the navigation bar?
- different colours for the items in the navigation bar
- colours of bottom bar (I do not think its a standard UITabBar?) background and tint color

**Comment by s4cha** [comment]
We tried to keep things as native as possible, so this will be mostly through native Apis.

### Different color of the navigation bar
```swift
let coloredImage = UIImage(color: .red) // (this is a helper below)
UINavigationBar.appearance().setBackgroundImage(coloredImage, for: UIBarMetrics.default)
```
### Different fonts of the items in the navigation bar
```swift
let attributes = [NSAttributedStringKey.font : UIFont.systemFont(ofSize: 30, weight: .bold) ]
UINavigationBar.appearance().titleTextAttributes = attributes // Title fonts
UIBarButtonItem.appearance().setTitleTextAttributes(attributes, for: .normal) // Bar Button fonts
```

### Different colours for the items in the navigation bar
```swift
UINavigationBar.appearance().titleTextAttributes = [NSAttributedStringKey.foregroundColor : UIColor.yellow ] // Title color
UINavigationBar.appearance().tintColor = .red // Left. bar buttons
config.colors.tintColor = .green // Right bar buttons (actions)
```


## Colours of bottom bar
This is not supported at the moment but it'd be a good idea to provide a customisation entry point for this as well :)

We need to document this in the Readme :)


### UIImage+color helper
https://stackoverflow.com/questions/26542035/create-uiimage-with-solid-color-in-swift
```swift
public extension UIImage {
    public convenience init?(color: UIColor, size: CGSize = CGSize(width: 1, height: 1)) {
        let rect = CGRect(origin: .zero, size: size)
        UIGraphicsBeginImageContextWithOptions(rect.size, false, 0.0)
        color.setFill()
        UIRectFill(rect)
        let image = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()
        
        guard let cgImage = image?.cgImage else { return nil }
        self.init(cgImage: cgImage)
    }
}
``

**Comment by NikKovIos** [comment]
What about the thing, that appearance() do change in any instance, when we need to change only in separate class?

**Comment by s4cha** [comment]
@NikKovIos 
If you want to customise the picker only, you can use:
```swift
let pickerAppearrance = UINavigationBar.appearance(whenContainedInInstancesOf: [YPImagePicker.self])
```
:)

**Comment by hixfield** [comment]
I noticed the YPColors in configuration. Would that not do the trick?

**Comment by NikKovIos** [comment]
Does it affect to SelectionsGallery, Filters also?

**Comment by s4cha** [comment]
@hixfield We rely on `YPConfig.colors` only for things that are specific to the picker, for example the video trimer control color `trimmerMainColor` or the loader via `navigationBarActivityIndicatorColor`.

Hope that makes sense :)

**Comment by hixfield** [comment]
I managed to do some styling, but how to do the red items?

![screen shot 2018-06-16 at 09 47 36](https://user-images.githubusercontent.com/9302613/41496899-6f40a0a0-714a-11e8-9544-3c96cb91a45f.png)

**Comment by hixfield** [comment]
I made a fork and are looking at the code...
