### ISSUE TITLE
make library option to open first

### ISSUE THREAD

**Issue by ChintanWeapp** [Yummypets/YPImagePicker#16]
When we are creating object of YPImagePicker and present it as view controller I need to open Library option first insted of Photo. How to do that? Thanks.

**Comment by s4cha** [comment]
@ChintanWeapp I'm looking at it at the moment it shouldn't be too difficult to implement :)
Please excuse the late reply,

Cheers

**Comment by s4cha** [comment]
would such an api work for you?

```swift
config.startOnScreen = .library //.video, defaults to .photo
```

**Comment by ChintanWeapp** [comment]
I have write this line in the code as following block  func showPicker() -> Void {

        var config                          = YPImagePickerConfiguration()
        config.startOnScreen = .library 
        config.onlySquareImagesFromLibrary  = false
        config.onlySquareImagesFromCamera   = true
        config.libraryTargetImageSize       = .original
        config.showsVideo                   = true
        config.usesFrontCamera              = false
        config.showsFilters                 = true
        config.shouldSaveNewPicturesToAlbum = true
        config.videoCompression             = AVAssetExportPresetHighestQuality
        config.albumName                    = "Yearbook"
        
        // Build a picker with your configuration
        let picker = YPImagePicker(configuration: config)}
}

But it gives an error. If I've made any mistake to write it, where should I write this ?

**Comment by s4cha** [comment]
@ChintanWeapp,
It's totally normal, the api above is not yet released. I wanted to make sure you agreed before releasing it :)

**Comment by ChintanWeapp** [comment]
Oh! Ok Sir. Thanks for the support.

**Comment by s4cha** [comment]
@ChintanWeapp  This is now available in 2.4.0 
https://github.com/Yummypets/YPImagePicker/releases/tag/2.4.0

Thanks for the request @ChintanWeapp  :)

Let me know if that works as you expected,

Have a fantastic day and year 2018 !

**Comment by userdar** [comment]
well @s4cha  it works but there is a problem when set startonscreen = .library there is no next button up right :). when you switch to another mode (photo in my case) next button comes :)

**Comment by s4cha** [comment]
@userdar oops that's weird indeed! I'm going to look into this now, thanks for your help and patience :)

**Comment by s4cha** [comment]
@userdar https://github.com/Yummypets/YPImagePicker/releases/tag/2.4.1
should solve your issue ;)

**Comment by s4cha** [comment]
Closing this for now, don't hesitate to reopen if you encounter issues :)

**Comment by RogelioHIT** [comment]
Hi, I'm setting video as start screen, but keeps going to library my config is

```
var config = YPImagePickerConfiguration()
config.usesFrontCamera = false
config.showsPhotoFilters = false
config.showsVideoTrimmer = false
config.shouldSaveNewPicturesToAlbum = false
if isVideoRequired {
  config.screens = [.library, .video]
  config.library.mediaType = .video
  config.startOnScreen = .video
}
```

I'm doing something wrong? or is there another way to force this?
The problem is that if the device don't have any video, it just closes the picker, and it seems like an error
