### ISSUE TITLE
Cancel button cannot exit dismiss current viewcontroller

### ISSUE THREAD

**Issue by kb100824** [Yummypets/YPImagePicker#160]
![1](https://user-images.githubusercontent.com/8489350/41462281-ef81a682-70c4-11e8-8cf2-045a7269418d.gif)

**Comment by s4cha** [comment]
I think what you are looking for is :
```swift
picker.didFinishPicking { [unowned picker] items, cancelled in
    picker.dismiss(animated: true, completion: nil)
}
```
In the latest releases, it's now the client's responsibility to dismiss the picker :)

**Comment by kb100824** [comment]
@s4cha   The code is the same as yours, but clicking the cancel button dismiss the current viewcontroller takes a long delay to dimiss the current viewcontroller

**Comment by s4cha** [comment]
So it does dismiss but takes a long time? This is weird to say the least :) I am unfortunately unable to reproduce on my end. Have you tried the Example project provided ? Does it happen there on your side?

Cheers,

**Comment by s4cha** [comment]
@KBvsMJ have you had time to try the example project ? any updates on this?

**Comment by datacosmos** [comment]
I had the same issue, but this was caused by checking for cancelled too late, I had sth. like this:
```swift
picker.didFinishPicking { [unowned picker] items, cancelled in
            if let photo = items.singlePhoto, let img = photo.modifiedImage {
         .....
              if cancelled {
                 log.debug("PH: Did Cancel")
                 picker.dismiss(animated: true, completion: nil)
                 return
             }
         }
```
 
So the  code above checked for cancellation only **after** an image was chosen!

This worked for me:

```swift
picker.didFinishPicking { [unowned picker] items, cancelled in
            if cancelled {
                log.debug("PH: Did Cancel")
                picker.dismiss(animated: true, completion: nil)
                return
            }
            if let photo = items.singlePhoto, let img = photo.modifiedImage {
...
```

Hope that helps anyone.

**Comment by s4cha** [comment]
@datacosmos Thanks for your input :) @KBvsMJ Did that solve your issue?

**Comment by kb100824** [comment]
@s4cha  it's ok

**Comment by ashish752** [comment]
Thanks
