### ISSUE TITLE
Landscape Videos Rotated

### ISSUE THREAD

**Issue by Appswage** [Yummypets/YPImagePicker#161]
It seems all videos that are taken "live" from the library come out in portrait orientation. If a video is taken landscape, it is rotated and sideways for editing and output.

**Comment by Appswage** [comment]
I've solved this issue by adding the following in `YPVideoHelper`

```
    func currentVideoOrientation() -> AVCaptureVideoOrientation {
        var orientation: AVCaptureVideoOrientation
        
        switch UIDevice.current.orientation {
        case .portrait:
            orientation = AVCaptureVideoOrientation.portrait
        case .landscapeRight:
            orientation = AVCaptureVideoOrientation.landscapeLeft
        case .portraitUpsideDown:
            orientation = AVCaptureVideoOrientation.portraitUpsideDown
        default:
            orientation = AVCaptureVideoOrientation.landscapeRight
        }
        
        return orientation
    }
```

Add the `connection` bit.

```
public func startRecording() {
        let outputPath = "\(NSTemporaryDirectory())output.mov"
        let outputURL = URL(fileURLWithPath: outputPath)
        let fileManager = FileManager.default
        if fileManager.fileExists(atPath: outputPath) {
            do {
                try fileManager.removeItem(atPath: outputPath)
            } catch {
                return
            }
        }
        
        let connection = videoOutput.connection(with: AVMediaType.video)
        if (connection?.isVideoOrientationSupported)! {
            connection?.videoOrientation = currentVideoOrientation()
        }
        
        videoOutput.startRecording(to: outputURL, recordingDelegate: self)
    }
    
    public func stopRecording() {
        videoOutput.stopRecording()
    }
    
```

**Comment by s4cha** [comment]
@Appswage  Your fix is in the pipe here: https://github.com/Yummypets/YPImagePicker/pull/163

I want to say your help as been very precious lately.
And as a maintainer, you gotta love the issues that come with a working fix 👍 
Feel free to create Pull requests in the future 🎉 
Have an awesome day !

**Comment by s4cha** [comment]
@Appswage This is live as of 3.3.0 :) https://github.com/Yummypets/YPImagePicker/releases/tag/3.3.0

**Comment by Appswage** [comment]
@s4cha - Awesome, thanks for being so responsive!

**Comment by Appswage** [comment]
@s4cha - I need to make an update to the above code. I found that if the phone is portrait locked from settings, the video would not be properly oriented if taken in landscape mode. I'd suggest replacing my orientation function with this one which can still detect orientation when portrait locked.  This uses CoreMotion which of course needs to be imported at the top of class. Also add a property called motionManager of type CMMotionManager. 

   ```
 private func checkOrientation(completion: @escaping(_ orientation:AVCaptureVideoOrientation?)->()) 
    {
        self.motionManager = CMMotionManager()
        self.motionManager.accelerometerUpdateInterval = 0.2
        
        self.motionManager.startAccelerometerUpdates( to: OperationQueue() ) { data, _ in
            guard data != nil else {completion(nil);return}
            let data = data!

            let orientation = abs(data.acceleration.y) < abs(data.acceleration.x)
                ?   data.acceleration.x > 0 ? AVCaptureVideoOrientation.landscapeLeft      :  AVCaptureVideoOrientation.landscapeRight
                :   data.acceleration.y > 0 ? AVCaptureVideoOrientation.portraitUpsideDown  :   AVCaptureVideoOrientation.portrait
            
            completion(orientation)
        }
    }
```

```
public func startRecording() {
        let outputPath = "\(NSTemporaryDirectory())output.mov"
        let outputURL = URL(fileURLWithPath: outputPath)
        let fileManager = FileManager.default
        if fileManager.fileExists(atPath: outputPath) {
            do {
                try fileManager.removeItem(atPath: outputPath)
            } catch {
                return
            }
        }
        
        checkOrientation { (orientation) in
            self.motionManager.stopAccelerometerUpdates()
            guard orientation != nil else {print("Orientation Error");return}
            let connection = self.videoOutput.connection(with: AVMediaType.video) 
            if (connection?.isVideoOrientationSupported)! {
                connection?.videoOrientation = orientation!
                self.videoOutput.startRecording(to: outputURL, recordingDelegate: self)
            }
        }
    }


```

**Comment by s4cha** [comment]
@Appswage Your update is on point 👌. This looks like a micro case, but still, nice catch!

I implemented it here with few amends and it works perfectly :
https://github.com/Yummypets/YPImagePicker/commit/bd28c7c068429e90b39f78c4108a38749005063c
This will probably be live later today.

PS: Excuse the delayed response, we won the soccer World Cup so I was away for a while 🇫🇷 🍻 :)

Totally unrelated, I think I saw your profile on the top iOS dev in upwork, congrats!! 👏  Have you used the picker on clients' apps? If so would you be willing to communicate their name in the App Store so we can build a list of Apps that use it ?

Cheers!

**Comment by s4cha** [comment]
This should be ok in 3.4.0 https://github.com/Yummypets/YPImagePicker/releases/tag/3.4.0 :)

**Comment by s4cha** [comment]
Closing this for now, don't hesitate to reopen if needed :)
