### ISSUE TITLE
Save drafts

### ISSUE THREAD

**Issue by shotat** [Yummypets/YPImagePicker#162]
Hi.
Original Instagram app allows user to save drafts with metadata and show them in gallery view.
Do you have any plans for the feature?

**Comment by s4cha** [comment]
@shotat I wouldn't say it's top priority for us but I'm not against it, feel free to take a crack at it :)
@NikKovIos What do you think?

**Comment by NikKovIos** [comment]
@shotat @s4cha  
I think it's a hard implemented not necessary functional and we have a lot of tasks with more priority than this. So maybe in a far future 🙂
And i think it's better to refactor all code first to support better scalability.

**Comment by NikKovIos** [comment]
Too old issue. Feel free to open new.
