### ISSUE TITLE
PHAsset local Identifier addition

### ISSUE THREAD

**Issue by barisozr** [Yummypets/YPImagePicker#168]
Could you add localIdentifier of PHAsset or whole related asset to YPMediaPhoto/YPMediaVideo (if exists on photo library) for reaching later? Or is there anyway to get the local identifier or related asset on current version?

**Comment by NikKovIos** [comment]
Hello! )
Could you please say, why do you need it. We need a reason to add it. )

**Comment by barisozr** [comment]
Hi @NikKovIos 
I have 2 reasons.
* I want to save the photo identifier to reach from photos later. If the photo exists still in the library I don't want to download from the server. In short I need this for reducing data usage.
* I want to check the photo is already added/used in the app. Don't want to compare any other stuffs, just want to check the local identifier is same or not.

Is it enough?

**Comment by s4cha** [comment]
@barisozr, this makes sense indeed ;) 
We will add this to our roadmap and let you know when it's implemented :)

**Comment by rehannali** [comment]
Hi, Is this feature implemented?
If yes, then how can I use this, i.e. property name?

**Comment by s4cha** [comment]
@rehannali you have an `asset: PHAsset?` in YPMediaPhoto from pictures & videos coming from the library. Please be aware that this points to the original image, aka not filtered nor cropped :)

**Comment by s4cha** [comment]
```swift
picker.didFinishPicking { [unowned picker] items, _ in
    //...
    let asset = items.singlePhoto?.asset
    //...
}
```

**Comment by NikKovIos** [comment]
Too old issue. Feel free to open new.
