### ISSUE TITLE
Application is getting crashed when initialise the config file

### ISSUE THREAD

**Issue by MandeepSingh1** [Yummypets/YPImagePicker#171]
Hi Team, am using your library in lots of projects, but today I update the library to latest code from Cocoapods but now whenever I initialise the library with new swift 4.0 code. My application is getting crashed at this line. I don't know why it happens

   config.library.mediaType = .photoAndVideo
        config.library.onlySquare  = false
        config.onlySquareImagesFromCamera = true
        config.targetImageSize = .original
        config.usesFrontCamera = true
        config.showsFilters = true
        config.filters = [YPFilterDescriptor(name: "Normal", filterName: ""),
                          YPFilterDescriptor(name: "Mono", filterName: "CIPhotoEffectMono")]
        config.shouldSaveNewPicturesToAlbum = true
        config.video.compression = AVAssetExportPresetHighestQuality
        config.albumName = "MyGreatAppName"
        config.screens = [.library, .photo, .video]
        config.startOnScreen = .library
        config.video.recordingTimeLimit = 10
        config.video.libraryTimeLimit = 20
        config.showsCrop = .rectangle(ratio: (16/9))
        config.wordings.libraryTitle = "Gallery"
        config.hidesStatusBar = false
//        config.overlayView = myOverlayView
        config.library.maxNumberOfItems = 5
//        config.isScrollToChangeModesEnabled = false
        
        // Build a picker with your configuration
       let picker = YPImagePicker(configuration: config)

Can you please help me out and Xcode don't show me why the application is getting crashed.

**Comment by MandeepSingh1** [comment]
Please help me out asap, because I have to update this and now my application is suffered

**Comment by MandeepSingh1** [comment]
<img width="1404" alt="screen shot 2018-06-23 at 12 49 54 am" src="https://user-images.githubusercontent.com/11526089/41795174-76fa26f6-767f-11e8-98b0-7ed0089046b1.png">

Please check this file, application is getting crashed anywhere when ever I try to open the camera with latest code.

**Comment by MandeepSingh1** [comment]
@NikKovIos , @s4cha  can you help me guys. I need this urgent

**Comment by s4cha** [comment]
@MandeepSingh1 As a quick fix, I'd suggest you downgrade the version to the previously working one :) I'm going to look into it in the meantime.

**Comment by s4cha** [comment]
@MandeepSingh1 I just did `pod repo update` then `pod try YPImagePicker` to get the latest pod (3.2.0). Using your configuration above, it runs fine on both device and simulator on my machine. Could you try the same and see if that works?

**Comment by MandeepSingh1** [comment]
Yes, Actually I also implement in the demo and it works fine in the demo. But When I implement in my Project it crashes. I don't know why it is crashing in my project. Because I have implement in 2 demos and in both of the demos its working fine. But when it comes to my project config variable releasing their memory. And thats why it gives me excess_bad_code.

So now what I do, I need your SDK in my app. How can I fix this issue?

**Comment by s4cha** [comment]
@MandeepSingh1, it's quite hard for me to help without more information. One thing you can try is integrate the library via Carthage and see if that solves your issue. 
Also we just updated a new version (3.3.0) so you could try this one as well.
It really looks like something on your side so it's quite hard to help you debug without having access the the code :)

Hope this helps,

**Comment by MandeepSingh1** [comment]
Thanks @s4cha , I would let you know by update the new version, as new version resolve the issue or not.

**Comment by s4cha** [comment]
@MandeepSingh1 any updates on this?

**Comment by s4cha** [comment]
Actually I had such an issue recently and I had to uninstall the app form the phone/simulator and build again. Strange Xcode thing but it solved it. Hope this helps :)

**Comment by NikKovIos** [comment]
I had the same issue at the line with `processingLabel.text = YPConfig.wordings.processing`. That's the weird bug. I think it's the problem with Xcode/Derived data. After cleaning the project, everything works well. 🧐

**Comment by s4cha** [comment]
@MandeepSingh1 any updates?

**Comment by MandeepSingh1** [comment]
@s4cha, no still the issue is same am not able to understand about this issue. If am using the pod file into the demo its working fine and I didn't face any issue. But am using the pod file into my project. whenever I initiaize the YPImage picker my app is get crashed.

**Comment by MandeepSingh1** [comment]
So for right now, I have go to your code and do the manually changes from my side so that my app can work for current situation.

**Comment by MandeepSingh1** [comment]
But i have clean my project, and still the issue is same, when ever I run the application and configuration file is load. The application is getting crashed at configuration file like above the issue mentioned.

**Comment by s4cha** [comment]
@MandeepSingh1  any news?

**Comment by s4cha** [comment]
Closing for now for lack of activity, feel free to reopen if needed.
