### ISSUE TITLE
Camera multiple selection 

### ISSUE THREAD

**Issue by FarisAlbalawi** [Yummypets/YPImagePicker#172]
How to do multiple selection from Camera ?

**Comment by s4cha** [comment]
@fairs-222 This is not supported at the moment, do you have an idea of how it would look like?

PS: Excuse the delayed response, we won the soccer World Cup so I was away for a while 🇫🇷 🍻 :)

**Comment by s4cha** [comment]
@fairs-222 Thinking about it we are not going to be supporting this use case in the near future. We aim to be an "Instagram picker clone" since they pretty much have the best photo picker around. We will stick to their existing for now :)
