### ISSUE TITLE
Setting up causing problems Picker deinited 👍

### ISSUE THREAD

**Issue by mohsinka** [Yummypets/YPImagePicker#174]
Hi, so I was trying this library of yours and followed the exact process by first installing the dependencies, giving permissions in info.plist, followed by, using the custom configurations or otherwise, by using the default YPImagePicker instance, and whenever I try to instantiate the Camera or Library i get a console print, "Picker deinited 👍" and nothing else happens.. I can't seem to understand why this might be happening hence need your insights on this. Please update as soon as possible. Very grateful for all the help.

LOL I FIXED THIS... SO STUPID OF ME.. Sorry.. Thanks

**Comment by s4cha** [comment]
@mohsinka glad you solved it :)

**Comment by harjeetk** [comment]
How did you solve the issue? @mohsinka

**Comment by Aviru** [comment]
@harjeetk  the solution is 
`present(picker, animated: true, completion: nil)`

**Comment by AdieOlami** [comment]
I am having this issue how do I solve it? my imageview does not show the selected image
