### ISSUE TITLE
Saving Photo/Video data and presenting into new View Controller

### ISSUE THREAD

**Issue by ewjc** [Yummypets/YPImagePicker#175]
Hi there,

I appreciate the one callback function didFinishPicking, but when placed into the view life cycle, it doesn't activate when the save button is pressed(at the end of choosing, cropping, filtering, etc). Instead, it saves the photo to album and that's it. I needed to make an instagram based preview page to add a caption and what not in order to migrate.

Is there any way to do this without an edit to the pod? I had to edit the didSelect function's switch cases. I added a few lines of code, now the function presents the data I need on a new page which is going to allow me to add a post to my database. Also consider using a delegate/protocol for view controller communication.

If you can fix this, I think people may have a use case for this type of thing.

**Comment by 10000TB** [comment]
try

```
picker.pushViewController(...)
```

**Comment by 10000TB** [comment]
try 
```
picker.pushviewcontroller(...)
```

**Comment by s4cha** [comment]
@ewjc The single `didFinishPicking` is something we came up with internally after a long discussion.
There are drawbacks and advantages to both approaches (delegate vs callbacks) and we agreed this was more "swifty", although less common among libraries.

Your use case is perfectly valid. 

If you want to dismiss the picker and present another sheet modally than you can use this :

```swift
    func showPicker() {
        var config = ...
        let picker = YPImagePicker(configuration: config)
        
        picker.didFinishPicking { [unowned picker] items, cancelled in
            
            if cancelled {
                picker.dismiss(animated: true, completion: nil)
                return
            }
            
            let postVC = PostStatusVC()
            if let photo = items.singlePhoto {
                postVC.preloadedImage = photo.image
            } else if let video = items.singleVideo, let videoData = try? Data(contentsOf: video.url) {
                postVC.preloadVideo(with: videoData, thumbnail: video.thumbnail)
            }
            picker.dismiss(animated: true) {
                present(postVC, animated: false, completion: nil)
            }
        }
        present(picker, animated: false, completion: nil)
    }
```

as @10000TB pointed out the picker is itself a UINavigationController so you can push your own views inside it natively.

Essentially replace 
```swift
picker.dismiss(animated: true) {
    present(postVC, animated: false, completion: nil)
}
```
in the above code by:
```swift
let myVC = MYViewController()
picker.pushViewController(myVC, animated: true)
```

Hope this helps :)

PS: Excuse the delayed response, we won the soccer World Cup so I was away for a while 🇫🇷 🍻 :)

**Comment by Clint1994** [comment]
@s4cha Hi mate, I know I am months late. Any reason why I am getting a black screen when trying to present or pushVC?

**Comment by Clint1994** [comment]
@s4cha Any reason why I am presented with two navigation bars when using picker.pushViewController... ? 

I have my navigation bar that includes a share button, and I also have the YPPicker nav bar with the back button included. Anyway I can get the YPPicker nav bar and also include my title and share button?

**Comment by Clint1994** [comment]
@s4cha Do you know how I can access the photo in the next view controller? It is not appearing after I push. Did I have to configure the picker configure? Heres my code


`   let picker = YPImagePicker()
        picker.didFinishPicking { [unowned picker] items, cancelled in
            
            
            if cancelled {
                picker.dismiss(animated: true, completion: nil)
                return
            }
            
            
            if let photo = items.singlePhoto {
                let sharePostVC = SharePhotoViewController()
             
                sharePostVC.selectedImage = photo.modifiedImage ?? photo.image
                
                
            }
            
                let shareVC = self.storyboard?.instantiateViewController(withIdentifier: "SharePhotoController")
                picker.pushViewController(shareVC!, animated: true)


And after I push to the next VC.. 
`
    var selectedImage: UIImage? {
        didSet {
            self.finalPhoto?.image = selectedImage
        }
    }`


Do you see anything wrong? No errors, however no photo appears.
