### ISSUE TITLE
config.video.fileType = .mp4 setting not work

### ISSUE THREAD

**Issue by imzyf** [Yummypets/YPImagePicker#177]
version 3.3.0
iOS 11

set the `config.video.fileType = .mp4`, then record a video, in `didFinishPicking` I print video after the `case .video(let video):` line.

the video file url still end of .mov

any suggest thanks

**Comment by NikKovIos** [comment]
That's a bug.

Please, try to test in branch DifferentHotfixes and tell if it fixed.
To install, write pod 'YPImagePicker', :git => 'https://github.com/Yummypets/YPImagePicker.git', :branch => 'DifferentHotfixes' in your Podfile.

**Comment by s4cha** [comment]
@NikKovIos @imzyf I tried on latest master commit (not released yet) and I do have ".mp4" when setting `config.video.fileType = AVFileType.mp4` 

:)

**Comment by NikKovIos** [comment]
Wow, that's strange..)

**Comment by s4cha** [comment]
@NikKovIos I made I typo! I meant that everything works fine :)

**Comment by s4cha** [comment]
@imzyf does that work now?
