### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by appfrilans** [Yummypets/YPImagePicker#178]
I got a crash in YPPhotoCaptureDefaults.swift on row with

`   sessionQueue.async { [unowned self] in`

I suggest not using unowned but instead weak. Following code work just fine:

```
   func start(with previewView: UIView, completion: @escaping () -> Void) {
        self.previewView = previewView
        sessionQueue.async { [weak self] in
             guard let self = self else {
                 return
             }
```

**Comment by s4cha** [comment]
This should be ok in 3.4.0 https://github.com/Yummypets/YPImagePicker/releases/tag/3.4.0
thanks to your PR :) Thanks a ton for your help on this, much appreciated !

**Comment by s4cha** [comment]
Closing this for now, feel free to reopen if the crash comes back :)
