### ISSUE TITLE
File name of a single image or captured photo in the picker 

### ISSUE THREAD

**Issue by thewozz** [Yummypets/YPImagePicker#179]
How can I get the filename or the path of the selected image in the picker.didFinishPicking method ?

**Comment by s4cha** [comment]
@thewozz 
At the moment there's no way to get the filename/path but this is something we are going to tackle in the next version 🚀 

This is related to https://github.com/Yummypets/YPImagePicker/issues/168
PS: Please excuse the late reply :)

**Comment by gintechsystems** [comment]
+1

**Comment by programever** [comment]
I am not sure if it can help, but i can get the file path using below code:
`photo.asset?.requestContentEditingInput(with: PHContentEditingInputRequestOptions()) { (input, _) in
    print(input!.fullSizeImageURL!)
}`
Please note this is async task.

**Comment by NikKovIos** [comment]
Too old issue. Feel free to open new.
