### ISSUE TITLE
Camara preview black first time startup when config.startOnScreen = .photo

### ISSUE THREAD

**Issue by iantfang** [Yummypets/YPImagePicker#18]
User has to swipe to library view and back to camera view to start capture photo. This issue happens on first time YPImagePicker is shown after the app starts running. Sometimes the app freezes on photo capture view for 5 seconds.

Issue also exists in the example app.

**Comment by s4cha** [comment]
@Tinyik Thanks for spotting that out ! I'm looking into it at the moment and will let you know :)

**Comment by s4cha** [comment]
@Tinyik This should be fixed in the latest version 2.4.2 
https://github.com/Yummypets/YPImagePicker/releases/tag/2.4.2

Have a great day :)

**Comment by iantfang** [comment]
@s4cha Thank you! Congrats on the amazing framework.

**Comment by iantfang** [comment]
Hello, there are still issues when config.startOnScreen = .photo.
1. After snapping the photo, if user swipe back from the filterVC to the cameraVC, the cameraCapture layer is stuck at the previous photo instead of showing live preview.
2. If now click on "Cancel" and enter the ImagePicker again, the entire ImagePicker freezes.
3. To preventing freezing as described in 2., user needs to manually swipe to library view and back to cameraVC before clicking "Cancel"

**Comment by s4cha** [comment]
@Tinyik Good news is the slow startup should be fixed in the latest version.
Concerning the preview stuck when coming back from the filters I can reproduce on my side so I'll try to fix it when I have some time, if you want to have a look in the meantime, don't hesitate :)

**Comment by s4cha** [comment]
I can't reproduce (3) with the latest version so might be fixed as well :)

**Comment by s4cha** [comment]
@Tinyik I just fixed the freeze issue so it'll be good in the next version (later today) :)

**Comment by s4cha** [comment]
@Tinyik it is now live in 
https://github.com/Yummypets/YPImagePicker/releases/tag/2.6.1
Hope that fixes all your issues :)

Cheers,

**Comment by s4cha** [comment]
@Tinyik any updates?

**Comment by iantfang** [comment]
@s4cha Hi! Sorry for the late reply, and I was busy with school in past two weeks. I’ll get back to you as soon as I tested it out. They you so much for your support and dedication in this open source project! I genuinely appreciate it.

**Comment by s4cha** [comment]
@Tinyik no problem, no rush, I just wanted to know you were still alive 🙃 
Thanks for the kind words :)

**Comment by iantfang** [comment]
@s4cha Hahaha. In that case, rest assured

**Comment by iantfang** [comment]
@s4cha Can confirm the latest version resolves the issues mentioned above and it works as charm. Pleas keep on the great work! I'm now closing the issue.
