### ISSUE TITLE
Custom back button

### ISSUE THREAD

**Issue by johsem** [Yummypets/YPImagePicker#184]
Is there a way to set a custom UIBarButtonItem (or at least an image) to YPPickerVC?

**Comment by NikKovIos** [comment]
Yes, use extension for this class, that overrides viewWillAppear method.

**Comment by s4cha** [comment]
I don't think you can override such a method in an extension :/ 
My best bet would be to fork the project until we have such an api :)

**Comment by NikKovIos** [comment]
Here is the code, i use in my proj to override the back button:

```swift
extension YPPhotoFiltersVC {
    override open func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
      if let controllersCount = navigationController?.viewControllers.count, controllersCount > 1 {
                let backButton = UIButton(frame: CGRect(x: 0, y: 0, width: 20, height: 40))
                backButton.setImage(UIImage(named: "arrow_left"), for: .normal)
                backButton.setImage(UIImage(named: "arrow_left_orange"), for: .highlighted)
                backButton.contentMode = .left
                let backButtonItem = UIBarButtonItem(customView: backButton)
                backButton.addTarget(self, action: #selector(popCurrentViewController), for: .touchUpInside)
                navigationItem.leftBarButtonItem = backButtonItem
            }
    }
}
```

I didn't try with YPPickerVC thus, so you're right here. But maybe that code would helps;)

**Comment by s4cha** [comment]
Alright that would work but in this case 'viewWillAppear' has already been overridden in `YPPickerVC`
so not modifiable form an extension anymore @johsem any updates?
<img width="709" alt="screen shot 2018-07-24 at 10 46 39" src="https://user-images.githubusercontent.com/1812953/43127090-e318b682-8f2e-11e8-928f-3adebca7aeb9.png">

**Comment by NikKovIos** [comment]
I think it should be an option in lib for that too. And it implemented at half part (if i remember well)

**Comment by NikKovIos** [comment]
Too old issue. Feel free to open new.
