### ISSUE TITLE
GIF support

### ISSUE THREAD

**Issue by sharad-paghadal** [Yummypets/YPImagePicker#185]
Please add support to show GIF in pickerview and select them.

**Comment by NikKovIos** [comment]
Hello) 
You can add it, try in new branch and upload a PR;)

**Comment by s4cha** [comment]
@sharad-paghadal Indeed, we're trying to get as close a Instagram's functionalities as possible and they don't support GiF neither so this is not on our roadmap at the moment. Feel free to contribute :)

**Comment by NikKovIos** [comment]
Here is a nice code to take from https://github.com/swiftgif/SwiftGif/blob/master/SwiftGifCommon/UIImage%2BGif.swift

**Comment by nastasiupta** [comment]
@NikKovIos @s4cha guys can we reconsider this option :)) ?

**Comment by NikKovIos** [comment]
@nastasiupta i don't think so, sorry)
But you can try to make a MR and we would watch it.
