### ISSUE TITLE
Bug: Attempted to read an unowned reference but the object was already deallocated

### ISSUE THREAD

**Issue by imbaggaarm** [Yummypets/YPImagePicker#189]
Hi, I recently use YPImagePicker, and it's great, but I saw a bug with simulator here. I got a crash with error: 
Fatal error: Attempted to read an unowned reference but the object was already deallocated2018-07-22 Fatal error: Attempted to read an unowned reference but the object was already deallocated

Fix:
In file YPPhotoCaptureDefaults.swift, method start(with previewView: UIView, completion: @escaping () -> Void), change the [unowned self] -> [weak self] will fix this bug.

**Comment by NikKovIos** [comment]
Could you please test and create a PR? Big thanks for that! =)

**Comment by s4cha** [comment]
Hi @imbaggaarm, thanks for taking the time to report the issue! Actually this has been fixed in the latest version (3.4.0) https://github.com/Yummypets/YPImagePicker/releases/tag/3.4.0
Cheers :)

**Comment by s4cha** [comment]
Closing this for now, feel free to reopen if needed :)
