### ISSUE TITLE
pod crash for the first use video

### ISSUE THREAD

**Issue by bcalmeil** [Yummypets/YPImagePicker#190]
**Describe the bug**
I am using the last updated vesion for swift4. I notice that the first time the user, use the video to record, an authorisation pop up appear to require the autorisation of the use of microphone. This crash the apps after autorisation
At the second use no issue.

**To Reproduce**
First use of the apps form user
Open Galerie, camera (autorisation to access to gallerie & camera) 
3. Click on video recod
pop up for authorisation to use microphone
launch video => no video is recording and we switch to trim screen
Apps crash
line 135 - YPVideoFiltersVc
 DispatchQueue.main.async {
                    let resultVideo = YPMediaVideo(thumbnail: strongSelf.coverImageView.image!,
Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value

Many thanks 

Benoit

**Comment by NikKovIos** [comment]
Do you approve the authorization to use the mic? I can't reproduce it..

**Comment by bcalmeil** [comment]
I do approve.
This is my configuration:
Swift4 - last pop released

After the autorisation, i guess the camera dont have enough time to launch and record a blank

please find the catch screen
![img_8048](https://user-images.githubusercontent.com/29054379/43231476-2074e7b4-909f-11e8-9e96-87a96361cde9.PNG)
![img_8045](https://user-images.githubusercontent.com/29054379/43231477-20a17068-909f-11e8-9d2d-06bb68cb0cef.PNG)
![screen shot 2018-07-26 at 6 40 44 am](https://user-images.githubusercontent.com/29054379/43231500-33e5d768-909f-11e8-80dd-3a2f3e068d93.png)

**Comment by NikKovIos** [comment]
Please, try to test in branch DifferentHotfixes and tell if it fixed.  
To install, write `pod 'YPImagePicker', :git => 'https://github.com/Yummypets/YPImagePicker.git', :branch => 'DifferentHotfixes'` in your Podfile.

**Comment by bcalmeil** [comment]
hello

I have tested your branch but the pod totally crash now.

YPFilterDescriptor is not recognised anymore in my project and when I remove my customise filter and launch the project

When I take a picture from the camera I have a 
Thread 1: signal SIGABRT 
ligne 66                 self.v.collectionView.selectItem(at: IndexPath(row: 0, section: 0),

YPPhotoFiltersVC.swift

Benoit

**Comment by NikKovIos** [comment]
Use YPFilter now instead of YPFilterDescriptor.

Please provide step to step to reproduce, unfortunately i can't find a bug.

**Comment by bcalmeil** [comment]
Hello

I have made the update accordingly, 

YPFilter I have an error :

Argument labels '(name:, filterName:)' do not match any available overloads



This is my swift file for the video and picture (just before the crash) -  :



This is the video of the step by step

Still same error
YPVideoFiltersVC
L136                DispatchQueue.main.async {
                    let resultVideo = YPMediaVideo(thumbnail: strongSelf.coverImageView.image!,
                                              videoURL: destinationURL)
                    didSave(YPMediaItem.video(v: resultVideo))
                    strongSelf.setupRightBarButtonItem()
                }

Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value

**Comment by bcalmeil** [comment]
Sorry I forgot 
If I wait the initialisation or the video or if I do record -> camera-> record the phone show a picture and not a black screen I can record without issue 

I guess there is an issue if the camera is not finished to be initialised by the phone we record a blank and crash the app 


I phone SE
IOS 11.4

Benoit

Benoit CALMEIL 

20B
Lexington Hill
11 Rock Hill Street
Kennedy Town
Hong Kong

**Comment by bcalmeil** [comment]
Hi Nick

I ahem. Quick question, I try to select two picture and get the information like

if let firstItem = items.first {
 switch firstItem {
            case .photo(let photo):
            let scaledImage1 = photo.image ….

}

if let firstItem = items.last {
            switch firstItem {
            case .photo(let photo):
                let scaledImage2 = photo.image.>>
}

But the scaledImage 1 and 2 return the two values

What is the perfect code for multi selection, I can t find this information on line

Many thanks

Benoit


Benoit Calmeil

- - -
20 B
Lexington Hill
11 rock Hill Street

**Comment by bcalmeil** [comment]
Hi Nick

Sorry to have bother you with that

I loop in the items and it s all good.

Have a great day

Benoit


Benoit Calmeil

- - -
20 B
Lexington Hill
11 rock Hill Street

**Comment by s4cha** [comment]
@bcalmeil is that fixed now or are your still experiencing the issue?

**Comment by s4cha** [comment]
Closing this for now, feel free to reopen if need be :)

**Comment by bcalmeil** [comment]
Hello

Thanks sure.




Benoit Calmeil

- - -
20 B
Lexington Hill
11 Rock hill Street 
Kennedy Town
