### ISSUE TITLE
Multiple selections are cleared when albums changed.

### ISSUE THREAD

**Issue by shotat** [Yummypets/YPImagePicker#193]
**Describe the bug**

- Multiple selections are cleared when asset collections switched.

**To Reproduce**
1. Go to Gallery（Library）
2. Click on multiple selections button
3. Click on the title view ( `Gallery` )
4. Click any cells (e.g. `Camera Roll`) and switch albums.
5. Multiple selections are cleared.

**Expected behavior**
Selections should remain unchanged.

**Environment (please complete the following information):**
 - Xcode Version 9.3.1
 - Swift Version 4.1

**Installation Type**
 - Manual

**Additional context**

**Comment by s4cha** [comment]
@shotat Nice catch 👍 
Actually it was done on purpose at the time.
Having the selection remain across folders is harder to implement but it's definitely something we want to support in future releases.
