### ISSUE TITLE
Do you know why my bottom buttons ( Cancel / Save ) are black and not white ?

### ISSUE THREAD

**Issue by ljs19923** [Yummypets/YPImagePicker#194]
Do you know why my bottom buttons ( Cancel / Save ) are black and not white ? 

![image](https://user-images.githubusercontent.com/5727223/43365325-90172954-932b-11e8-8574-d8a728924bef.png)

**Comment by NikKovIos** [comment]
Check the appearance methods in your app

**Comment by s4cha** [comment]
Indeed the code explicitly sets them to white `cancelButton.tintColor = .white` so there might be something like `UIBarButtonItem.appearance().tintColor = .black` somewhere in your code?

**Comment by ljs19923** [comment]
No...so its why i dont understand. its really weird :/

**Comment by NikKovIos** [comment]
Try to debug your view hierarchy. Maybe there is something, that overlaying these buttons.

**Comment by ljs19923** [comment]
So if i add UIBarButtonItem.appearance().tintColor = .white before present YImagePickerVC, that will works ? Because that dont works :/

**Comment by ljs19923** [comment]
UIBarButtonItem.appearance().setTitleTextAttributes([NSAttributedStringKey.font: Brain.kItemNavBarFont, NSAttributedStringKey.foregroundColor:UIColor.white], for:.normal)


Thats works but now i dont see cancel / next buttons in the top nav bar in the previous VC because they are white....

Because yes in My app im my launching method i have  

UIBarButtonItem.appearance().setTitleTextAttributes([NSAttributedStringKey.font: Brain.kItemNavBarFont, NSAttributedStringKey.foregroundColor:UIColor.black], for:.normal)

And i cant remove it. So i need to find a solution with that

![image](https://user-images.githubusercontent.com/5727223/43578824-4d0f2472-9650-11e8-941e-fbe61ec3f51c.png)

**Comment by NikKovIos** [comment]
That most likely on your side. However, u can send a test project, that we can search for a solution or a bug. Also be sure, that u use the last release from master branch.

**Comment by gali8** [comment]
Hi, this is the right solution, using appearance. Note that Theme.....Color is just a kind of structs into my app.

`        let navBarImagePicker = UINavigationBar.appearance(whenContainedInInstancesOf: [YPImagePicker.self])
        navBarImagePicker.isTranslucent = Theme.ImagePicker.NavigationBar.isTranslucent
        navBarImagePicker.tintColor = Theme.ImagePicker.NavigationBar.tintColor
        navBarImagePicker.barTintColor = Theme.ImagePicker.NavigationBar.barColor
        navBarImagePicker.titleTextAttributes = [NSAttributedString.Key.foregroundColor: Theme.ImagePicker.NavigationBar.titleColor, NSAttributedString.Key.font : Theme.ImagePicker.NavigationBar.titleFont]`
        
`         let barBtnImagePicker = UIBarButtonItem.appearance(whenContainedInInstancesOf: [YPImagePicker.self])
        barBtnImagePicker.setTitleTextAttributes([NSAttributedString.Key.foregroundColor: Theme.ImagePicker.BarButtonItem.tintColor, NSAttributedString.Key.font : Theme.ImagePicker.BarButtonItem.titleFont], for: UIControl.State.normal)
        barBtnImagePicker.setTitleTextAttributes([NSAttributedString.Key.foregroundColor: Theme.ImagePicker.BarButtonItem.tintColor, NSAttributedString.Key.font : Theme.ImagePicker.BarButtonItem.titleFont], for: UIControl.State.highlighted)`

**Comment by NikKovIos** [comment]
Too old issue. Feel free to open new.
