### ISSUE TITLE
Squared Video Recording

### ISSUE THREAD

**Issue by DariusDresp** [Yummypets/YPImagePicker#195]
While the video is recording it looks like its going to be squared. However the video recording isnt actually squared (recorded video at trimming isnt squared although I expected that). Is it possible to force video recordings to be squared and how do I set that up?

**Comment by s4cha** [comment]
@DariusDresp This is a very good point, we actually discussed something similar here: https://github.com/Yummypets/YPImagePicker/issues/137
It is not possible at the moment but recording squared videos is something we're looking at :)
