### ISSUE TITLE
Feature - Customize Pager

### ISSUE THREAD

**Issue by gintechsystems** [Yummypets/YPImagePicker#197]
Hello everyone! Great project, works well and saved me a lot of development time. I was curious if there is a way to customize the background and bottom button colors (background, title color)? I know you can do an appearance for the app & we can change the navigation styles, but wanted to customize per just the pager. If there is a way, excuse me. I was looking at the code but only saw overlayView, which doesn't sound to be the same thing. I can provide more detail if needed. I would be willing to contribute and help implement this feature too if needed :)

Let me know your thoughts!

Thanks
Joe

**Comment by rheligonwbi** [comment]
Hello, i did it easily on YPMenuItem.swift
Just change your colors on  functions: selectedColor() and unselectedColor()

**Comment by gintechsystems** [comment]
@rheligonwbi I haven't checked but aren't those functions private right now? Meaning, we can't just do .config.menu.color for example? We just need to implement easier way.

**Comment by s4cha** [comment]
Hi @gintechsystems Glad you like the project!
I think you could add properties in `YPColor` so the usage would follow the previous customisations via `config.color.[something]`
https://github.com/Yummypets/YPImagePicker/blob/master/Source/Configuration/YPColors.swift
Contributions are always welcome and encouraged of course :)
You can submit a Pull request, don't worry if it's not perfect, we'll refine the api on the pull request and the core team will help you out if needed :)

**Comment by s4cha** [comment]
This is similar to https://github.com/Yummypets/YPImagePicker/issues/203

**Comment by s4cha** [comment]
In the latest version you should be able to use `config.bottomMenuItemSelectedColour` & `bottomMenuItemUnSelectedColour` for the foreground colours. the background is not yet supported though

**Comment by gintechsystems** [comment]
Yeah, the background is what I am asking about. I don't think I had the latest version at the time bottomMenuItem was part of the config. Will take a look at that.

Thank you!

**Comment by NikKovIos** [comment]
Too old issue. Feel free to open new.
