### ISSUE TITLE
Issues with video grabbed by screen recorder having no audio

### ISSUE THREAD

**Issue by ravinagar79** [Yummypets/YPImagePicker#199]
App is not not responding if I am using video grabbed by screen recorder having no audio. I am getting below error:
PHCachingImageManager >>> Problems with audio track

Please check issue on attached video

Please download 
[ScreenRecording_08-06-2018 09-27-49.MP4.zip](https://github.com/Yummypets/YPImagePicker/files/2273416/ScreenRecording_08-06-2018.09-27-49.MP4.zip)

**Comment by yokochi** [comment]
I have same problem(ver 3.4.0). but it was fixed with this [commit](https://github.com/Yummypets/YPImagePicker/commit/a6e847cfb822706c49fecf3c831814446b4e0fa2).
That version is not tagged yet. try use master branch.

**Comment by s4cha** [comment]
@ravinagar79 & @yokochi 
This is indeed fixed as of 3.4.1 & 3.5.0(xcode10) :)

**Comment by Berk-Kaya** [comment]
It still happens in 4.0
