### ISSUE TITLE
Navigating with 'Next' and 'Done' buttons

### ISSUE THREAD

**Issue by cwestMobile** [Yummypets/YPImagePicker#20]
Apologies beforehand as this is probably a dumb question with a simple solution.

Can you point me in the right direction for getting the selected photo and navigating to another VC by clicking on the 'Next' or 'Done' button? The best case scenario is the transition looks the same as the transition from initial image picker to the filter page.

I would also want the image to carry over to the other VC.

Thanks for any information you may have.

**Comment by cwestMobile** [comment]
+Reminder

**Comment by cwestMobile** [comment]
Any ideas?

**Comment by s4cha** [comment]
Sure @cwestMobile 

YPImagePicker is a plain `UINavigationController` so you can push whatever view  controller you want into it :

```swift
let myVc = UIViewController()
myVc.view.backgroundColor = .red
        
picker.didSelectImage = { [unowned picker] img in
    picker.pushViewController(myVc, animated: true)
}
```

Please excuse the late reply ;)

**Comment by cwestMobile** [comment]
Thanks for the response. I will try this out tonight and close out if it works.

**Comment by s4cha** [comment]
@cwestMobile awesome :)

**Comment by cwestMobile** [comment]
So I'm not quite getting what I was hoping. I have attached a video showing the issue. First issue being the lag when changing views as seen in the video. The second being it is just showing a black screen when it is pointing to a view with many items. Any help is appreciated. 

https://vimeo.com/254616670

**Comment by s4cha** [comment]
@cwestMobile The scenario in the video usually happens if the `backgroundColor` of the view controller is clear. Have you tried setting the view controller's `vc.view.backgroundColor = .white` ?
Hope it helps :)

**Comment by cwestMobile** [comment]
So got everything working, and have one final question in regards to navigation. If a user clicks 'Cancel' on the initial view controller, it just dismissing..how would i go about navigating somewhere else when that button is clicked. Basically just need to find the method called when that is clicked.

**Comment by cwestMobile** [comment]
Thanks for your help :)
