### ISSUE TITLE
objective c related problem

### ISSUE THREAD

**Issue by hirenkapoor** [Yummypets/YPImagePicker#201]
How can i use this lib in my objective c project , i had stuff in this issue. can u show me step for use this lib to obj c project ?

**Comment by s4cha** [comment]
Hi @hirenkapoor as mentioned in the Readme, Obj-C is not supported and it is not in our Roadmap :)
If you really wan to use it in Obj-C, I think you could fork the project and replace all structs by classes.
Hope this helps :)
