### ISSUE TITLE
Video Recording is not working, after pressing back button

### ISSUE THREAD

**Issue by MandeepSingh1** [Yummypets/YPImagePicker#202]
**Describe the bug**
If you record Video, and then come back again your video sessions is not started again and also if you click on button to start the video, it will crash the application.
**To Reproduce**
1. Record the video and go to next screen
2. Click on back button to record the video again
3. Now your session is not working, If you click on record the video app crashes

**Environment (please complete the following information):**
 - Device: [ iPhoneX]
 - OS: [ iOS 11.4.1]
 - Xcode Version [ 9.4.1]
 - Swift Version [ 4.1]

**Comment by MandeepSingh1** [comment]
@NikKovIos @s4cha Guys have you find that issue, which is currently creating a huge issue in my app.

**Comment by gintechsystems** [comment]
@MandeepSingh1  I tried to reproduce this issue with your exact specs, but I am not seeing it. Can you post some code, maybe your config?

**Comment by MandeepSingh1** [comment]
@gintechsystems , Hello Sir actually my application is getting crashed at YPImagePickerConfiguration. So am not able to set their configurations. So I have done some changes in their config file. You can refer to this issue #171 . You can see this issue which I have added from last 30 days and still the issue remains same and the team is not helping me out.

**Comment by hellocqlsys** [comment]
my app is crashed randomly on video cam

**Comment by gintechsystems** [comment]
@MandeepSingh1 so are you using the pod or manually adding it to your project? I would assume there is a intermittent bug going on since only certain people can reproduce.

**Comment by hellocqlsys** [comment]
@MandeepSingh1 hey bro, when I go from camera to video immediately app crashes, but when I go from camera to library & library to video then its working fine, it seems that there is session problem

**Comment by s4cha** [comment]
@MandeepSingh1 Please excuse the late reply, the project got a lot of users recently and we are working hard to try and solve the issues :)
What is the version of the pod are you using?  This has been fixed some time ago if I remember well.

**Comment by HSIOSDevelopment** [comment]
> **Describe the bug**
> If you record Video, and then come back again your video sessions is not started again and also if you click on button to start the video, it will crash the application.
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Record the video and go to next screen
> 2. Click on back button to record the video again
> 3. Now your session is not working, If you click on record the video app crashes
> 
> **Environment (please complete the following information):**
> 
> * Device: [ iPhoneX]
> * OS: [ iOS 11.4.1]
> * Xcode Version [ 9.4.1]
> * Swift Version [ 4.1]

@MandeepSingh1 need to restart camera session when picker will reappear (back from videofilterVC).
So need to update the viewcontroller mode. In YPPickerVC class call the func updateMode(with vc: UIViewController) in viewWillAppear.

**Comment by NikKovIos** [comment]
Too old issue. Feel free to open new.
