### ISSUE TITLE
Change TabBar and its BarButtonItems colors.

### ISSUE THREAD

**Issue by MehdiBrandoMahdloo** [Yummypets/YPImagePicker#203]
Might be very useful to be able to change the TabBar and all its BarButtonColors, to make the Picker in line with the app overall style.

Thank you 🤗

**Comment by rheligonwbi** [comment]
Hello, i did it easily on YPMenuItem.swift
Just change your colors on functions: selectedColor() and unselectedColor()
The workaround on top is for versions previous to what i will explain next.

If you update to version 3.4.1, you can use a config property now for this: 
> config.bottomMenuItemSelectedColour
config.bottomMenuItemUnSelectedColour

**Comment by s4cha** [comment]
The `colors` struct in the config file now enables you to customize the colours :)
