### ISSUE TITLE
Cannot use videos without audio track

### ISSUE THREAD

**Issue by portellaa** [Yummypets/YPImagePicker#207]
**Describe the bug**
Videos without audio track fails to import with console error.
⚠️ PHCachingImageManager >>> Problems with audio track

The screen gets stuck with the loading indicator and that's it.

**To Reproduce**
1. Get a video without audio track. I recorded one in slow motion with an android phone and sent the video to my device
2. Select that video and tap the confirm action

**Expected behavior**
Depending on the configuration, it should move to the next screen or deliver the selected item through the `didFinishPicking` closure

**Environment (please complete the following information):**
 - Device: iPhone6
 - OS: 11.3.
 - Xcode Version: 
 - Swift Version: 4.1

**Installation Type**
 - Cocoapods

**Comment by jeremysua** [comment]
I am having the same issue. Any update on this problem?

**Comment by jeremysua** [comment]
I am having the same issue. Any update on this problem ?

**Comment by Out1and3r** [comment]
Another way to reproduce is to use time lapse video from the library.

**Comment by NikKovIos** [comment]
This is fixed in master branch, but didn't released yet ;)

**Comment by portellaa** [comment]
great 🎉
