### ISSUE TITLE
Support for orientation change

### ISSUE THREAD

**Issue by Sieniek** [Yummypets/YPImagePicker#209]
**Is your feature request related to a problem? Please describe.**
Once YPImagePicker view controller is opened and orientation i.e from portrait to landscape is changed the layout doesn't resize and it looks like attached screenshot.

**Describe the solution you'd like**
It would be perfect to have autolayout that adjust layout to current orientation.
Minimal working solution is to lock orientation in specific view controllers to avoid showing glitched view to end user.

**Describe alternatives you've considered**
Since YPImagePicker is presented on Navigation View controller I cannot change orientation without messing with YPImagePicker library code.
Since YPImagePicker class is "public", not a "open" class it cannot be subclassed.

**Additional context**
![iphonecamera](https://user-images.githubusercontent.com/7023484/44512167-f5ee5d00-a6b9-11e8-8517-75f92232797e.png)
![iphonelibrary](https://user-images.githubusercontent.com/7023484/44512168-f5ee5d00-a6b9-11e8-81ca-c7f5b9692f88.png)
![ipadcamera](https://user-images.githubusercontent.com/7023484/44512205-0ef70e00-a6ba-11e8-92a1-5c8aa7afcab8.png)
![ipadlibrary](https://user-images.githubusercontent.com/7023484/44512206-0ef70e00-a6ba-11e8-802e-e02e04de0b81.png)

**Comment by Skyb0rg** [comment]
+1
When i open the Library (landscape mode), i can see the Camera Screen on the right.
how to stay in portrait mode?

**Comment by s4cha** [comment]
Hi @Sieniek, @Skyb0rg , the landscape orientation has never been supported so it's "normal" that this fails 😄 .
This is something that we might support in the future but in the meantime you'll have to force portrait orientation when showing the picker :)

**Comment by Skyb0rg** [comment]
OK thank you.
I will try this answer:
https://stackoverflow.com/questions/28938660/how-to-lock-orientation-of-one-view-controller-to-portrait-mode-only-in-swift

Or do you have a guide / hint for us?

Thanks

**Comment by SaidAlSouti** [comment]
How to lock the picker in portrait mode?

**Comment by schveiguy** [comment]
So this is fine, you are free not to support it. However, if you do not want to support landscape, the view controller should tell the os. I fixed my instance by adding the following function to YPImagePicker.swift:

```swift
    open override var supportedInterfaceOrientations: UIInterfaceOrientationMask {
        return .portrait
    }
```

Without this, the above horrible "half-visible" orientation is what happens.

**Comment by NikKovIos** [comment]
Too old issue. Feel free to open new.
