### ISSUE TITLE
Video either muted or not automatically played  

### ISSUE THREAD

**Issue by jayjac** [Yummypets/YPImagePicker#211]
Hi, 
first of all thanks for your amazing library guys.
I just have one question for you. 
When one opens the video library, for example with the following YPImagePickerConfiguration :
```swift
config.library.mediaType = .video 
config.screens = [.library]
```
 the first video selected in the library is automatically played with sound. 
My question is : is there a config option to change that default behaviour to either playing the video muted or just not playing the video at all upon selection ?

Thanks for your time and assistance.

**Comment by edbeecroft** [comment]
+1. Interested in hearing about this too. The automatic playback is something I'd like to disable if possible.

**Comment by gintechsystems** [comment]
Don't think there is an option, I +1 on implementing this too.

**Comment by prashanththota09** [comment]
Currently i am facing with the same issue. Is this feature implemented or yet to be implemented ?

**Comment by NikKovIos** [comment]
Too old issue. Feel free to open new.
