### ISSUE TITLE
Old videos received by Airdrop are not showing at the top

### ISSUE THREAD

**Issue by Didar1994** [Yummypets/YPImagePicker#212]
Hi!

I tried to send a video that was taken 1 year ago by Airdrop to my iPhone. Video is showing in the library, but not at the top, like the Photos App or Instagram do. It is showing at the end of the list. I tried to change PHAsset fetch option from "creationDate" key to "modificationDate", but this not helped. I tried to remove fetch options, but the list appears is in ascending order, but I need in descending order.

Any suggestions?

Thank you in advance!

**Comment by NikKovIos** [comment]
Too old issue. Feel free to open new.
