### ISSUE TITLE
Rotation on cropped image not working 

### ISSUE THREAD

**Issue by sulaimankhan7** [Yummypets/YPImagePicker#215]
**Description*
After zooming a image , it crops the image as expected. But if i rotate the image after zoom , view shows the rotated image but don't crop the image as rotated. Crop the image but show in original rotation . 

**To Reproduce**
1. Go to photo selection 
2. Zoom the image for crop 
3. Rotate it 
4. Now save it
It crops image correctly but in it's original zero degree rotation , 

**Expected behavior**
Image should be cropped on my defined rotation

**Environment**
 - Device: Emulator iPhone 8 plus, real device iPhone 6 plus
 - OS:  11.4.1
 - Xcode Version: 9.4.1
 - Swift Version : 4.1

**Installation Type**
1. Cocoapods

Configuration code 
```
        config.library.mediaType = .photo
        config.library.onlySquare  = true
        config.onlySquareImagesFromCamera = true
        config.library.skipSelectionsGallery = true
        config.targetImageSize = .original
        config.usesFrontCamera = true
        config.showsFilters = false
        config.isScrollToChangeModesEnabled = false
        config.shouldSaveNewPicturesToAlbum = true
        config.albumName = "MyGreatAppName"
        config.screens = [.library]
        config.startOnScreen = .library
        //config.showsCrop = .rectangle(ratio: (16/9))
        config.wordings.libraryTitle = ""
        config.library.multipleSelection = true
        
        config.hidesStatusBar = false
        config.library.maxNumberOfItems = maxPhotoCount
        config.library.minNumberOfItems = 1

```

**Comment by s4cha** [comment]
@sulaimansust Thanks for reporting an issue, When you are in the photo library, I don't understand how you can "rotate" the picture as rotation is not supported in the picker. Could you elaborate? or better yet take a video screenshot of your actions ?

Cheers,

**Comment by sulaimankhan7** [comment]
Sorry . This was not your fault. I was given your library after some modification. To fulfill our client's requirement, i had to  modify your library and added some feature on your library. Sorry for the disturbance

**Comment by s4cha** [comment]
@sulaimansust no problem :)

**Comment by petritz** [comment]
@sulaimansust could you share how you added the rotation functionality?

**Comment by yehezkiel17** [comment]
Is this the rotating image feature already deployed? If already deployed, which the version?
