### ISSUE TITLE
Next button not working in Video Crop

### ISSUE THREAD

**Issue by utgodmode** [Yummypets/YPImagePicker#217]
When User tries to tap on next button in Video Crop View, the app doesn't do anything. There is no action. The app does not crash either, it just denies the action to go next step to save the video.

**To Reproduce**
1. Select the Video from Library
2. Tap Next
3. In Crop View, tap next

 - Device: iPhone X
 - OS: 11
 - Xcode Version 10 GM
 - Swift Version - 4.1

Using Cocoapods

Any Idea how I can resolve this issue ?

**Comment by s4cha** [comment]
@utgodmode I can't test right now but a new Cocoapods update was just uploaded based on yesterday's release 3.4.1 which probably fixes this issue, could you update the pod and see if the issue persists?

**Comment by s4cha** [comment]
@utgodmode any updates on this ?

**Comment by utgodmode** [comment]
@s4cha I wanted to use it for video but since the crop function and filters are not available, am just not using the library for video. This bug is still unsolved.

**Comment by s4cha** [comment]
@utgodmode Can you try with the latest 4.2.0 release and let me know how this goes ? Thanks in advance !

**Comment by NikKovIos** [comment]
Too old issue. Feel free to open new.
