### ISSUE TITLE
AVAssetExportPresetHEVCHighestQuality not supported

### ISSUE THREAD

**Issue by blurtime** [Yummypets/YPImagePicker#218]
When setting `config.video.compression = AVAssetExportPresetHEVCHighestQuality` and tapping "Next" to select and possibly trim the video nothing happens. 

Adding `@available(iOS 11.0, *)` before every struct in `YPImagePickerConfiguration.swift` would enable only iOS 11+ users to use the picker and render it useless to others.

**Comment by s4cha** [comment]
@blurtime Thanks for taking the time to open an issue,

How were you able to compile using `AVAssetExportPresetHEVCHighestQuality` (iOS 11 only)?
I'm not sure I fully understand your second point, could you elaborate?

Have you tried the following code? 
```swift
if #available(iOS 11.0, *) {
    config.video.compression = AVAssetExportPresetHEVCHighestQuality
} else {
    // Fallback on earlier versions
    config.video.compression = AVAssetExportPresetHighestQuality
}
```
Cheers,

**Comment by blurtime** [comment]
@s4cha Sorry for answering so late, Swift 4.2 conversion had me occupied... 

Now (Swift 4.2 and iOS 12) I get an error when I use the code you suggested: 

In `LibraryMediaManager.swift (line 136)`, it says: `Fatal error: Unexpectedly found nil while unwrapping an Optional value`, namely the export session (`self.currentExportSessions.append(exportSession!`) which is set earlier (`line 119: let exportSession = AVAssetExportSession(asset: assetComposition, presetName: YPConfig.video.compression)`) using the export preset. Why isn't it working with the export preset `AVAssetExportPresetHEVCHighestQuality`? 

EDIT: I apologize for not checking last time if this reply was well-formatted. I fixed it with this edit.

Some informations about the device I've been testing the picker on: I am using an iPhone 6. According to [this link](https://support.apple.com/en-us/HT207022) there shouldn't be any problems, as the videos I tested the picker with definitely were "no greater than 1080p/240 fps". 

In addition to that, I was wondering whether there was an option to hide the tab or screen bar at the bottom of the screen if there was only one screen, e.g. only library (`config.screens = [.library]`).

**Comment by s4cha** [comment]
@blurtime No worries Swift 4.2 got us all busy :)
Well this is weird :/ Since it's pretty hard for us to fix without reproducing the issue, could you please create an example project to reproduce your issue? That would help use tremendously 🙏  :)
Concerning your last point this is a very good idea and actually already being discussed here : https://github.com/Yummypets/YPImagePicker/issues/231

Cheers,

**Comment by blurtime** [comment]
@s4cha I'll try my best to do it as soon as I can but currently I barely have to time do get even pretty small things done... sorry :/

**Comment by s4cha** [comment]
@blurtime AVAssetExportPresetHEVCHighestQuality works well on my side. any new on this?

**Comment by pushpankq** [comment]
AVAssetExportPresetHEVCHighestQuality is also not working in my iPhone 6

**Comment by pushpankq** [comment]
and I found a link regarding this 

https://support.apple.com/en-us/HT207022



> @s4cha Sorry for answering so late, Swift 4.2 conversion had me occupied...
> 
> Now (Swift 4.2 and iOS 12) I get an error when I use the code you suggested:
> 
> In `LibraryMediaManager.swift (line 136)`, it says: `Fatal error: Unexpectedly found nil while unwrapping an Optional value`, namely the export session (`self.currentExportSessions.append(exportSession!`) which is set earlier (`line 119: let exportSession = AVAssetExportSession(asset: assetComposition, presetName: YPConfig.video.compression)`) using the export preset. Why isn't it working with the export preset `AVAssetExportPresetHEVCHighestQuality`?
> 
> EDIT: I apologize for not checking last time if this reply was well-formatted. I fixed it with this edit.
> 
> Some informations about the device I've been testing the picker on: I am using an iPhone 6. According to [this link](https://support.apple.com/en-us/HT207022) there shouldn't be any problems, as the videos I tested the picker with definitely were "no greater than 1080p/240 fps".
> 
> In addition to that, I was wondering whether there was an option to hide the tab or screen bar at the bottom of the screen if there was only one screen, e.g. only library (`config.screens = [.library]`).

I think iPhone 6 doesn't support HEVC 

https://support.apple.com/en-us/HT207022

**Comment by NikKovIos** [comment]
Closed because of stale. Feel free to reopen.
