### ISSUE TITLE
Camera preview Crash

### ISSUE THREAD

**Issue by rheligonwbi** [Yummypets/YPImagePicker#219]
**Describe the bug**
When i present the picker, i can see the library fine, but the photo preview sometimes takes about a minute to start the camera, and just stays in a black square. If i press cancel, then reopen the picker i get a crash error, because the object was deallocated.

**To Reproduce**
1. Go to open picker

**Expected behavior**
The camera preview to be available as soon as the view is displayed.

**Screenshots**

This is how the camera preview stays in black for a while, sometimes it starts after a minute (which is not good still, should be a few seconds), so i just put my picker to start on library view to give it some time, sometimes it stays black for a long time
![image](https://user-images.githubusercontent.com/42754294/45639622-2b4a5880-ba76-11e8-87bc-6e26aec0d6e6.png)

This is the line of code where i get the error.
![image](https://user-images.githubusercontent.com/42754294/45639518-da3a6480-ba75-11e8-8754-6c2ad2656f64.png)

This is the error in the console
![image](https://user-images.githubusercontent.com/42754294/45639563-f807c980-ba75-11e8-9669-70d10fa2d22d.png)

**Environment (please complete the following information):**
 - Device: iphone 6s
 - OS: iOS 11.4
 - Xcode Version 9.4
 - Swift Version 4.0

**Installation Type**
 - Cocoapods

**Additional context**
Please let me know if you need anything else.

**Comment by NikKovIos** [comment]
Could you please specify steps to reproduce. I test on iPhone 5s and everything is ok.

**Comment by rheligonwbi** [comment]
As i told before, all i do is just open and cancel several times. I will keep on testing and see if i get a procedure to reproduce it all the time, as it not always happens to me. After i restarted my phone it stopped happening.
Thank you for your reply.

**Comment by NikKovIos** [comment]
Also try to reproduce it in a test project to filter if the bug is on your side.

**Comment by s4cha** [comment]
@rheligonwbi Thanks for the detailed report, looking at it I can see that your version uses `[unowned]` tag. Latest releases now use `[weak]` which should solve the crash. What version are you using? Could you try updating it? I believe this is related to https://github.com/Yummypets/YPImagePicker/issues/178, which has been fixed in 3.4.0 :)

**Comment by rheligonwbi** [comment]
@s4cha Thank you very much, i had 3.3.1, which was the version the cocoa pods downloaded for me about yesterday? Effectively used the unowned in that code, by looking online i saw it might be an error caused by the unowned so i changed it manually to weak but it didnt work either way, so i figured i had to change more stuff and i decided not to do so.
But i updated today to 3.4.1 and i will see if that does not happen to me anymore.
Again, thank you for your reply.

**Comment by s4cha** [comment]
Closing this for now, feel free to reopen if needed :)
