### ISSUE TITLE
Display only gallery option in picker

### ISSUE THREAD

**Issue by ChintanWeapp** [Yummypets/YPImagePicker#22]
Currently in the SDK we've default options as either we can select images/videos from library or we can take it using camera. But it would be useful if SDK provides options so we can set only option from (library or photos or videos) for media selection.

**Comment by eddieespinal** [comment]
@ChintanWeapp, I added a logic for Video Only which you can easily duplicate for library only or photo only.  I created a PR to see if it can be implemented here.

https://github.com/Yummypets/YPImagePicker/pull/21

**Comment by s4cha** [comment]
@ChintanWeapp, @eddieespinal 

I was thinking that in a later version we could have something like:

```swift
screensToDisplay = [.album, .library, .video]
```
(Don't pay attention to the naming)

Such a thing would enable to customise the screens shown with a simple api.

for instance :
```swift
screensToDisplay = [.library] // Photo only
```

Let me know if you like the idea :)

**Comment by eddieespinal** [comment]
@s4cha I like that solution, let me know if you need help with the integration.

**Comment by ChintanWeapp** [comment]
@s4cha <https://github.com/s4cha>  I think that is a good idea.

**Comment by s4cha** [comment]
Here is the link of the PR :) https://github.com/Yummypets/YPImagePicker/pull/23

**Comment by s4cha** [comment]
@ChintanWeapp 
You should be able to do what you wanted in the latest version with:
```swift
config.screens = [.library]
```

https://github.com/Yummypets/YPImagePicker/releases/tag/2.6.0

Hope it helps :)

**Comment by s4cha** [comment]
@ChintanWeapp @eddieespinal closing this for now as this is now supported in the latest version :)
