### ISSUE TITLE
Fixed image size

### ISSUE THREAD

**Issue by rheligonwbi** [Yummypets/YPImagePicker#220]
Is there a way to make the image preview as a fixed height? In my current application we actually are fixing the height at 220 and the width is the device's.
Ive seen you use a squared ratio but i dont know if there is an easy way to customize the picker to preview and output the image with the height at 220.

In case of the final output and not the preview:

I saw in another question that you can do "config.showsCrop = .rectangle(ratio: (1/1))"
maybe i can use this to crop and make the final output this way? how can i do it with ratios?

Thank you

**Comment by NikKovIos** [comment]
Maybe `minWidthForItem` in version 3.4.1 would help you?

**Comment by rheligonwbi** [comment]
What i need fixed is height not widht, but im willing to try. 
Where can i find that property?, or should i just tweak around and find it?

**Comment by rheligonwbi** [comment]
@NikKovIos thank you for your reply, i didn't actually try your suggestion since it says width and what i need is height.

I think i found a workaround, maybe you can make it into a feature or something in the future or maybe it is intended to work that way but i couldn't find the way to use it as a ratio.

What i did now is that i used your property: 

> config.showsCrop = .rectangle(ratio: (220))

and in the file "YPCropView.swift" i changed the line where you assign the cropArea its height:
> //        cropArea.Height == cropArea.Width * r
         cropArea.Height == CGFloat(ratio)

The top line is what you had, the bottom one is the one i changed it to.

Now i get to crop the full image to the size of 220, allowing the user to crop the piece of the full picture he wants.

Thank you guys for this awesome picker and your fast replies.

**Comment by KingOlami** [comment]
hi, I am having this issue how do I solve it? my imageview does not show the selected image kindly help contribute https://github.com/Yummypets/YPImagePicker/issues/256

**Comment by NikKovIos** [comment]
Too old issue. Feel free to open new.
