### ISSUE TITLE
YPImagePickerExample crash

### ISSUE THREAD

**Issue by zhangchenzhuo** [Yummypets/YPImagePicker#223]
**Describe the bug**
crash on iPad iOS 12,  privacy permission ok, the photo and library is ok,  when switch from photo to video, looks like the camera does not open yet, start video and crash on file YPVideoProcessor.swift at line 65,  empty array asset. only happens when switch from photo to video. 

**To Reproduce**
1. Click Pick 
2. switch to photo
3. switch to video

**Screenshots**

![image](https://user-images.githubusercontent.com/15139184/45729668-1c8fad00-bc00-11e8-98ef-677938e62ebb.png)

**Environment (please complete the following information):**
 - Device: iPad pro A1673 
 - OS: iOS 12.0 16A366
 - Xcode  9.4 (9F1027a)
 - Swift Version 4.1(Xcode9.4 default)

**Installation Type**
 - Cocoapods update and try

**Comment by s4cha** [comment]
@zhangchenzhuo thanks for such a detailed crash report, it makes our lives so much easier 👍

**Comment by s4cha** [comment]
I just pushed a fix https://github.com/Yummypets/YPImagePicker/commit/7f343dce610088b64a1533791c0887512411b11e
I can't test on iPad at the moment so I did it kinda blindly :)

**Comment by s4cha** [comment]
Should be fixed in 3.5.2. Don't hesitate to reopen if it ever comes back :)

**Comment by zhangchenzhuo** [comment]
😂😂
Well, it **does not crash** but, the video is not shown on my iPad after i swap from photo to video, like the picture above. But, if i select video from gallery, and then swap to photo, everything is ok, after that, i swap to video, again, the video stopped and shows the last frame.
I tested on iPad and iPhone. 
After i change the system language from Chinese to English, the problem happens with **large probability**, not every time

Sorry for waiting, i have been busy for a long time

**Comment by s4cha** [comment]
@zhangchenzhuo thanks a ton for the precision, the other issue is tracked separately :)
