### ISSUE TITLE
Square Images and multiple Image Selection

### ISSUE THREAD

**Issue by DariusDresp** [Yummypets/YPImagePicker#226]
Hi,

If i just select one image everything works fine. However if I allow the user to select more than one image, the cropping of the images dont work always. The cropping of an image will only work in my case when I move the image manually at least a little bit in the editor. But if I select multiple images without touching the view of the image, the image will be forced into a squared ratio but it wont be cropped at all (I think for the first and last image selected however everything works like expected). Therefor some images look really bad as their ratios are completely changed. I hope I could explain my issue accurately and you know what I am talking about. Is this something only I am experiencing or is this a bug? Is there anything I can do to resolve that issue?

Cheers 
Darius 

<img width="306" alt="bildschirmfoto 2018-09-24 um 16 14 09" src="https://user-images.githubusercontent.com/34845692/45957298-feb5b400-c014-11e8-9bfe-2d7958b366e1.png">

(actually selected more than 2 images after I took the screenshot)

<img width="297" alt="bildschirmfoto 2018-09-24 um 16 14 37" src="https://user-images.githubusercontent.com/34845692/45957311-04ab9500-c015-11e8-9c0a-eabb9be2543d.png">

**Comment by s4cha** [comment]
@DariusDresp Thanks a ton for the report, this looks like a serious bug indeed!

**Comment by s4cha** [comment]
@DariusDresp this has been brilliantly fixed by @mpiechocki, this will be available in the next version (probably later today)

**Comment by s4cha** [comment]
@DariusDresp this should be good in https://github.com/Yummypets/YPImagePicker/releases/tag/3.5.3 
Let me know if that solves your issue :)
