### ISSUE TITLE
Video Filter 

### ISSUE THREAD

**Issue by yashbarotkunj** [Yummypets/YPImagePicker#227]
Need Video Filters like image or photo

How can I add video filter  

can please help me?

Thanks

**Comment by s4cha** [comment]
@yashbarotkunj Filters are not implemented for videos as we speak. This is something we might want to add in the future but we have no clear roadmap for this feature at the moment.
This is already tracked here : https://github.com/Yummypets/YPImagePicker/issues/101

Cheers,
