### ISSUE TITLE
Swift 3 -> version 1.2.1 not available via Pods

### ISSUE THREAD

**Issue by algrid** [Yummypets/YPImagePicker#229]
**Describe the bug**
I have a Swift 3 project and want to use the Swift 3 -> version 1.2.1 but `pod install` fails.

**To Reproduce**
1. Add `pod 'YPImagePicker', '1.2.1'` to your Podfile
2. Run `pod install`
3. See error:

```
[!] CocoaPods could not find compatible versions for pod "YPImagePicker":
  In Podfile:
    YPImagePicker (= 1.2.1)

None of your spec sources contain a spec satisfying the dependency: `YPImagePicker (= 1.2.1)`.
```

**Environment (please complete the following information):**
 - Xcode Version: 9.4.1
 - Swift Version 3.3

**Installation Type**
 - Cocoapods

**Comment by s4cha** [comment]
@algrid It seems that "1.2.1" has never been on Cocoapods for some reason. "1.2.0" should be available though. Please be aware that these are very old versions (1 year) and tons of stuff has been fixed / added in the meantime.
I would strongly encourage you to migrate to swift 4.+ whenever possible :)

**Comment by s4cha** [comment]
@algrid readme has been updated with 1.2.0 for swift 3.
Closing this for now, feel free to reopen if needed :)
