### ISSUE TITLE
Hide bottom bar if only one item activated?

### ISSUE THREAD

**Issue by cwestMobile** [Yummypets/YPImagePicker#231]
**Is your feature request related to a problem? Please describe.**
The project looks a bit weird if you only have .library selected for example, it negates the need for the bottom bar.

**Describe the solution you'd like**
Ability to hide the bottom bar, or have it hide automatically when only one item is selected

Let me know if you need more info.

**Comment by NikKovIos** [comment]
Great suggestion, thank you. By the way you can make it and submit a PR ;)

**Comment by s4cha** [comment]
@cwestMobile This is a very good UX idea :)

**Comment by s4cha** [comment]
@ylin0x81 just added a way to manually hide the bottom bar 👍 .
I would suggest we hide it automatically when showing a single screen as suggested by @cwestMobile .
Following the same logic, I think hiding the bar when having multiple screens can be misleading UX speaking.
What do you think? @NikKovIos @cwestMobile @ylin0x81 ?

**Comment by liniminil** [comment]
Makes sense to me.

**Comment by KingOlami** [comment]
hi, I am having this issue how do I solve it? my imageview does not show the selected image kindly help contribute https://github.com/Yummypets/YPImagePicker/issues/256

**Comment by NikKovIos** [comment]
Too old issue. Feel free to open new.
