### ISSUE TITLE
why i can't pod update about 3.5.0???

### ISSUE THREAD

**Issue by CtrlJone** [Yummypets/YPImagePicker#232]
CocoaPods could not find compatible versions for pod "YPImagePicker":
  In Podfile:
    YPImagePicker (~> 3.5.0)

**Comment by s4cha** [comment]
@nizenyang We are having an issue with one of our dependencies unfortunately so we are trying to fix it asap. Carthage integration works for 3.5.0 though.
This is tracked here : https://github.com/Yummypets/YPImagePicker/issues/214
