### ISSUE TITLE
Fixed photo size and "minWidthForItem" problem.

### ISSUE THREAD

**Issue by fikretsengul** [Yummypets/YPImagePicker#235]
I'm creating an application that has some ImageViews with a fixed height at 320 and the width is the device's. I tried the "minWidthForItem" but it just crops a rectangle that is devicesWidthx320. Is there any way to first scale the whole image for the size of width and than crop it's height as 320px.

Sorry for my bad english. Thank you for creating this amazing picker.

**Comment by NikKovIos** [comment]
I think you can try to use crop view with custom crop ratio. Check for it in settings.

**Comment by s4cha** [comment]
@fikretsengul Have you found a way?

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
