### ISSUE TITLE
Command CompileSwiftSources failed with a nonzero exit code

### ISSUE THREAD

**Issue by crspybits** [Yummypets/YPImagePicker#236]
**Describe the bug**
When I compile the example project with Xcode 10, I get this error.

**Comment by liniminil** [comment]
This is a known issue documented in [Swift 4.2 Release Notes for Xcode 10](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes/swift_4_2_release_notes_for_xcode_10)

> Compilation might fail without displaying the errors responsible for the failure. For example, you might see the message “Command CompileSwiftSources failed with a nonzero exit code” without an accompanying failure reason. (43033749)
Workaround: Disable batch mode by adding a user-defined build setting named SWIFT_ENABLE_BATCH_MODE and set it to NO.

<img width="896" alt="screen shot 2018-10-07 at 9 16 08 am" src="https://user-images.githubusercontent.com/43127399/46577161-298b0980-ca12-11e8-918d-c13d697bf25b.png">

Once you have added the build setting, the real problem will be revealed, `PryntTrimmerView.h` is missing.
<img width="1020" alt="screen shot 2018-10-05 at 4 49 21 pm" src="https://user-images.githubusercontent.com/43127399/46525947-8d50ed80-c8bf-11e8-8f67-838d24e85d1a.png">

To fix it, run `carthage update`, clean the build folder and then rebuild the example project.

**Comment by nico75005** [comment]
I don't have `SWIFT_ENABLE_BATCH_MODE`. There is nothing for me after `MTL_ENABLE_DEBUG_INFO`

**Comment by kkj915** [comment]
Umbrella header 'PrynTrimmerView.h' not found. after carthage update.
How to fix?

**Comment by G1King** [comment]
thanks ！ solved my problem

**Comment by raygun101** [comment]
Yup, fixed it for me, now I can see the actual compilation error.
THANKS!

**Comment by GergesEid** [comment]
In my case I connect an actual iphone not simulator and run the app once on it, It solved the problem. But connect iphone firstly, then choose it from the menu of simulator, then press run button.
The problem will solve too.

**Comment by xlsd** [comment]
it does not work for me. Xcode12 bate3

**Comment by xinzy** [comment]
> it does not work for me. Xcode12 bate3

And XCode 12.2

**Comment by hardmen** [comment]
it does not work for me. Xcode13.0.

**Comment by sikloDev** [comment]
> it does not work for me. Xcode13.0.

did you find a solution for this good sir?

**Comment by xlevchenko** [comment]
> > it does not work for me. Xcode13.0.
> 
> did you find a solution for this good sir?

Hi,
Steps To get fixes of these errors:
![20210707172729582](https://user-images.githubusercontent.com/34953510/139906563-82395fba-190c-486f-bdf7-a6aaa748aa80.png)

SWIFT_COMPILATION_MODE
