### ISSUE TITLE
Deprecation Warnings - XCode 10 Swift 4.2

### ISSUE THREAD

**Issue by 5fcgdaeb** [Yummypets/YPImagePicker#240]
**Describe the bug**
After installing the 3.5.1 version via Cocoapods, the following warnings appear during compile-time.

`didSelectImage, didSelectVideo, didCancel are deprecated; use <alternativeMethod> instead`

**To Reproduce**
Install version 3.5.1 via Cocoapods and build you project.

**Environment (please complete the following information):**
- Deployment Target: 10.0
 - Xcode Version 10.0
 - Swift Version 4.2

Would it be possible to remove these warnings? I prefer not to inhibit them via Cocoapods myself.

Thanks!

**Comment by s4cha** [comment]
@5fcgdaeb Thanks for reminding us about that, these were left for a while for backwards compatibility purposes, it's been a while so it's time to remove them for good :)
This will be done in next release 👍
