### ISSUE TITLE
Is there an easy way to set a max height to an image in preview?

### ISSUE THREAD

**Issue by mlazic95** [Yummypets/YPImagePicker#244]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mlazic95** [comment]
Is there an easy way to set a max height to an image in preview? Right now the whole image is viewed no matter of its dimensions and that kind a break my whole app. I would like it to be more like instagram if that is possible. Thank you in advance.

**Comment by liniminil** [comment]
@markolazic261 Setting a `minWidthForItem` might fits your needs.
``` swift
/* Can forbid the items with very big height with this property */
config.library.minWidthForItem = UIScreen.main.bounds.width * 0.8
```

**Comment by mlazic95** [comment]
It seems to work. Thank you very much!
