### ISSUE TITLE
Not getting Assets and Data after recording video

### ISSUE THREAD

**Issue by Neelu1112** [Yummypets/YPImagePicker#251]
After recording video,
fetching video using below code,
`if let video = items.singleVideo`
  in which` video.asset` is nil
                 `video.data` is nil
I want PHAsset or Data to upload video in facebook through SDK.

**Comment by vijayevolgence** [comment]
Same problem

**Comment by vijayevolgence** [comment]
Please fix the issue asap

**Comment by ndemie** [comment]
This still seems to be an issue. Has anyone managed to resolve this? Cause right now it's impossible to use recorded videos making that feature completely broken.

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
