### ISSUE TITLE
Order is duplicate on multi select when a new image is taken

### ISSUE THREAD

**Issue by taratandel** [Yummypets/YPImagePicker#252]
When selecting some pictures then take pictures with camera app on coming back to the original App All the new images were selected with duplicate numbers.

1. Go to the Library and Select for example 3 pictures. leave the app here
2. Get out of the app and take some pictures with camera App
3. Go back to the original app 
4. See the new pictures are selected from 1 and the old selected pictures are still selected from number one.

the new pictures should not get selected.

step 1
![img_0943](https://user-images.githubusercontent.com/23617793/47009919-81c8b680-d14a-11e8-88b6-b0927ab77d14.jpg)
 after step 3 
![img_0944](https://user-images.githubusercontent.com/23617793/47009951-973de080-d14a-11e8-84db-6a7175a02d84.jpg)

 - Device: [iPhone6]
 - OS: [.iOS12.0.1]
 - Xcode Version [10.0]
 - Swift Version [4.2]

**Installation Type**
 - Cocoapods

**Comment by KingOlami** [comment]
hi, I am having this issue how do I solve it? my imageview does not show the selected image kindly help contribute https://github.com/Yummypets/YPImagePicker/issues/256

**Comment by s4cha** [comment]
@taratandel That is a nice catch! I believe this is already fixed in the next version, will keep you posted when it's out :)

**Comment by s4cha** [comment]
@taratandel this should be fixed in https://github.com/Yummypets/YPImagePicker/releases/tag/3.5.3, feel free to reopen if you still experience the issue :)
