### ISSUE TITLE
Can't change camera overlay height

### ISSUE THREAD

**Issue by mBilal5674** [Yummypets/YPImagePicker#254]
I want to change camera overlay height.

**Comment by AdieOlami** [comment]
hi, I am having this issue how do I solve it? my imageview does not show the selected image kindly help contribute https://github.com/Yummypets/YPImagePicker/issues/256

**Comment by mBilal5674** [comment]
but here i can't find out how to maximize overlay height

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
