### ISSUE TITLE
Is there a feature i show images only , if i give media type images only still shows the video picker

### ISSUE THREAD

**Issue by abdullah-et** [Yummypets/YPImagePicker#255]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AdieOlami** [comment]
hi, I am having this issue how do I solve it? my imageview does not show the selected image kindly help contribute https://github.com/Yummypets/YPImagePicker/issues/256

**Comment by s4cha** [comment]
@abdullah-et 
```swift
//change
config.screens = [.library, .photo, .video]
// into
config.screens = [.library, .photo]
```
This is actually the default configuration :)

**Comment by s4cha** [comment]
Closing this for now for lack of activity, @abdullah-et don't hesitate to reopen if you still encounter the issue.
