### ISSUE TITLE
Picker deinited imageview not showing selected image

### ISSUE THREAD

**Issue by AdieOlami** [Yummypets/YPImagePicker#256]
Hi, so I was trying this library of yours and followed the exact process by first installing the dependencies, giving permissions in info.plist, followed by, using the custom configurations or otherwise, by using the default YPImagePicker instance, and whenever I try to instantiate the Camera or Library i get a console print, "Picker deinited 👍" and nothing else happens.. I can't seem to understand why this might be happening hence need your insights on this. Please update as soon as possible. Very grateful for all the help.

I am having this issue how do I solve it? my imageview does not show the selected image

here is my config

```


        var config = YPImagePickerConfiguration()
        config.library.mediaType = .photo
        config.library.onlySquare  = false
        config.onlySquareImagesFromCamera = false
        config.targetImageSize = .cappedTo(size: 1024)
//        config.usesFrontCamera = true
        config.showsFilters = false
//        config.filters = [YPFilterDescriptor(name: "Normal", filterName: ""),
//                          YPFilterDescriptor(name: "Mono", filterName: "CIPhotoEffectMono")]
        config.shouldSaveNewPicturesToAlbum = true
        config.video.compression = AVAssetExportPresetHighestQuality
        config.albumName = "Sheduler"
        config.screens = [.library, .photo]
        config.startOnScreen = .library
        config.video.recordingTimeLimit = 10
        config.video.libraryTimeLimit = 20
        config.showsCrop = .none //.rectangle(ratio: (16/9))
        config.wordings.libraryTitle = "Gallery"
        config.hidesStatusBar = false
//        config.overlayView = myOverlayView
        config.library.maxNumberOfItems = 1
        config.library.minNumberOfItems = 1
        config.library.numberOfItemsInRow = 3
        config.library.spacingBetweenItems = 2
        config.isScrollToChangeModesEnabled = true

```

**Comment by AdieOlami** [comment]
works now. I was hiding the selected image

**Comment by s4cha** [comment]
@KingOlami Glad this is now solved :)
In the future, please do not reference your issue on other posts, be aware that this does not help solve your issue faster :) Happy new Year!

**Comment by Clint1994** [comment]
@AdieOlami  I am having the same issue now. Did you have to edit anything in the YPconfigure file? Also how did you unhide the selected image? 

Thanks mate.
