### ISSUE TITLE
Hide bar at the bottom if only one screen configured 

### ISSUE THREAD

**Issue by blurtime** [Yummypets/YPImagePicker#257]
This is just a small suggestion. I'm sure I could've solved this myself and contributed it but I really do not have the time right now and can barely finish the most essential parts of my projects. Would it be possible to add a boolean somewhere indicating whether to hide the bar at the bottom of the picker that says e.g. "Library" if only one screen is used. Or don't even bother creating a boolean for this but hiding the bar automatically if only one screen is configured like so: 

config.screens = [.library]

Especially if less then 4 items pre row are displayed (e.g. 3), things start to look a little more cramped up at the bottom of the screen, I feel.

**Comment by liniminil** [comment]
Duplicate of https://github.com/Yummypets/YPImagePicker/issues/231
