### ISSUE TITLE
How to get the physical location of the selected image

### ISSUE THREAD

**Issue by jksjaz** [Yummypets/YPImagePicker#258]
I am using realm database in my iOS app and I need the selected Image location that user chose and want to transfer that url to my database for my other view controllers to access it from.

Thanks for your help.

**Comment by neodave** [comment]
Inside of the YPMediaPhoto class there is a variable asset: PHAsset? This is the what you need in order to get the url. Below are extensions to the PHAsset class that will allow you to get the URL like this

```swift
var imageURL: URL?

YPMediaAsset.getURL(completionHandler{ (url) in
    if url != nil {
        imageURL = url!
    }
}


extension PHAsset {
    var originalFilename: String? {
        return PHAssetResource.assetResources(for: self).first?.originalFilename
    }
    
    func getURL(completionHandler : @escaping ((_ responseURL : URL?) -> Void)){
        if self.mediaType == .image {
            let options: PHContentEditingInputRequestOptions = PHContentEditingInputRequestOptions()
            options.canHandleAdjustmentData = {(adjustmeta: PHAdjustmentData) -> Bool in
                return true
            }
            self.requestContentEditingInput(with: options, completionHandler: {(contentEditingInput: PHContentEditingInput?, info: [AnyHashable : Any]) -> Void in
                completionHandler(contentEditingInput!.fullSizeImageURL as URL?)
            })
        } else if self.mediaType == .video {
            let options: PHVideoRequestOptions = PHVideoRequestOptions()
            options.version = .original
            PHImageManager.default().requestAVAsset(forVideo: self, options: options, resultHandler: {(asset: AVAsset?, audioMix: AVAudioMix?, info: [AnyHashable : Any]?) -> Void in
                if let urlAsset = asset as? AVURLAsset {
                    let localVideoUrl: URL = urlAsset.url as URL
                    completionHandler(localVideoUrl)
                } else {
                    completionHandler(nil)
                }
            })
        }
    }
}
```

**Comment by neodave** [comment]
That formatted strangely. everything from extension PHAsset down should be in one block

**Comment by s4cha** [comment]
@neodave Thanks a ton for chiming in, I just edited the formatting for clarity :)
@jksjaz Did that help?

**Comment by KOSURUUDAYSAIKUMAR** [comment]
Hi Friends,
public class YPMediaPhoto {
    
    public var image: UIImage { return modifiedImage ?? originalImage }
    public let originalImage: UIImage
    public var modifiedImage: UIImage?
    public let fromCamera: Bool
    public let exifMeta: [String: Any]?
    public var asset: PHAsset?
    public var url: URL?
    public var imageURL: URL?
    public init(image: UIImage, exifMeta: [String: Any]? = nil, fromCamera: Bool = false, asset: PHAsset? = nil, url: URL? = nil) {
        self.originalImage = image
        self.modifiedImage = nil
        self.fromCamera = fromCamera
        self.exifMeta = exifMeta
        self.asset = asset
        self.asset?.getURL(completionHandler: { url in
            if url != nil {
                print("Image url ----------------", url)
                self.imageURL = url!
            }
        })
        self.url = url
    }
    
}

But while I am calling 
 picker.didFinishPicking { [unowned picker] items, cancelled in 
if let firstItem = items.first {
                switch firstItem {
                case .photo(let photo):
                photo.assest --- > not getting imageURL keyword
                }
   }
}

Can you please help me
