### ISSUE TITLE
The next button isn't appearing

### ISSUE THREAD

**Issue by canarc** [Yummypets/YPImagePicker#261]
**Describe the bug**
When I take a photo or chose in gallery after filtering there is no next button

**Screenshots**
https://prnt.sc/l9zydy

**Environment (please complete the following information):**
 - Device: [iPhone 7]
 - OS: [iOS 12]
 - Xcode Version [10.0]
 - Swift Version [4.2]

**Installation Type**
 - Cocoapods

**Comment by dasoli** [comment]
@canarc make sure you dont have set stuff like that:
` UINavigationBar.appearance().tintColor = .white
        
        let attributes = [ NSAttributedString.Key.foregroundColor: UIColor.white,
                           NSAttributedString.Key.font: UIFont.systemFont(ofSize: 14) ]
        
        UIBarButtonItem.appearance().setTitleTextAttributes(attributes, for: .normal)
        UIBarButtonItem.appearance().setTitleTextAttributes(attributes, for: .highlighted)`
after i removed my one, it worked (check yours)

**Comment by bybash** [comment]
Hi, 
After capturing a photo, filter view takes the control and manipulates navigation bar, it hides the next button and also it adds a back button. When you go back to photo capture view, navigation bar doesn't show Cancel button and it shows back button which is added in filter view and it is not tappable 👎 I will debug and investigate codes.

**Comment by bybash** [comment]
I just tried the demo app, it is working good. However, the same codes are not showing navigationbar items correctly inside my project. I consider and debug too much and figure it out, a navigationcontroller is not working good when it is presented by a tabbarcontroller or a modal uiviewcontroller. My view diagram just like this, tabbarcntrl -> navcntrl -> viewcntrl -> modalviewcntrl -> ypimagepicker 
So in this flow, it is not showing correctly navigation items. What we need to this I don't know, I'm trying.

**Comment by jeanmartin** [comment]
Just encountered the same issue, for me this only happens on iPad (coming from a modal view opened from a SplitView), iPhone works fine. I am also setting the color of UIBarButtonItems manually as described above. Will investigate further.

**Comment by s4cha** [comment]
This is weird indeed, I've never encountered it personally :/

**Comment by s4cha** [comment]
@jeanmartin, @canarc, @bybash any news on that one?

**Comment by canarc** [comment]
I was fixed this subject.I dont remember exactly but it was like about presentation the ypimagepicker.when i was presented it on different page it was worked
