### ISSUE TITLE
Add a crop circle enum possibilities

### ISSUE THREAD

**Issue by El-Buritos** [Yummypets/YPImagePicker#263]
Hello very good framework, I read that you thought to do this in the near future but no more news, will you always implement this possibilities `config.showsCrop = .circle`? Thanks to your framework and your reply.

El-Buritos

**Comment by neodave** [comment]
This would be very helpful for us as well

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
