### ISSUE TITLE
video is not show properly in ios version 11.4.1 after doing zoom

### ISSUE THREAD

**Issue by Jatinharish** [Yummypets/YPImagePicker#264]
Hi,

When we select video from Gallary. and zoom that video. after that i press next button then video is not show properly. Its working fine in all devices but not in device which have version 11.4.1.

![screen shot 2018-10-26 at 12 45 38 pm](https://user-images.githubusercontent.com/12663449/47550541-29996d80-d91d-11e8-85f3-2a99228e9e58.png)

Please  resolve it ASAP

**Comment by Simerpal** [comment]
has anybody resolved it?

**Comment by Edward-Bazko** [comment]
Also reproduces on iPhone 6 and 6s, iOS 12.4.1. 

@Simerpal adding this line helped:
```
videosOptions.deliveryMode = .highQualityFormat
```
in `LibraryMediaManager.swift` class, method `fetchVideoUrlAndCrop(...)`, line 70. So it's somehow related to iCloud video fetching.

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
