### ISSUE TITLE
Adding Ability to Add Caption / Text to Photos.

### ISSUE THREAD

**Issue by ugenlik** [Yummypets/YPImagePicker#265]
**Is your feature request related to a problem? Please describe.**
My app requires adding a caption to a photo when uploading.  Or Adding a caption to each photo when selecting/uploading multiple photos.

Also my users won't need to have Filters or Crops, so I use this library mostly just for the multiple selection and taking photos. 

**Describe the solution you'd like**

![captionview](https://user-images.githubusercontent.com/1995917/47677958-f2ce8c00-db96-11e8-9421-5e5bb9dcf5cf.gif)

Adding another state like Filter, Crop and Caption would be the solution. 

I forked the repo and made the changes I need to have , however since it is a major change it needs a lot of detailed improvements. 

It'd be nice to see this changes in the next version.

Things I have changed:

1. Added caption to Photo Media Item

```
public class YPMediaPhoto {
    
    public var image: UIImage { return modifiedImage ?? originalImage }
    public let originalImage: UIImage
    public var modifiedImage: UIImage?
    public let fromCamera: Bool
    public let exifMeta : [String : Any]?
    public var asset: PHAsset?
    public var caption:String?
    
    init(image: UIImage, exifMeta : [String : Any]? = nil, fromCamera: Bool = false, asset: PHAsset? = nil, caption:String? = nil) {
        self.originalImage = image
        self.modifiedImage = nil
        self.fromCamera = fromCamera
        self.exifMeta = exifMeta
        self.asset = asset
        self.caption = caption
    }
}
```

2. Added showsCaption flag to Config files `YPConfigLibrary` section 

```
    public var showsCaption: Bool = false
```

For multiple selections, filter and caption doesnt work at the same time so usage becomes like this

```
config.filters = []
config.library.showsCaption  = true
```

or for single photos if you want to both use Filters and Caption you can just use

```
config.library.showsCaption  = true
```

TODOs:

- Didnt translate localized changes
- Caption view's font and sizes are hardcoded, will make this configurable
- For multiple selection Filters and Caption doesn't work at the same time, so user needs to disable either one in configuration file. This part was a bit more complicated because if user wants to edit the photos we need to know if they want to just edit the filter or caption or both?  

I will make a merge request from my fork and can work on this future if others also needs a feature like this.

**Comment by s4cha** [comment]
@ugenlik 
First of all thank you for taking the time and energy to try and improve the library, this is much appreciated. At the same time, I wish we had discussed this before you issued the pull request.
This is my fault actually for taking a long time to reply 🙏 
Our app also needs a caption before sending to the server. However I believe this kind of functionality belongs on the "app side" of things and not the library side. There are so many different ways to handle captions, for example some catch hashtags or mentions etc, I think this would be kind of utopic to try and do a generic way that would match all app use cases that need a caption.
To be honest I am not sure we are willing to support this use case on the library side.
The preferred way, in my opinion, is to have the ImagePicker final callback feed into a new UI where the captions are added, keeping the features separated. @NikKovIos I'd love your point of view on this :)

**Comment by ugenlik** [comment]
@s4cha I agree merge request shouldn't be merge for various reasons.

But I disagree that adding caption should be only in "app side". 

If all apps had a similar approach to Instagram's caption I'd agree captions being on the app side but my app requires individual captions like filters, so I think it should be on the library side.

Another problem doing this on the App Side is UI/UX wise it might not be an identical experience to previous steps. 

For example: I use Library with certain configurations and I pick multiple images and apply filters then Library's model view gets dismissed and I have to pop another model view and another image picker like view to add captions. 

I think end-user could get an extra step and more sluggish experience.

That's my two cents tho, I will keep using a fork if this feature won't be supported in the feature releases

**Comment by ClintNurse** [comment]
Hi @ugenlik  

Do you mind me asking how did you get the caption view controller to appear after choosing the filter ? This is something I am currently working on a project and a caption needs to be included as well.

Thanks mate

**Comment by ClintNurse** [comment]
@ugenlik Anyway you can sure your version of the caption code mate?

**Comment by NikKovIos** [comment]
Totally agree with @s4cha. In my app the caption also use the custom UI. Image picker library should pick image and pass on. Cropping, filters is already side functions, but they are complex and the library allows to disable them. UI for caption always different and not needed there.

However folks who need this feature can copy code manually from MR https://github.com/Yummypets/YPImagePicker/pull/266
