### ISSUE TITLE
custom crop template

### ISSUE THREAD

**Issue by userdar** [Yummypets/YPImagePicker#27]
Hello there, first of all i love your work. it's awesome and easy to customize. i want to create a custom rectangular (2:1 aspect ratio) crop area for certain use cases. (such as cover photos) can you implement such a feature maybe something like:
config.customCrop = true
config.cropRectangleRatio(width:1,height:2)
and maybe something like 
config.cropCircle = true

can you walk me through or what is your opinion on the matter?

**Comment by s4cha** [comment]
Hey @userdar thanks for the kind words ! 

It sounds like a very good idea :) We could provide crop support like we provide filters indeed. I will start a PR tomorrow so that we can discuss the api and start coding.

**Comment by s4cha** [comment]
@userdar here is the PR where we can discuss this new api :)
https://github.com/Yummypets/YPImagePicker/pull/29

**Comment by userdar** [comment]
awesome :). this library will be great with your attitude and care. I have another question, as soon as i choose image from library the quality goes from 100 to 10, why do you think it's happening i'm developing some kind of social media app so image quality is important,

**Comment by s4cha** [comment]
@userdar Concerning the quality
I just opened another issue to track that separately: https://github.com/Yummypets/YPImagePicker/issues/33

**Comment by s4cha** [comment]
@userdar  Very happy to have the v1 of the crop live in 2.7.0
https://github.com/Yummypets/YPImagePicker/releases/tag/2.7.0
Thanks so much suggesting this cool addition 👍

**Comment by s4cha** [comment]
@userdar the quality issue should be fixed in the latest version 2.8.0
Also we are going to close this one and track the circle crop in a separate issue if you don't mind : 
https://github.com/Yummypets/YPImagePicker/issues/77
