### ISSUE TITLE
workflow for optional crop?

### ISSUE THREAD

**Issue by wdcurry** [Yummypets/YPImagePicker#271]
I don't yet use the repo, and have tried to see a standard (for me) use case is available: while presenting the crop view, to not force a crop, but accept a full image instead. The option to crop or not can be very useful.

**Comment by s4cha** [comment]
@wdcurry This is not supported at the moment but I like the idea :)

**Comment by davidrobertovenegas** [comment]
This would be very useful. End users want a full picture by default.

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
