### ISSUE TITLE
Ability to override the library's image assets 

### ISSUE THREAD

**Issue by ghost** [Yummypets/YPImagePicker#272]
**Is your feature request related to a problem? Please describe.**
To create a consistent UI/UX with the rest of my app, it would be nice to be able to override the assets on the YPImagePicker, for instance, the camera taking button image, video taking button image, flash auto image, flash off image, etc.

**Describe the solution you'd like**
To create public outlets for the respective UIButtons so that we can set new images on them.

<img width="263" alt="screen shot 2018-11-13 at 8 26 27 am" src="https://user-images.githubusercontent.com/9462299/48419551-df3a2e00-e71d-11e8-8bba-d6fbd39710f2.png">

**Comment by s4cha** [comment]
@datureezy You should be able to do this by overriding the `icons` property like so 

```swift
config.icons. capturePhotoImage = [YouUIImageHere]
```

Here is the `YPIcons` file for reference 
```swift
public struct YPIcons {

    public var shouldChangeDefaultBackButtonIcon = false
    public var hideBackButtonTitle = true

    public var backButtonIcon: UIImage = imageFromBundle("yp_arrow_left")
    public var arrowDownIcon: UIImage = imageFromBundle("yp_arrow_down")
    public var cropIcon: UIImage = imageFromBundle("yp_iconCrop")
    public var flashOnIcon: UIImage = imageFromBundle("yp_iconFlash_on")
    public var flashOffIcon: UIImage = imageFromBundle("yp_iconFlash_off")
    public var flashAutoIcon: UIImage = imageFromBundle("yp_iconFlash_auto")
    public var loopIcon: UIImage = imageFromBundle("yp_iconLoop")
    public var multipleSelectionOffIcon: UIImage = imageFromBundle("yp_multiple")
    public var multipleSelectionOnIcon: UIImage = imageFromBundle("yp_multiple_colored")
    public var capturePhotoImage: UIImage = imageFromBundle("yp_iconCapture")
    public var captureVideoImage: UIImage = imageFromBundle("yp_iconVideoCapture")
    public var captureVideoOnImage: UIImage = imageFromBundle("yp_iconVideoCaptureRecording")
    public var playImage: UIImage = imageFromBundle("yp_play")
}
```
I'v personally not tried it so I'd love to know if everything works as expected on your side.
Looks like we need to document this in the readme as well :)

**Comment by s4cha** [comment]
@datureezy @Tom-Fox1  any news?

**Comment by ghost** [comment]
Haven’t gotten the assets designed but I’m taking your word for it. Thank you for this library!!
