### ISSUE TITLE
I don't want to square the video after recording 

### ISSUE THREAD

**Issue by MandeepSingh1** [Yummypets/YPImagePicker#275]
Hey Guys, Thanks for your awesome library but I don't want to square the video after recording but still   I need that video to rotate to video. So if I don't use the below code its not working anymore. Can you guys help me 

Below is your function:- 
static func cropToSquare(filePath: URL, completion: @escaping (_ outputURL : URL?) -> ()) {
        
        // output file
        let outputPath = makeVideoPathURL(temporaryFolder: true, fileName: "squaredVideoFromCamera")
        
        // input file
        let asset = AVAsset.init(url: filePath)
        let composition = AVMutableComposition.init()
        composition.addMutableTrack(withMediaType: .video, preferredTrackID: kCMPersistentTrackID_Invalid)
        
        // Prevent crash if tracks is empty
        if asset.tracks.isEmpty {
            return
        }
        
        // input clip
        let clipVideoTrack = asset.tracks(withMediaType: .video)[0]
        
        // make it square
        let videoComposition = AVMutableVideoComposition()
        videoComposition.renderSize = CGSize(width: CGFloat(clipVideoTrack.naturalSize.height), height: CGFloat(clipVideoTrack.naturalSize.height))
        videoComposition.frameDuration = CMTimeMake(value: 1, timescale: 30)
        let instruction = AVMutableVideoCompositionInstruction()
        instruction.timeRange = CMTimeRangeMake(start: CMTime.zero, duration: CMTimeMakeWithSeconds(60, preferredTimescale: 30))
        
        // rotate to potrait
        let transformer = AVMutableVideoCompositionLayerInstruction(assetTrack: clipVideoTrack)
        let t1 = CGAffineTransform(translationX: clipVideoTrack.naturalSize.height, y: -(clipVideoTrack.naturalSize.width - clipVideoTrack.naturalSize.height) / 2)
        let t2: CGAffineTransform = t1.rotated(by: .pi/2)
        let finalTransform: CGAffineTransform = t2
        transformer.setTransform(finalTransform, at: CMTime.zero)
        instruction.layerInstructions = [transformer]
        videoComposition.instructions = [instruction]
        
        // exporter
        let exporter = AVAssetExportSession.init(asset: asset, presetName: YPConfig.video.compression)
        exporter?.videoComposition = videoComposition
        exporter?.outputURL = outputPath
        exporter?.shouldOptimizeForNetworkUse = true
        exporter?.outputFileType = YPConfig.video.fileType

        exporter?.exportAsynchronously {
            if exporter?.status == .completed {
                DispatchQueue.main.async(execute: {
                    completion(outputPath)
                })
                return
            } else if exporter?.status == .failed {
                print("YPVideoProcessor -> Export of the video failed. Reason: \(String(describing: exporter?.error))")
            }
            completion(nil)
            return
        }
    }

And thats mine function:- 
static func cropToSquare(filePath: URL, completion: @escaping (_ outputURL : URL?) -> ()) {
        
        // output file
        let outputPath = makeVideoPathURL(temporaryFolder: true, fileName: "squaredVideoFromCamera")
        
        // input file
        let asset = AVAsset.init(url: filePath)
        let composition = AVMutableComposition.init()
        composition.addMutableTrack(withMediaType: .video, preferredTrackID: kCMPersistentTrackID_Invalid)
        
        // Prevent crash if tracks is empty
        if asset.tracks.isEmpty {
            return
        }
        
        // input clip
        let clipVideoTrack = asset.tracks(withMediaType: .video)[0]
        
        // make it square
        let videoComposition = AVMutableVideoComposition()
        
        // rotate to potrait
        let transformer = AVMutableVideoCompositionLayerInstruction(assetTrack: clipVideoTrack)
        let t1 = CGAffineTransform(translationX: clipVideoTrack.naturalSize.height, y: -(clipVideoTrack.naturalSize.width - clipVideoTrack.naturalSize.height) / 2)
        let t2: CGAffineTransform = t1.rotated(by: .pi/2)
        let finalTransform: CGAffineTransform = t2
        transformer.setTransform(finalTransform, at: CMTime.zero)
        instruction.layerInstructions = [transformer]
        videoComposition.instructions = [instruction]
        
        // exporter
        let exporter = AVAssetExportSession.init(asset: asset, presetName: YPConfig.video.compression)
        exporter?.videoComposition = videoComposition
        exporter?.outputURL = outputPath
        exporter?.shouldOptimizeForNetworkUse = true
        exporter?.outputFileType = YPConfig.video.fileType

        exporter?.exportAsynchronously {
            if exporter?.status == .completed {
                DispatchQueue.main.async(execute: {
                    completion(outputPath)
                })
                return
            } else if exporter?.status == .failed {
                print("YPVideoProcessor -> Export of the video failed. Reason: \(String(describing: exporter?.error))")
            }
            completion(nil)
            return
        }
    }

Thanks Guys

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
