### ISSUE TITLE
Video session is not started 

### ISSUE THREAD

**Issue by MandeepSingh1** [Yummypets/YPImagePicker#277]
**Describe the bug**

**To Reproduce**
1. Go to Video
2. Click on Cancel 
3. Again open the picker and go to video and then again click on cancel. Do this scenario for upto 3-4 times. You will see video session is not started properly.

**Environment (please complete the following information):**
 - Device: [e.g. iPhoneX]
 - OS: [e.g. iOS12.1]
 - Xcode Version [e.g. 10.0]
 - Swift Version [e.g. 4.1]

**Installation Type**
 - Cocoapods

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
