### ISSUE TITLE
Only portrait oriented application is not getting correct Image orientation after capture

### ISSUE THREAD

**Issue by bybash** [Yummypets/YPImagePicker#279]
Hi there, 

In my application, I tried to use YPImagePicker directly with source integration. I have a portrait oriented application and I never needed to use UIDevice.current.orientation, when I tried to capture photos in landscape mode, images weren't rotated correctly. I have checked that my UIDevice.current.orientation is always unknown. 
I tried your demo app and it doesn't have that problem so this is not a bug, however, I'm writing this because if someone gets this issue in his/her project, they can fix it.
So I added some codes to init and deinit of YPImagePicker to notify device from orientation changes. 

```
public required init(configuration: YPImagePickerConfiguration) {
        YPImagePickerConfiguration.shared = configuration
        picker = YPPickerVC()
        super.init(nibName: nil, bundle: nil)
        picker.imagePickerDelegate = self
        //added
        if !UIDevice.current.isGeneratingDeviceOrientationNotifications
        {
            UIDevice.current.beginGeneratingDeviceOrientationNotifications()
        }
}
```

```
deinit {
        print("Picker deinited 👍")
        //added
        if UIDevice.current.isGeneratingDeviceOrientationNotifications
        {
            UIDevice.current.endGeneratingDeviceOrientationNotifications()
        }
    }
```

Thanks for your great job, I loved the library 😊🙏👍🏻

**Comment by s4cha** [comment]
@bybash Thanks for taking the time to document this for other people. 
I'm going to leave this open for now :)
I'll take a deeper look whenever I have some time.

**Comment by s4cha** [comment]
@bybash next version will use the accelerometer directly  thanks to  @kf99916 PR https://github.com/Yummypets/YPImagePicker/pull/376/files.
So this will yield the correct orientation independently from DeviceOrientationNotifications. 🎉
