### ISSUE TITLE
Video not squared when playing it back.

### ISSUE THREAD

**Issue by viktorgardart** [Yummypets/YPImagePicker#28]
With the configuration below, after recording the video it's not saved as squared. When playing it back in an AVPlayerLayer it's in portrait mode. 

**Configuration:**
```swift
var config = YPImagePickerConfiguration()
config.onlySquareImagesFromLibrary = true
config.onlySquareImagesFromCamera = true
config.showsVideo = true
config.showsFilters = false
config.videoCompression = AVAssetExportPresetPassthrough
config.libraryTargetImageSize = .cappedTo(size: mediaSize)
let picker = YPImagePicker(configuration: config)
```

**Comment by viktorgardart** [comment]
Setting the `videoGravity` on the layer makes it look correct on the screen but when saving the video to camera roll it's saved in portrait mode.

**Comment by s4cha** [comment]
@viktorgardart yep it wasn’t something we needed internally which is why it’s never been done but it’s definitely something we can add. No idea how hard it is to define a output format for videos though. Would you be willing to have a look?

**Comment by viktorgardart** [comment]
Can do 🙂

**Comment by viktorgardart** [comment]
Hmm, appears to be more work than expected, (to get it right). And I don't really need it either. Might look at this at a later time!

**Comment by s4cha** [comment]
Ok we can keep that here for reference, there are higher priority issues at the moment but it will be a welcome improvement :)

**Comment by NikKovIos** [comment]
Would be there https://github.com/Yummypets/YPImagePicker/issues/54 😉
