### ISSUE TITLE
Disable default trimming for videos > 60 seconds

### ISSUE THREAD

**Issue by esabunor** [Yummypets/YPImagePicker#283]
Hi, thank you for this awesome project. I have observed that videos that are greater than 60 seconds are trimmed to 60 seconds after been processed, is there a way to disable this behaviour?

**Comment by esabunor** [comment]
For future googlers config.video.trimmerMaxDuration = \\ whatever

**Comment by s4cha** [comment]
@esabunor I am going to add it to the readme, thanks for noticing the missing doc :)

**Comment by iqbal0029** [comment]
how to skip trim screen?

**Comment by UtkuDalmaz** [comment]
> how to skip trim screen?

Any information about this?

**Comment by iqbal0029** [comment]
var config = YPImagePickerConfiguration()
config.showsCrop = .none
