### ISSUE TITLE
[Question] NavigationBar Tint Color Changes

### ISSUE THREAD

**Issue by UtkuDalmaz** [Yummypets/YPImagePicker#284]
I use white tint color for Navigation controller navigationbar tint color. 
When I present picker view it changes tint color to black
I tried to change tint color back to white on didFinishPicking but it doesn't work
```
UIBarButtonItem.appearance().tintColor = .white
UINavigationBar.appearance().tintColor = .white
```

**Comment by Pro2005** [comment]
The same issue. The problem is inside YPImagePicker
`        
// If user has not customized the Nav Bar tintColor, then use black.
        if UINavigationBar.appearance().tintColor == nil {
            UINavigationBar.appearance().tintColor  = .black
        }
`

**Comment by UtkuDalmaz** [comment]
> The same issue. The problem is inside YPImagePicker
> ` // If user has not customized the Nav Bar tintColor, then use black. if UINavigationBar.appearance().tintColor == nil { UINavigationBar.appearance().tintColor = .black }`

Any workaround?

**Comment by Pro2005** [comment]
You just need to set tintColor using appearance
It should work in most cases

**Comment by UtkuDalmaz** [comment]
> You just need to set tintColor using appearance
> It should work in most cases

I tried setting tint color in didFinishPicking
`UINavigationBar.appearance().tintColor = .white`

It just doesn't work

**Comment by Pro2005** [comment]
I've just forked and commented these lines
https://github.com/Pro2005/YPImagePicker

https://github.com/Pro2005/YPImagePicker/commit/796f1f76b862a05c42a104a22d03c18eee2f1135

**Comment by UtkuDalmaz** [comment]
Fixed that now
