### ISSUE TITLE
Video View freeze on iOS 12.1

### ISSUE THREAD

**Issue by nightroadcosplay** [Yummypets/YPImagePicker#285]
When I open the YPImagePicker (default on photo) and switch to video, the video view freeze.
I can still do other things(like: cancel, switch front-rear camera), only the view freeze. 

**To Reproduce**
1. Go to Picker, default photo
2. Switch to video
3. Video view freezes
4. In console I get the following error:

AVAudioSessionPortImpl.mm:56:ValidateRequiredFields: Unknown selected data source for Port Speaker (type: Speaker)

**Environment:**
 - Device: Iphone 5s
 - OS: iOS 12.1
 - Xcode Version 10.1
 - Swift Version 4.2

**Installation Type**
 - Cocoapods

What should I do? Is a problem from the new OS version?
On version 12.0 it worked well.

**Comment by nightroadcosplay** [comment]
After some debugging i got this error when the video view freeze:

 [avas] AVAudioSessionPortImpl.mm:56:ValidateRequiredFields: Unknown selected data source for Port Speaker (type: Speaker)

**Comment by mohshaat1990** [comment]
any solution for this bug?

**Comment by adriansergheev** [comment]
on iOS 12.1.4, iPhone SE it is still here.

**Comment by NikKovIos** [comment]
@andriansergheev @nightroadcosplay is it still actual?

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
