### ISSUE TITLE
Library crop does not work when maxNumberOfItems = 1

### ISSUE THREAD

**Issue by calsmith** [Yummypets/YPImagePicker#290]
**Describe the bug**
Cropping from the Library picker only works when . This does not impact the showsCrop = true UI.

**To Reproduce**
1. config.library.maxNumberOfItems = 1
2. Pick an image from the Library
3. Zoom into part of the image from the Library picker
4. Original image is returned, crop/zoom is ignored

**Installation Type**
 - Manual

**Additional context**
This can be fixed by removing the check for "strongSelf.multipleSelectionEnabled" in YPLibraryVC.swift:85

**Comment by s4cha** [comment]
@calsmith this is now live in https://github.com/Yummypets/YPImagePicker/releases/tag/3.5.3, thanks a ton for your help on this release 🚀
