### ISSUE TITLE
Loading RAW images infinitely.

### ISSUE THREAD

**Issue by jasudev** [Yummypets/YPImagePicker#293]
Loading RAW images infinitely.

There is an infinite loading problem when selecting RAW images.

When selecting a RAW image, the original image must be able to be evicted. Or at least I want to be able to show that I have selected a RAW image. Depending on the support, there may be a way to display "RAW" on the thumbnail image of the image you want to select from the picker list screen.

Please explain if there is a good way to solve the problem. Thank you.

**Comment by jasudev** [comment]
requestImageData(for: asset, options: options) { data, dataUTI, CTFontOrientation, info in
if let data = data, let image = UIImage(data: data)?.resetOrientation() {
When the RAW image (sony raw format ARW) image is selected, "UIImage(data: data)" value in the above function is nil.

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
