### ISSUE TITLE
If you switch to a square, the horizontal and vertical size of the image will be 1px different.

### ISSUE THREAD

**Issue by jasudev** [Yummypets/YPImagePicker#294]
Select a single image and zoom in to a square. If you go to the next screen and check the size of the image, the horizontal and vertical sizes will differ by 1px.

**Comment by s4cha** [comment]
@jasudev eagle eye. Have no idea why at the moment. We need to investigate :)

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
