### ISSUE TITLE
Default square

### ISSUE THREAD

**Issue by jasudev** [Yummypets/YPImagePicker#295]
`config.library.onlySquare = false`

I would like to be able to show square images by default when loading library images. The Instagram also sets the square image to default. If you like, you can change the ratio of the original image through the bottom left button.

I would like to be able to set it as square image by default. Or I would like to have such a function.
Thank you.

**Comment by s4cha** [comment]
@jasudev Thanks for pointing this out. Indeed we want to be as close as possible the to instagram implementation. If I understand well you just want to have the default set to square crop, but still having the option to zoom out. Going to experiment and will report back :)

**Comment by s4cha** [comment]
Setting `private var shouldCropToSquare = true` in `YPAssetViewContainer.swift` will do the trick :) This will be up in the next version, I'll keep you posted when it's up :)

**Comment by s4cha** [comment]
@jasudev this is now the default in https://github.com/Yummypets/YPImagePicker/releases/tag/3.5.3
Feel free to reopen if it doesn't fit what you wanted :)

**Comment by javiermanzo** [comment]
Hi @s4cha , **onlySquare** is not working. I don't want to crop the photos or videos.

> config.library.onlySquare = false

All the videos and photos are cropped.

**Comment by javiermanzo** [comment]
I created an issue and pull request #317
