### ISSUE TITLE
Init Picker with Multiple Images button selected

### ISSUE THREAD

**Issue by SonicGerkor** [Yummypets/YPImagePicker#296]
**Describe the bug**
I wanted to know if you can init the picker with the multiple images button already selected.

**Comment by s4cha** [comment]
@SonicGerkor Indeed you can use
```swift
config.library.minNumberOfItems = 2
config.library.maxNumberOfItems = 5
```
This will force multiple selection :)
Let me know if that fits your use case, cheers!

**Comment by SonicGerkor** [comment]
Perfect bro, thanks!

**Comment by iTofu** [comment]
User can't just select one image.
