### ISSUE TITLE
requestImageData RAW image data is nil

### ISSUE THREAD

**Issue by jasudev** [Yummypets/YPImagePicker#297]
`requestImageData(for: asset, options: options) { data, dataUTI, CTFontOrientation, info in`

When the RAW image (sony raw format ARW) image is selected, "UIImage(data: data)" value in the above function is nil.

**Comment by s4cha** [comment]
@jasudev good catch, I've never tried with raw images to be honest :)
Could you provide the raw image triggering the bug so that I can debug it on my side please?
Cheers,

**Comment by jasudev** [comment]
@s4cha https://drive.google.com/file/d/1Ts8QJJL2A5mfzkTC7e2r1mLS5128QL2m/view?usp=sharing
Raw file of Sony camera series. Thank you.

**Comment by jasudev** [comment]
@s4cha http://www.rawsamples.ch/index.php/en/sony

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
