### ISSUE TITLE
App size increasing after getting pictures/videos

### ISSUE THREAD

**Issue by farhan101** [Yummypets/YPImagePicker#298]
App size increasing after getting pictures/videos.
Every time I use YPImagePicker to get videos/images, it increases my app size. It keeps on increasing and increasing. I have to delete the app and reinstall to get it back to normal size. Is there any way to clear the cache?

**Comment by s4cha** [comment]
Hi @farhan101,

Could you elaborate a bit more on how you measure the App size increase so that we can try to reproduce on our end?
Also, are you experiencing the same using the provided Example project ?

**Comment by farhan101** [comment]
> Hi @farhan101,
> 
> Could you elaborate a bit more on how you measure the App size increase so that we can try to reproduce on our end?
> Also, are you experiencing the same using the provided Example project ?

Upload some pictures/videos to accumulate the size. Then go to iPhone's  Settings -> General -> iPhone Storage -> Select your app -> check app and documents & data size. This keeps increasing after uploads.

PS: I printed the app's storage contents and I can see images and videos lying in "temp" folder. I guess they are not being removed from there OR I am missing a some configuration???

I shall also try this with your sample projects as well and update you with the results.

**Comment by deeplinkage** [comment]
This is a big issue if you upload big video files like I do. How can this be resolved? Thanks

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮

**Comment by ratz6** [comment]
anyone fixed it anyhow ?
