### ISSUE TITLE
Ability to remove sound track from video

### ISSUE THREAD

**Issue by ghost** [Yummypets/YPImagePicker#299]
**Is your feature request related to a problem? Please describe.**
Video picked from the library always include the sound track. Sometimes you have amazing video with annoying sounds (say cars driving by) and you would like to be able to only keep the video track and ditch the audio track.

**Describe the solution you'd like**
 Similarly to how IG does it, could we add a button for the user to disable the audio track of their video. 

In an ideal scenario, we would add a button on top of the video trimmer view that the user could tap to remove or add back the audio track of their video. Doing so would mute/ unmute the playback of the video and based on what the user has selected it would export the video/ audio tracks or only the video track (using the AVPlayer Asset tracksWithMediaType and removing the track with audio/ only keeping the asset associated with the video track).

**Describe alternatives you've considered**
A "simpler" solution could be to add the button to know the user's intention and have the didFinishPicking call-back return a Bool with the user intention with regard to whether or not s/he wants to keep the audio of the video or not. The devs could then manually extract the video track from the returned video if the user only wants to keep the video w/o audio.

**Additional context**
I took a quick look at the code and see that we already have an export session taking an asset as input. All we would need to do is add a condition to feed that export session with the asset being including either the video + audio track or the asset being just the video track.

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
