### ISSUE TITLE
Video Thumbnail Selection?

### ISSUE THREAD

**Issue by cwestMobile** [Yummypets/YPImagePicker#30]
I was wondering if there was currently a way to choose a specific thumbnail for a video?

Thanks.

**Comment by s4cha** [comment]
@cwestMobile At the moment the thumbnail is the first frame of the video, so customisation is not supported. I think you could push a custom view onto the picker if you'd like to customise this with your own UI.
Here is the code to generate a thumbnail `UIImage` out of a video URL file.


```swift
func thunbmailFromVideoPath(_ path: URL) -> UIImage {
    let asset = AVURLAsset(url: path, options: nil)
    let gen = AVAssetImageGenerator(asset: asset)
    gen.appliesPreferredTrackTransform = true
    let time = CMTimeMakeWithSeconds(0.0, 600)
    var actualTime = CMTimeMake(0, 0)
    let image: CGImage
    do {
        image = try gen.copyCGImage(at: time, actualTime: &actualTime)
        let thumbnail = UIImage(cgImage: image)
        return thumbnail
    } catch { }
    return UIImage()
}
```

Hope this helps,

**Comment by NikKovIos** [comment]
Going to be here https://github.com/Yummypets/YPImagePicker/issues/54 😁

**Comment by Berk-Kaya** [comment]
How can I disable thumbnail selection?
