### ISSUE TITLE
Present Picker with count of selected pictures

### ISSUE THREAD

**Issue by SonicGerkor** [Yummypets/YPImagePicker#301]
**Describe the bug**
I have an array of UIImage which I set when selecting images, appending them.
My max is 5, but I can select 1, dismiss it, then another, dismiss it, then 5 more. And it should allow me 3 more, not 5.

Is there a way to present the picker with the current amount of pictures selected?

**Comment by NikKovIos** [comment]
Change the configuration - max count, depending on how much items already exists.

**Comment by SonicGerkor** [comment]
Yeah I did that as soon as I finished typing the issue, thanks!
