### ISSUE TITLE
After changing the album, the automatically selected image is not selected.

### ISSUE THREAD

**Issue by jasudev** [Yummypets/YPImagePicker#302]
In single image selection, if you click Next on the first image automatically selected for the first time after changing the album, the image of the previous album will be processed.

**Comment by s4cha** [comment]
This is a very serious bug indeed, I'm trying to fix it for the next (swift5) version :)
Will report back when it's fixed !

**Comment by s4cha** [comment]
@jasudev This should be fixed by https://github.com/Yummypets/YPImagePicker/pull/340, this will be part of the upcoming release :)

**Comment by s4cha** [comment]
This is now solved in https://github.com/Yummypets/YPImagePicker/releases/tag/4.0.0
