### ISSUE TITLE
Additional Config: Disable Crop on Library; Save position of images being cropped

### ISSUE THREAD

**Issue by angelo-RSVP** [Yummypets/YPImagePicker#305]
**Disable Crop on Library**
This can be redundant if we have `config.screens = [.library, .photo]` and `config.showsCrop = .rectangle(ratio: (1/1))`. 

Can we have something like `config.library.enableCrop = true`, wherein if it's false we just show the collection of images that can be selected, and show normally (with preview) if true.

**Save position of images being cropped**
When navigating from MyViewController and back to CropVC, the position of the image that was cropped is reset to center. 

Can we have a `config.saveCropPosition = false` so we can save the user's selection when this happens?

**Comment by emresancaktar** [comment]
Did you find any solution ? I don't want to crope my image too.

**Comment by s4cha** [comment]
@angelo-RSVP Never though of this and this is redundant indeed. We have other priorities (urgent bug fixes) at the moment but this definitely desirable.
@emresancaktar Have you tried `config.showsCrop = .none` (which is the default value) ?

**Comment by emresancaktar** [comment]
Hello @s4cha thanks for the quick answer. Yes, I fixed my problem with `config.onlySquareImagesFromCamera = false`  somehow `config.showsCrop = .none` didn't work for me. Thanks for the library btw.

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
