### ISSUE TITLE
READEME.md unsuitablity

### ISSUE THREAD

**Issue by devliuhuan** [Yummypets/YPImagePicker#309]
**Describe the READEME.md unsuitablity**
all Languages which suported Contry or region is English Name, but "繁體中文（台灣）" is very diffrient,this makes developers from China uncomfortable。

** Advice**
1. Use English for all language instructions
2. Use the supported language to instruce

**Comment by NikKovIos** [comment]
Sorry, but i can't understand what do you mean😅

**Comment by lonely4flow** [comment]
That means change the Languages part if you can will be more acceptable ,for example:
from:
🇺🇸 English, 🇪🇸 Spanish, 🇫🇷 French 🇷🇺 Russian, 🇳🇱 Dutch, 🇧🇷 Brazilian, 🇹🇷 Turkish, 🇸🇾 Arabic, 🇩🇪 German, 🇮🇹 Italian, 🇯🇵 Japanese, 🇨🇳 Chinese, 🇮🇩 Indonesian, 🇰🇷 Korean, 🇹🇼 繁體中文（台灣）
to:
🇺🇸 English, 🇪🇸 Spanish, 🇫🇷 French 🇷🇺 Russian, 🇳🇱 Dutch, 🇧🇷 Brazilian, 🇹🇷 Turkish, 🇸🇾 Arabic, 🇩🇪 German, 🇮🇹 Italian, 🇯🇵 Japanese, 🇨🇳 Chinese, 🇮🇩 Indonesian, 🇰🇷 Korean, 🇹🇼Traditional Chinese（Taiwan）
Or to:
![image](https://user-images.githubusercontent.com/47106210/51877650-f8ab5780-23a7-11e9-9a1a-a5fdd6068741.png)

**Comment by NikKovIos** [comment]
Sorry, i'm not a specialist in kinds of languages. If you can, please submit a PR.

**Comment by s4cha** [comment]
@devliuhuan thanks for noticing, we'll use English for all languages then, this must have slipped through a Pull request :)
