### ISSUE TITLE
Run time error

### ISSUE THREAD

**Issue by aneena-thomas** [Yummypets/YPImagePicker#31]
When run the git project it shows,

Module compiled with Swift 4.0.3 cannot be imported in Swift 4.0: /Users/Aneena/Downloads/YPImagePicker-master 2/Carthage/Build/iOS/Stevia.framework/Modules/Stevia.swiftmodule/x86_64.swiftmodule

**Comment by s4cha** [comment]
@aneena-thomas,
You downloaded manually right ?
`Github > Clone or Download > Download Zip > Run`
This works fine on my side :/
 What is your Xcode version? (mine is 9.2)

Cheers,

**Comment by s4cha** [comment]
@aneena-thomas If you are using `Carthage`

Running:
`carthage update --platform iOS --no-use-binaries`

will rebuild dependencies with your local Xcode version (here Stevia)
That can save you form having to update Xcode in the meantime :)

Hope this helps,

**Comment by aneena-thomas** [comment]
My also 9.2.

**Comment by aneena-thomas** [comment]
when i run in Xcode 9.1,its working

**Comment by aneena-thomas** [comment]
z][4

**Comment by s4cha** [comment]
@aneena-thomas glad to know it fixes your issue :)
