### ISSUE TITLE
Camara preview stuck at black when swiping to video sometimes

### ISSUE THREAD

**Issue by lshannak** [Yummypets/YPImagePicker#314]
**Description**
When launching the picker and then going to the video section by swiping right, the camera preview for video is stuck at black, sometimes this happens on first use, and it also happens after the first use when the user opens the picker and swipes to the video.
What helps reproduce the issue sometimes is swiping fast to the video section.
The picker is being started from the library option, so the user has to swipe twice to get to the video section.

**Environment (please complete the following information):**
 - OS: 12, 11.4
 - Xcode Version 10
 - Swift Version 4.2

**Installation Type**
 - Cocoapods

**Comment by aldammit** [comment]
i've got the same problem too

**Comment by Saurav1143** [comment]
also i have got the same issue...

**Comment by ilai1823** [comment]
me too

**Comment by kkadyrbekov** [comment]
i also have same problem

**Comment by mrayls** [comment]
We also have this issue.

**Comment by Goldy-74** [comment]
Me too :(

**Comment by Palando** [comment]
I had this problem because there was an active phone call. After hanging up it worked.

**Comment by ruanorz** [comment]
any solution?

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
