### ISSUE TITLE
Code signing "PryntTrimmerView.framework" failed.

### ISSUE THREAD

**Issue by yugeshm** [Yummypets/YPImagePicker#316]
When I am uploading my app to App Store I am getting "Code signing "PryntTrimmerView.framework" failed."

![screenshot 2019-02-15 at 10 49 22 pm](https://user-images.githubusercontent.com/22911076/52873011-fac93080-3173-11e9-84d6-5c7edabdc679.png)

**Environment (please complete the following information):**
 - OS: 10.14
 - Xcode Version 10.1
 - Swift Version4.1

**Installation Type**
 - Manual

**Comment by AkiraTokyo2023** [comment]
https://stackoverflow.com/questions/54274148/how-to-code-sign-a-carthage-framework-for-app-store-submission

It's work for me.
