### ISSUE TITLE
Start config zoomableView

### ISSUE THREAD

**Issue by javiermanzo** [Yummypets/YPImagePicker#317]
Hi,
If I set **config.library.onlySquare = false** the **zoomableView** starts square.

**To Reproduce**
Set **config.library.onlySquare = false**

**Expected behavior**
If the user set **config.library.onlySquare = false** the **zoomableView** start config should not fit square.
If the user set **config.library.onlySquare = true** the **zoomableView** start config should fit square.

**Comment by s4cha** [comment]
@javiermanzo I think there is a confusion here. The `onlySquare` setting forces selecting square images. However setting in to no doesn't "force" non square images.
If you look at the instagram app for example (which is our model for the implemented features), users can choose both square and non-square images, yet the picker always starts with a "crop-to-square" setting. This is actually the intended behaviour.
So `If the user set config.library.onlySquare = false the zoomableView start config should not fit square` is not the intended behaviour :)
Could you explain your use case in more details so we can try and find a solution that fits you?

**Comment by appfabtech** [comment]
@s4cha I think he means that it would be very useful to have a congif flag telling the library not to start with a "crop-to-square". And that's what I'd need too because I going to use in a tech support app and they want to start library with full size image to pick it
Thanks

**Comment by javiermanzo** [comment]
As @appfabtech said, I want to start the library without the crop to square. My PR #318 solves that.

**Comment by qky1412** [comment]
so how to 'start the library without the crop to square'?

**Comment by NikKovIos** [comment]
Sorry guys, you need to import the library in your project and make the changes from https://github.com/Yummypets/YPImagePicker/pull/318 by yourself.

**Comment by schveiguy** [comment]
I added a new PR that I think will be accommodating enough. #414
