### ISSUE TITLE
Video Aspect Ratio other then square

### ISSUE THREAD

**Issue by lohenyumnam** [Yummypets/YPImagePicker#320]
Any plan for supporting video recording other than Square Aspect ratio ??

**Comment by dstuecken** [comment]
Would also be awesome for photo selection and taking.

**Comment by s4cha** [comment]
@lohenyumnam this is a wanted feature indeed. Our time is quite limited at the moment so if you want to take a crack at it through a PR, feel free :)
@dstuecken Photo selection is not square only and you can already take non-square photos by setting `config.onlySquareImagesFromCamera = false`. Hope this helps.
Cheers :)

**Comment by yunustek** [comment]
Has this problem been solved? I'm having this problem too.

**Comment by s4cha** [comment]
Non square video taking will be available in next version :)
