### ISSUE TITLE
Picker dismiss on iOS 10.3.3 version

### ISSUE THREAD

**Issue by RahulTBI** [Yummypets/YPImagePicker#321]
Hi when i present YPImagePicker in above 10.3.3 version it works perfectly. but below that it dismiss instantly.

please help me out

Thanks
RahulTBI

**Comment by RahulTBI** [comment]
Hiii @ylin0x81 any update?

**Comment by s4cha** [comment]
@RahulTBI I just tried with a 10.3.1 simulator and unfortunately couldn't reproduce the issue. May be is it linked to https://github.com/Yummypets/YPImagePicker/issues/292 is the library empty?

**Comment by RahulTBI** [comment]
Thanks @s4cha 
What should i do if phone gallery is empty?

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
