### ISSUE TITLE
Pictures on iclound show abnormal size after downloading

### ISSUE THREAD

**Issue by cuirhong** [Yummypets/YPImagePicker#324]
Before modification
  let videosOptions = PHVideoRequestOptions()
 videosOptions.isNetworkAccessAllowed = true

 
After modification
let videosOptions = PHVideoRequestOptions()
videosOptions.isNetworkAccessAllowed = true
videosOptions.version = .original

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
