### ISSUE TITLE
Problem with Swift 5, problem raising from Stevia fillContainer()

### ISSUE THREAD

**Issue by shopno111** [Yummypets/YPImagePicker#327]
Hi, 
I got a problem with Swift 5, and Problem raising from Stevia fillContainer()

**Comment by shopno111** [comment]
My Issue is solved by updating with latest Stevia.framework

**Comment by s4cha** [comment]
@shopno111 This will be fixed in next (swift 5) version coming soon, thanks for your patience :)

**Comment by s4cha** [comment]
This is now solved in https://github.com/Yummypets/YPImagePicker/releases/tag/4.0.0
