### ISSUE TITLE
How to present the picker again with the images shown as selected

### ISSUE THREAD

**Issue by userSV** [Yummypets/YPImagePicker#328]
Is this possible to just present (or push) the picker , select the multiple media and then dismiss (or pop) it and then again present it with the last selected media?

**Comment by s4cha** [comment]
@userSV Unfortunately this is not supported at the moment.

**Comment by kyounghak** [comment]
> @userSV Unfortunately this is not supported at the moment.

still not supported?

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
