### ISSUE TITLE
YPAlbumCell: How to change textcolor of title & numberOfItems

### ISSUE THREAD

**Issue by Skyb0rg** [Yummypets/YPImagePicker#329]
Could someone told me how to change the textColors without manipulating the pod?

Thank you

**Comment by s4cha** [comment]
@Skyb0rg I'm afraid there is no supported way to do that at the moment. Could you describe your use case in a bit more details to see if we can support it in the future?

**Comment by Skyb0rg** [comment]
> @Skyb0rg I'm afraid there is no supported way to do that at the moment. Could you describe your use case in a bit more details to see if we can support it in the future?

Hi @s4cha,
i have a dark theme and now it looks like
![Simulator Screen Shot - iPhone Xs Max - 2019-05-04 at 13 43 07](https://user-images.githubusercontent.com/5628005/57178556-906e8500-6e72-11e9-9139-bc0d30927c0b.png)

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
