### ISSUE TITLE
Tint color is not applied to icons

### ISSUE THREAD

**Issue by jonathansolorzn** [Yummypets/YPImagePicker#330]
I expected that `config.colors.tintColor` would be applied to all the elements, but it's not applied to the icons.

Shouldn't it be like that?

**Comment by s4cha** [comment]
@fenixsolorzano Good one, what icon in particular are you looking to tint?

**Comment by jonathansolorzn** [comment]
All of them, _(I believe the ones are the flash and rotate)_

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
