### ISSUE TITLE
Default first image is selected in library but user will be able skip image selection

### ISSUE THREAD

**Issue by himanshujamnaniopenxcell** [Yummypets/YPImagePicker#331]
By Default first image is selected but I want that if user want to skip the image selection so he can in library.

**Comment by s4cha** [comment]
@himanshujamnaniopenxcell I'm sorry but I'm afraid I can't grasp what your are trying to achieve. Could you please rephrase and elaborate? 
Cheers,

**Comment by himanshujamnaniopenxcell** [comment]
Can we do something like user can see skip button initially when there is no image selection and when user select any image can see done button?

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
