### ISSUE TITLE
Remove Cover Option

### ISSUE THREAD

**Issue by xRose1** [Yummypets/YPImagePicker#333]
Hi 
Is it possible to remove the cover option from the video and only leave the trimmer function. I was wondering if someone knew. Also is it possible to record as much as a person wants and be able to cut down the video or recording to a specified time. Thank you.

**Comment by Berk-Kaya** [comment]
did you find a solution?

**Comment by bios90** [comment]
Found solution how to disable bottom buttons.

Just activate search and search for "YPVideoFiltersVC". Open that file (Agree with file editing in this library if needed). To disable cover button just comment lines in this file : 

`coverBottomItem.textLabel.text = YPConfig.wordings.cover`
`coverBottomItem.button.addTarget(self, action: #selector(selectCover), for: .touchUpInside)`

Now you cover button is disabled and not visible and you can disable trim button same way.

**Comment by Rajesh9274** [comment]
> Found solution how to disable bottom buttons.
> 
> Just activate search and search for "YPVideoFiltersVC". Open that file (Agree with file editing in this library if needed). To disable cover button just comment lines in this file :
> 
> `coverBottomItem.textLabel.text = YPConfig.wordings.cover`
> `coverBottomItem.button.addTarget(self, action: #selector(selectCover), for: .touchUpInside)`
> 
> Now you cover button is disabled and not visible and you can disable trim button same way.

This solution not working in latest i tried but i cant disable cover button.

**Comment by Samigos** [comment]
Would be great if we could have cover selection as optional
