### ISSUE TITLE
Project broke on new Xcode 10.2

### ISSUE THREAD

**Issue by snowtema** [Yummypets/YPImagePicker#334]
**Describe the bug**
After upgrading on the new version of Xcode 10.2, the project doesn't compile with an error:
```
Error: module map file '/Users/_REDACTED_/Pods/Headers/Public/Stevia/SteviaLayout.modulemap' not found
Error: underlying Objective-C module 'Stevia' not found
```

If I'll delete **pod** and comment **associated code** then the project will successfully be compiled.

**To Reproduce**
1. Upgrade to Xcode 10.2 
2. Try to build project
3. See error

**Expected behavior**
Successfully build projects

**Screenshots**

**Environment (please complete the following information):**
 - Device: any
 - OS: OS X 10.14.4
 - Xcode Version 10.2
 - Swift Version 5
 - pod version 3.5.3

**Installation Type**
 - Cocoapods

**Comment by s4cha** [comment]
@snowtema this will be fixed with the upcoming swift 5 version. thanks you for your patience :)

**Comment by s4cha** [comment]
This is now solved in https://github.com/Yummypets/YPImagePicker/releases/tag/4.0.0

**Comment by snowtema** [comment]
Thank you! 😊 🙏
