### ISSUE TITLE
Cannot record video longer than 60 seconds

### ISSUE THREAD

**Issue by Alexandru993** [Yummypets/YPImagePicker#336]
Export of the video failed. Reason: Optional(Error Domain=AVFoundationErrorDomain Code=-11841 "Operation Stopped" UserInfo={NSLocalizedDescription=Operation Stopped, NSLocalizedFailureReason=The video could not be composed.})

**Comment by mrayls** [comment]
We also have this problem.

**Comment by ghost** [comment]
Submitted pull request #351

**Comment by NirajCapermint** [comment]
Same issue, have any solution?

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
