### ISSUE TITLE
Video recording after device lock

### ISSUE THREAD

**Issue by geekellan** [Yummypets/YPImagePicker#337]
**Describe the bug**
When app lock by auto-lock on device, video still recording with black screen.

**To Reproduce**
1. Go to 'Recording video'
2. Click on 'Record'
3. Wait till device lock
4. Unlock device.
5. Video was recorded with black screen and with extended time

 - Swift Version 4.2

**Installation Type**
 - Cocoapods

**Comment by ruanorz** [comment]
same error here... did you solve it? thank you

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
