### ISSUE TITLE
Why NSMicrophoneUsageDescription?

### ISSUE THREAD

**Issue by Ewg777** [Yummypets/YPImagePicker#34]
```

        var config = YPImagePickerConfiguration()
        config.screens = [.library, .photo]
        let picker = YPImagePicker(configuration: config)

        picker.didSelectImage = { [unowned picker] img in

        }
```
Is there a way to avoid asking the permission (NSMicrophoneUsageDescription)? The lib should allow to pick images only
@s4cha

**Comment by s4cha** [comment]
@Ewg777 This is needed for taking videos.
Indeed it is still even when videos is not shown, I am going to take a look.
Thanks for spotting that :)

**Comment by s4cha** [comment]
@Ewg777 You should be good to go as for 2.6.2 🎉 
https://github.com/Yummypets/YPImagePicker/releases/tag/2.6.2
Thanks a ton for taking the time to report an issue :)

**Comment by Ewg777** [comment]
Awesome! Thanks! Closed!
