### ISSUE TITLE
Crop Video to 10 seconds no matter the length

### ISSUE THREAD

**Issue by xRose1** [Yummypets/YPImagePicker#341]
I am trying to adjust the trimmer so that you can select or record any video of any time or a time range that I picked and then you can trim it to 10 seconds like instagram. Does anyone have an idea on how they can do that or achieved? Thanks

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
