### ISSUE TITLE
Error in YPImagePickerExample for swift 5

### ISSUE THREAD

**Issue by dev-mobile01** [Yummypets/YPImagePicker#344]
Showing Recent Messages
:-1: Multiple commands produce '/Users/esmaeil/Library/Developer/Xcode/DerivedData/YPImagePickerExample-fmxnsnafskomcqhhrpyzocijrwuj/Build/Products/Debug-iphoneos/YPImagePickerExample.app/Frameworks/Stevia.framework':
1) Target 'YPImagePickerExample' has copy command from '/Users/esmaeil/Downloads/YPImagePicker-master/Carthage/Build/iOS/Stevia.framework' to '/Users/esmaeil/Library/Developer/Xcode/DerivedData/YPImagePickerExample-fmxnsnafskomcqhhrpyzocijrwuj/Build/Products/Debug-iphoneos/YPImagePickerExample.app/Frameworks/Stevia.framework'
2) That command depends on command in Target 'YPImagePickerExample': script phase “[CP] Embed Pods Frameworks”

**Comment by dev-mobile01** [comment]
Solved error

**Comment by tryWabbit** [comment]
What did you do to solve the error @momeni1367 ?

**Comment by s4cha** [comment]
This should be solved by now :) Feel free to reopen if needed.

**Comment by fukemy** [comment]
how did u solved this?
