### ISSUE TITLE
Multiple Selection mode crash when photo library is empty

### ISSUE THREAD

**Issue by daveleenew** [Yummypets/YPImagePicker#347]
**Describe the bug**
Multiple Selection mode crash when photo library is empty

Temporary solution:

YPLibraryVC.swift

if selection.isEmpty {
                ///Temporary solution:
                if(mediaManager.fetchResult.count == 0){return}
                
                let asset = mediaManager.fetchResult[currentlySelectedIndex]
                selection = [
                    YPLibrarySelection(index: currentlySelectedIndex,
                                       cropRect: v.currentCropRect(),
                                       scrollViewContentOffset: v.assetZoomableView!.contentOffset,
                                       scrollViewZoomScale: v.assetZoomableView!.zoomScale,
                                       assetIdentifier: asset.localIdentifier)
                ]
            }

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Xcode Version [e.g. 9.4.1]
 - Swift Version [e.g. 4.1]

**Installation Type**
 - Carthage
 - Cocoapods
 - Manual

**Additional context**

**Comment by aegzorz** [comment]
We're seeing the same crashes in our app.

**Comment by victormihaita** [comment]
@daveleenew what is the status for this issue?

**Comment by daveleenew** [comment]
Sorry i don't know. Please contact the author.

「Victor Mihaita <notifications@github.com>」在 2019年5月31日 週五，下午2:57 寫道：

**Comment by Vollando** [comment]
Having similar issue where pressing multiple selection button after denying photo library access permission results in a crash

**Comment by angelo-RSVP** [comment]
> I don't know why the sample app isn't showing the multiple button until permission is granted. Is there a configuration for it?

Update: Just hid the button on first launch until permission is checked

public override func viewDidLoad() {
        super.viewDidLoad()        
        . . .
        v.assetViewContainer.multipleSelectionButton.isHidden = true
 }

**Comment by s4cha** [comment]
This should be fixed with @hansemannn PR. It will be in the next version, hopefully by the end of the week.
