### ISSUE TITLE
Unable to capture Video with front and back both camera

### ISSUE THREAD

**Issue by CearsKhush** [Yummypets/YPImagePicker#348]
Hello, 

Thank you for this amazing library. I want to capture one video with front camera and back camera both but I am unable to do this.  I had commented this line         **v.flipButton.isEnabled = !state.isRecording** in this function         **private func updateUIWith(state: ViewState) {** and I started recording and trying to changing camera back to front but whenever I change to camera Its stop recording, I want to do that while Recording If I change camera back to front or front to back then It will record one video with both camera.

Is there any way to do this? 

Please anyone Help me with this? 

Thanks!

**Comment by YogendraPatel** [comment]
@CearsKhush I also want this feature. have you find any solution?

**Comment by CearsKhush** [comment]
@YogendraPatel  I had integrated **SCRecorder's** camera in to this library to solve my problem, Here is link for **SCRecorder** https://github.com/rFlex/SCRecorder

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
