### ISSUE TITLE
Crop image with movable rectangle

### ISSUE THREAD

**Issue by tejaskdubal** [Yummypets/YPImagePicker#349]
I want to create preview with crop feature along with movable rectangle (please see attached image).

Please provide configuration that change cropping style.

![20110517-cropsquare](https://user-images.githubusercontent.com/32478101/57678579-252d6b80-7647-11e9-9400-be0748c9f634.jpg)

Thanks.

**Comment by jensonjohn001** [comment]
It will be helpful if available.

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
