### ISSUE TITLE
Order of videos get shuffle

### ISSUE THREAD

**Issue by userSV** [Yummypets/YPImagePicker#352]
**Describe the bug**

When the videos are selected from the picker, there order gets shuffle automatically. Also if the images and videos are selected simultaneously, on the preview screen, all images come before the videos.

**To Reproduce**
1. Select multiple videos
2. Click on next
3. There order gets shuffled

**Expected behavior**
The order should remain as selected

**Screenshots**

**Environment (please complete the following information):**
 - Xcode Version [e.g. 9.4.1]
 - Swift Version [e.g. 4.1]

**Installation Type**
 - Cocoapods

**Additional context**

**Comment by Simerpal** [comment]
I am having this issue how do I solve it?

**Comment by Steveaxelrod007** [comment]
Same here, any way we can easily fix this?

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
