### ISSUE TITLE
About whether the height of the UI can be modified in the photo mode, do not want a square

### ISSUE THREAD

**Issue by Geoege-xll** [Yummypets/YPImagePicker#353]
About whether the height of the UI can be modified in the photo mode, do not want a square

**Comment by Vollando** [comment]
You might find this useful https://github.com/Yummypets/YPImagePicker/issues/176#issuecomment-444782670

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
