### ISSUE TITLE
Swift Complier Warnings on Swift 5.0

### ISSUE THREAD

**Issue by fishfisher** [Yummypets/YPImagePicker#354]
**Swift Compiler Warnings**

I have updated to latest version (5.0.0) and I am still seeing Swift Complier Warnings in regards to switch cases not handling _@unknown default_.
I am also seeing several compiler warnings in regards to SteviaLayout. I can see the YPImagePicker is referencing Stevia version 4.4.4 and not 4.5.0 (Swift 5 version) in the Podspec.

Am I missing something in my config or is this what others are seeing as well?

Keep up the good work!

Best regards,
Erik

**Environment:**

 - OS: macOS 10.14.4
 - Xcode Version: 10.2.1
 - Swift Version: 5.0

**Installation Type**
 - Cocoapods

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
