### ISSUE TITLE
no back button in the upper left corner, why ,please help me

### ISSUE THREAD

**Issue by kslowbullet** [Yummypets/YPImagePicker#355]
var config = YPImagePickerConfiguration()
        config.isScrollToChangeModesEnabled = true
        config.onlySquareImagesFromCamera = true
        config.usesFrontCamera = false
        config.showsPhotoFilters = false
        config.shouldSaveNewPicturesToAlbum = true
        config.albumName = "DefaultYPImagePickerAlbumName"
        config.startOnScreen = YPPickerScreen.library
        config.screens = [.video, .photo, .library]
        config.showsCrop = .none
        config.targetImageSize = YPImageSize.original
        config.overlayView = UIView()
        config.showsVideoTrimmer = false
        config.hidesStatusBar = false
        config.hidesBottomBar = false
        config.library.options = nil
        config.library.onlySquare = false
        config.library.minWidthForItem = nil
        config.library.mediaType = YPlibraryMediaType.photoAndVideo
        config.library.maxNumberOfItems = 1
        config.library.minNumberOfItems = 1
        config.library.numberOfItemsInRow = 4
        config.library.spacingBetweenItems = 1.0
        config.library.skipSelectionsGallery = false
        config.video.compression = AVAssetExportPresetHighestQuality
        config.video.fileType = .mp4
        config.icons.shouldChangeDefaultBackButtonIcon = true
        config.icons.backButtonIcon = UIImage(named: "back_icon")!
        let picker = YPImagePicker(configuration: config)
        picker.didFinishPicking { [unowned picker] items, _ in
            if let photo = items.singlePhoto {
                print(photo.image) // Final image selected by the user
            }
            picker.dismiss(animated: true, completion: nil)
        }
        present(picker, animated: true, completion: nil)

**Comment by NikKovIos** [comment]
If bug still exist - reopen with screenshot please.
