### ISSUE TITLE
YPImagePicker takes long time to open in demo!

### ISSUE THREAD

**Issue by brextonpham** [Yummypets/YPImagePicker#356]
Hi there!

I'm currently running the demo and when you press "Pick" it seems like it takes the picker 5-6 seconds to open! When I go into the example and remove ".video" from the config.screens line (on line 114 in showPicker()) it becomes exponentially faster. Is there a way to fix this as I think about using this? Please let me know, thank you!

**Comment by brextonpham** [comment]
To clarify — once the picker is brought up once is dismissed, it's super quick to pop up again when you  bring it up after it is loaded the first time

**Comment by gintechsystems** [comment]
Bug in Apple's CoreMotionManager:
https://stackoverflow.com/questions/54607856/main-thread-checker-warning-with-coremotion-only-appearing-on-2018-model-iphone

Workaround for now is to turn off Main Thread Checker for the scheme having the issue.

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
