### ISSUE TITLE
Main Thread Checker! Problem 

### ISSUE THREAD

**Issue by toygift** [Yummypets/YPImagePicker#357]
**Describe the bug**
Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 11892, TID: 2295184, Thread name: com.apple.CoreMotion.MotionThread, Queue name: com.apple.root.default-qos.overcommit, QoS: 0
Backtrace:
4   libobjc.A.dylib                     0x0000000234adf6f4 <redacted> + 56
5   CoreMotion                          0x000000023b259d9c CoreMotion + 294300
6   CoreMotion                          0x000000023b25a2cc CoreMotion + 295628
7   CoreMotion                          0x000000023b25a1dc CoreMotion + 295388
8   CoreMotion                          0x000000023b28801c CoreMotion + 483356
9   CoreMotion                          0x000000023b288060 CoreMotion + 483424
10  CoreFoundation                      0x000000023586e27c <redacted> + 28
11  CoreFoundation                      0x000000023586db64 <redacted> + 276
12  CoreFoundation                      0x0000000235868e58 <redacted> + 2276
13  CoreFoundation                      0x0000000235868254 CFRunLoopRunSpecific + 452
14  CoreFoundation                      0x0000000235868f88 CFRunLoopRun + 84
15  CoreMotion                          0x000000023b2879f4 CoreMotion + 481780
16  libsystem_pthread.dylib             0x00000002354e6908 <redacted> + 132
17  libsystem_pthread.dylib             0x00000002354e6864 _pthread_start + 48
18  libsystem_pthread.dylib             0x00000002354eedcc thread_start + 4
2019-05-31 15:23:10.633633+0900 SMUL_iOS[11892:2295184] [reports] Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 11892, TID: 2295184, Thread name: com.apple.CoreMotion.MotionThread, Queue name: com.apple.root.default-qos.overcommit, QoS: 0
Backtrace:
4   libobjc.A.dylib                     0x0000000234adf6f4 <redacted> + 56
5   CoreMotion                          0x000000023b259d9c CoreMotion + 294300
6   CoreMotion                          0x000000023b25a2cc CoreMotion + 295628
7   CoreMotion                          0x000000023b25a1dc CoreMotion + 295388
8   CoreMotion                          0x000000023b28801c CoreMotion + 483356
9   CoreMotion                          0x000000023b288060 CoreMotion + 483424
10  CoreFoundation                      0x000000023586e27c <redacted> + 28
11  CoreFoundation                      0x000000023586db64 <redacted> + 276
12  CoreFoundation                      0x0000000235868e58 <redacted> + 2276
13  CoreFoundation                      0x0000000235868254 CFRunLoopRunSpecific + 452
14  CoreFoundation                      0x0000000235868f88 CFRunLoopRun + 84
15  CoreMotion                          0x000000023b2879f4 CoreMotion + 481780
16  libsystem_pthread.dylib             0x00000002354e6908 <redacted> + 132
17  libsystem_pthread.dylib             0x00000002354e6864 _pthread_start + 48
18  libsystem_pthread.dylib    

It happen iphone xs,xs Max, xr
not 7,7s,8..etc not X version device

**Comment by gintechsystems** [comment]
Bug in Apple's CoreMotionManager:
https://stackoverflow.com/questions/54607856/main-thread-checker-warning-with-coremotion-only-appearing-on-2018-model-iphone

Workaround for now is to turn off Main Thread Checker for the scheme having the issue.

**Comment by toygift** [comment]
thx!!!
