### ISSUE TITLE
fromCamera not set correctly for video

### ISSUE THREAD

**Issue by Palando** [Yummypets/YPImagePicker#361]
**Describe the bug**
When I make a video then the fromCamera flag is set to false.

**To Reproduce**
1. Make a video

**Expected behavior**
The flag should have been set to true.

**Environment (please complete the following information):**
 - Device: iPhone 8 plus
 - OS: 12.x
 - Xcode Version 9.x
 - Swift Version [e.g. 4.1]

**Installation Type**
 - Cocoapods version 4.0.0

**Additional context**
I already found a fix:
add the parameter fromCamera to the YPMediaVideo in YPVideoFiltersVC in the function save():

...
DispatchQueue.main.async {
    let resultVideo = YPMediaVideo(
        thumbnail: strongSelf.coverImageView.image!,
        videoURL: destinationURL,
        fromCamera: strongSelf.inputVideo.fromCamera,
        asset: strongSelf.inputVideo.asset
    )
    didSave(YPMediaItem.video(v: resultVideo))
    strongSelf.setupRightBarButtonItem()
}
...

**Comment by ndemie** [comment]
This is still an issue. fromCamera is not being set when using a recorded video

**Comment by RoqueCampos** [comment]
+1 I'm having the same problem. A workaround is to check if the video.asset object is nil, but it would be nice to have this little bug corrected

**Comment by AndriiHanets** [comment]
+1

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
