### ISSUE TITLE
 I want the video preview get start in Picker page in original size

### ISSUE THREAD

**Issue by dizcloud** [Yummypets/YPImagePicker#362]
Thank you for your wonderful YPImagePicker, it helps me a lot.
And I get into a problem:
 I want the video preview get start in Picker page in original size, and I could not found the right code to modify.

**Comment by diegogarciar** [comment]
Hey, found a solution? 
I also need to provide this feature

**Comment by YogendraPatel** [comment]
@dizcloud @diegogarciar i also want this feature

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
