### ISSUE TITLE
how I get image file path

### ISSUE THREAD

**Issue by MourinhoLove** [Yummypets/YPImagePicker#363]

**Comment by mhmdzaid** [comment]
here is the answer : [ https://github.com/Yummypets/YPImagePicker/issues/258](url)

**Comment by mhmdzaid** [comment]
this extension will get the url of image but not for the one which  taken from camera

**Comment by MourinhoLove** [comment]
OK,Thank you.

**Comment by zhujiahong** [comment]
> this extension will get the url of image but not for the one which taken from camera

How can i get image URL from camera?
Please help Thank you!

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
