### ISSUE TITLE
Default Zoomout

### ISSUE THREAD

**Issue by roarapps** [Yummypets/YPImagePicker#365]
Thank you for this awesome library

Is it possible to have an option not to zoom in when the library loads?

**Comment by atilimcetin** [comment]
Also can we have an option to disable (hide) the zoom button?

**Comment by YogendraPatel** [comment]
@roarapps i want same functionality. if you find any solution then please help me.

**Comment by caspahouzer** [comment]
same here

**Comment by smedic** [comment]
@s4cha ?

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
