### ISSUE TITLE
I want to deselect when multiple selection mode by default

### ISSUE THREAD

**Issue by yokochi** [Yummypets/YPImagePicker#366]
**Is your feature request related to a problem? Please describe.**
In the current Multiple selection mode, the first image is selected.

**Describe the solution you'd like**
In Multiple selection mode I want the image to be deselected by default

**Comment by fdemircan** [comment]
Hello yokochi,
 
Remove the code from the defaultmultipleselect inside the YPLibraryVC;

```
func initialize() {
        /* In the current Multiple selection mode, get the first image is selected.
        if YPConfig.library.defaultMultipleSelection {
            multipleSelectionButtonTapped()
        }*/
}

```

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
