### ISSUE TITLE
ShotButton FlipButton FlashButton disappear

### ISSUE THREAD

**Issue by gaoweimaster** [Yummypets/YPImagePicker#368]
**Describe the bug**
In camera view FlipButton,FlashButton and ShotButton disappear
These buttons still work, just invisible 

Try add code  
    self.bringSubviewToFront(shotButton)   
in YPCameraView.swift, not works

How to fix it ? 
Thanks

![IMG_0116](https://user-images.githubusercontent.com/7658740/61180276-c5534100-a646-11e9-88f5-bc01ea2217bf.PNG)

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮

**Comment by gaoweimaster** [comment]
This is an automatic reply.I have received your letter and I will respond to it ASAP.Thank you very much.
