### ISSUE TITLE
Image Sizing question 

### ISSUE THREAD

**Issue by UtkuDalmaz** [Yummypets/YPImagePicker#373]
When I click to change the sizing button on YPImagePicker, it shows the original size of the image. But on Instagram, it shows a copped version of the image. 

I am uploading 2 images showing the results

### Instagram
![IMG_0326](https://user-images.githubusercontent.com/2130592/61541517-81967800-aa48-11e9-9d17-52e97bb532c2.jpg)

### YPImagePicker
![IMG_0327](https://user-images.githubusercontent.com/2130592/61541519-81967800-aa48-11e9-9252-130cd71d4b97.jpg)

Is there a way to change it like on Instagram?

**Comment by UtkuDalmaz** [comment]
Any idea on this question? @s4cha

**Comment by s4cha** [comment]
@UtkuDalmaz Mmm I see. I actually never noticed that instagram cropped pictures even after tapping the "sizing button". There is no way to change it like instagram at the moment unfortunately. If you can I'd be curious to know what rule they apply, is it a certain image ratio?

**Comment by UtkuDalmaz** [comment]
@s4cha I am sure it is a certain image ratio but I don't know exactly. The problem is that we use YPImagePicker to let our users share their stuff to our Instagram like feed, so when they tap "sizing button" of YPImagePicker it shows the full-size image and it looks too tall on the feed, I think that was also the reason Instagram doesn't use it at the full size.

**Comment by cclaflin89** [comment]
+1

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
