### ISSUE TITLE
Stuck while switching image to video and vice versa

### ISSUE THREAD

**Issue by midhun-tw** [Yummypets/YPImagePicker#379]
**Describe the bug**
When I am trying to switch from image mode to video mode the camera screen is stuck with the previous image instead of showing realtime camera view

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Xcode Version [e.g. 9.4.1]
 - Swift Version [e.g. 4.1]

**Installation Type**
 - Carthage
 - Cocoapods
 - Manual

**Additional context**

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
