### ISSUE TITLE
Move directly to Cover Image selection View Controller

### ISSUE THREAD

**Issue by SarathInno** [Yummypets/YPImagePicker#380]
I am trying to use a trim video & cover selection in a single view controller with two tabs.

I want to navigate to Cover selection View Controller & use its features alone without using gallery selection page.

I have attached my incomplete view Controller for reference & required view controller from YPImage Picker

**Required View Controller & Features**
![View Controller Required](https://user-images.githubusercontent.com/44698355/62546332-e9d6bd80-b880-11e9-8e00-b2bc6c5e234a.png)

**My Incomplete ViewController**
![Image from iOS](https://user-images.githubusercontent.com/44698355/62545913-3372d880-b880-11e9-8746-d15f9e2b981f.png)

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
