### ISSUE TITLE
Can you add a configuration: the setting can only select pictures or only select videos. 

### ISSUE THREAD

**Issue by miaoyuxuan** [Yummypets/YPImagePicker#381]
The first one selects pictures, the video is not optional. The first one selects the video, the picture is not optional.

**Comment by xyqjay** [comment]
want this tooooooooooo

But I feel I have to do it myself.

**Comment by s4cha** [comment]
@miaoyuxuan I am not sure I fully understand what your end goal is, could you please elaborate?

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
