### ISSUE TITLE
Video picker dismiss automatically  

### ISSUE THREAD

**Issue by cs14rendra** [Yummypets/YPImagePicker#382]
I want to pick only video from library. when I launch picker it dismiss automatically. It happen only when library is empty, means library do not have any video files. if I add some video files to library then it is working fine.

This is my configuration code.
>       var config = YPImagePickerConfiguration()
        config.library.mediaType = .video
        config.screens = [.library]
        config.library.maxNumberOfItems = 1
        config.showsVideoTrimmer = false
        config.video.libraryTimeLimit = Double.infinity
        config.library.minNumberOfItems = 0

If library is empty then picker should show some user friendly message or view.

**Comment by choiks14** [comment]
same here.

**Comment by YogendraPatel** [comment]
@bithavoc @appfabtech @heitara @ezisazis @Seepak  

i also get same issue. Please help me if anyone find solution.

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
