### ISSUE TITLE
Video Compression

### ISSUE THREAD

**Issue by ljs19923** [Yummypets/YPImagePicker#383]
Hi!
How can i have a compression between AVAssetExportPresetHighestQuality & AVAssetExportPresetMediumQuality please ?
The quality of medium quality is too low... But AVAssetExportPresetHighestQuality size is so big

Thanks

**Comment by s4cha** [comment]
Hi @JulienLevallois 

```swift
// Theses are just shortcuts
AVAssetExportPresetLowQuality
AVAssetExportPresetMediumQuality
AVAssetExportPresetHighestQuality

/* These export options can be used to produce movie files with the specified video size.
   The export will not scale the video up from a smaller size. The video will be compressed using
   H.264 (AVC) and the audio will be compressed using AAC.  Some devices cannot support some sizes. */
AVAssetExportPreset640x480
AVAssetExportPreset960x540
AVAssetExportPreset1280x720
AVAssetExportPreset1920x1080
AVAssetExportPreset3840x2160

// New HEVC (High Efficiency video coding) format:

AVAssetExportPresetHEVCHighestQuality
AVAssetExportPresetHEVCHighestQualityWithAlpha

/* These export options can be used to produce movie files with the specified video size.
   The export will not scale the video up from a smaller size. The video will be compressed using
   HEVC and the audio will be compressed using AAC.  Some devices cannot support some sizes. */
AVAssetExportPresetHEVC1920x1080
AVAssetExportPresetHEVC1920x1080WithAlpha
AVAssetExportPresetHEVC3840x2160
AVAssetExportPresetHEVC3840x2160WithAlpha
```

I suggest you experiment with these to find the compression you're happy with :)

PS: Please excuse the oh so long reply 😂

**Comment by StephanKornerTrihow** [comment]
Will there be a video compression change-feature in YPImagePicker soon ?

To clarify, I mean some sort of button or dropdown-menu for the user to change video compression while having the picker open. (very similar to Apple's native iPhone-Setting option (to be found under Camera Settings) called "Video Format Control" option - that eventually shows compression-quality right there where you need it, i.e. inside the camera app when recording a video.)

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
