### ISSUE TITLE
Front camera orientation

### ISSUE THREAD

**Issue by Cleversou1983** [Yummypets/YPImagePicker#385]
Hi there, I've a app with only portrait orientation, when use the lib to capture from front face camera, it not rotate the image, as happens with back camera... Is there a way to workaround this? Thanks a lot!!!

**Comment by StephanKornerTrihow** [comment]
Same here - YPImagePicker does not rotate the front-camera image correctly (as YPImagePicker does correctly with the rear-camera image).

Landscape with front-camera (acquired with "didFinishPicking" delegate method) does show correct width and height.

However, the photo.image (or photo.originalImage) delivered by "didFinishPicking" for Landscape-aquired fotos from front-camera are corrupt (90 degree rotated).

Can somebody please tell us how to overcome this problem ?

I am using an iPhoneX physical device, under iOS14.0.1 (working with release 43, XCode12)

**Comment by ngodacdu** [comment]
I am also facing the same problem.
I have debug and realized that after flip orientation is up, so image will not transform.
I try to fix, flip image after reset orientation. It looks like below:
```
DispatchQueue.main.async { [self] in
    let noOrietationImage = image.resetOrientation()
    // Flip image if taken form the front camera.
    if let device = self?.photoCapture.device,
       device.position == .front,
       let flippedImage = self?.flipImage(image: image) {
        image = flippedImage
    }
    self?.capturedPhotos.append(noOrietationImage.resizedImageIfNeeded())
}
```
But I think it should be done after the library is updated instead of doing it like above.

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
