### ISSUE TITLE
Customizing the Photo button area

### ISSUE THREAD

**Issue by J-L** [Yummypets/YPImagePicker#387]
Forgive me, I couldn't find anything in the docs.

Is there a way of hiding area below the photo /video preview (the white area with the capture button) in the config?

Thanks!

**Comment by J-L** [comment]
hmmm, found the set color customization.

Is it possible to set the camera preview height to the full size of the phone (minus the nav bars?)

**Comment by Clint1994** [comment]
How did you find the color customization for the photo button?

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
