### ISSUE TITLE
Fix build failing on Swift 5.1 (Xcode 11.0 beta 6 (11M392q))

### ISSUE THREAD

**Issue by kazukisugita** [Yummypets/YPImagePicker#388]
**Is your feature request related to a problem? Please describe.**
Yes. Which is fixing build failing on Swift 5.1. 
I found this great library couldn't build on carthage, even with `--no-use-binaries`.
So I forked and seeked problems. Just only changing `import`, I've checked correct build succeeded on Xcode 11.0 beta 6 (11M392q).

**Describe the solution you'd like**
Build Succeeded in Swift 5.1 (Xcode 11.0 beta 6 (11M392q))

**Additional context**
Here is solutions.
https://github.com/kazukisugita/YPImagePicker/commit/e1afc898229002f5d425c574cedece29af973387

**Comment by s4cha** [comment]
Hi @kazukisugita thanks for noticing and suggesting a fix, I think this has been fixed in the meantime :) Feel free to reopen if needed !
