### ISSUE TITLE
Video preview is not updated after selecting a new one

### ISSUE THREAD

**Issue by Sehyris** [Yummypets/YPImagePicker#389]
**Describe the bug**
While selecting a video from the picker, the old video preview appears behind the new selected video preview.

**To Reproduce**
1. Open YPImagePicker controller
2. Tap on Library tab
3. Select a video, change the selected video to another from the grid

**Expected behavior**
After selecting a new video from the grid the preview should only show the selected video.

**Screenshots**
![IMG_0128](https://user-images.githubusercontent.com/5171041/63784788-6838e500-c8ac-11e9-856d-ed6c75d480d7.PNG)

**Environment (please complete the following information):**
 - Device: iPhoneX
 - iOS 13 Beta
 - Xcode 11 Beta 6

**Installation Type**
 - Cocoapods

**Comment by YogendraPatel** [comment]
@Sehyris Same issue. please help me if you find any solution.

**Comment by Sehyris** [comment]
No solutions yet

**Comment by Sehyris** [comment]
@s4cha - are you able to reproduce this issue. Now I'm also seeing this:
<img width="512" alt="Screen Shot 2019-12-11 at 9 35 28 AM" src="https://user-images.githubusercontent.com/5171041/70635555-bffc2180-1bf9-11ea-91e6-6331f3b322be.png">

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
