### ISSUE TITLE
Feature request: multiple photo & video selection

### ISSUE THREAD

**Issue by nCr78** [Yummypets/YPImagePicker#39]
Would this be possible in a future release? 😃

**Comment by gasparuff** [comment]
Please! This library is so awesome, but if it had multiple asset selection, it would be unbeatable!!!

**Comment by s4cha** [comment]
@nCr78 @gasparuff @RobinBecker @tin612 @rumnat we are tracking this feature here : https://github.com/Yummypets/YPImagePicker/issues/10
