### ISSUE TITLE
iOS13 Support

### ISSUE THREAD

**Issue by Sehyris** [Yummypets/YPImagePicker#391]
Are you going to provide a new version with iOS13 support? We are having issues after selecting a video, the video preview is not updated correctly

**To Reproduce**
1. Open YPImagePicker controller
2. Tap on Library tab
3. Select a video, change the selected video to another from the grid

**Expected behavior**
After selecting a new video from the grid the preview should only show the selected video.

**Screenshots**

**Environment (please complete the following information):**
- Device: iPhoneX
- iOS 13 Beta
- Xcode 11 Beta 6

**Installation Type**
 - Cocoapods

**Additional context**
It is failing on my project and also on demo example from the repository.

**Comment by kasnitski** [comment]
The same for me. Does anybody tried to fix it?

**Comment by Sehyris** [comment]
@kasnitski , @s4cha can you provide any input here?

**Comment by akshay-shah-dev** [comment]
i am capturing video OS 12.2 but camera not open just display black screen.

**Comment by s4cha** [comment]
Hi @Sehyris The latest version supports iOS13 (dark mode and some fixes).
Concerning the "video preview is not updated correctly" This will hopefully be available later this week. iOS13 got us all very busy 😅

**Comment by s4cha** [comment]
@Sehyris could you check if your issue is solved in the latest version https://github.com/Yummypets/YPImagePicker/releases/tag/4.2.0 ?
Thanks

**Comment by Sehyris** [comment]
Thanks @s4cha. I'm able to see the iOS13 fixes, however, the video preview is not working properly (it is better than before, after some seconds the overlapping view is removed). After switching between videos I can see the previous video in front of the selected video. Please see the attached images. 
I'm using iPhone 8, OS 13.3 and library version 4.2.0.

<img width="551" alt="Screen Shot 2020-01-09 at 10 43 13" src="https://user-images.githubusercontent.com/5171041/72086673-ebdbf700-32cc-11ea-82b7-67026875773d.png">

<img width="551" alt="Screen Shot 2020-01-09 at 10 47 43" src="https://user-images.githubusercontent.com/5171041/72087032-89372b00-32cd-11ea-9735-d6f55072c141.png">

**Comment by s4cha** [comment]
@Sehyris Now I understand with the screenshot. I somehow thought preview was referring to the crop screen in which we had a known bug, my bad. This one shouldn't be to hard to fix. Will keep you posted :)
