### ISSUE TITLE
Image URL 

### ISSUE THREAD

**Issue by mhmdzaid** [Yummypets/YPImagePicker#392]
I cannot see the url for selected photo there is only url for video not for taken image or selected one

**Comment by EinfachHans** [comment]
+1

**Comment by Ludotrico** [comment]
@s4cha  @NikKovIos @heitara  This is quite a big issue, any updates?

**Comment by erickva** [comment]
I am using the latest version (4.5), some time after this conversation started and I still cannot see the `.url` property for gallery or camera images, it is always nil.

If you still need it, you could convert the image to data and store it in a local url:

```
let imgName = "\(UUID().uuidString).png"
let documentDirectory = NSTemporaryDirectory()
let localPath = documentDirectory.appending(imgName)
let data = photo.modifiedImage.pngData()! as NSData
data.write(toFile: localPath, atomically: true)
let url = URL.init(fileURLWithPath: localPath)
```

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
