### ISSUE TITLE
Unable to compile with Xcode11, wrong imports

### ISSUE THREAD

**Issue by jonnyarc** [Yummypets/YPImagePicker#395]
**Describe the bug**
Error compiling YPPhotoSaver.swift
PHCachingImageManager+Extensions.swift

**To Reproduce**
Open the main project and compile with Xcode 11 GM

**Expected behavior**
Compiles the framework

**Environment (please complete the following information):**
 - Device: MacBook Pro
 - OS: Mojave
 - Xcode Version 11.0 (11A420a)
 - Swift Version 5.1

**Installation Type**
 - Carthage

**Additional context**
Wrong imports, it should import UIKit instead of Foundation

**Comment by rbecharast-chwy** [comment]
Hi, I have a same issue. In my case the error is:
```Module compiled with Swift 5.0 cannot be imported by the Swift 5.1``` on ```import Stevia```

Thanks

**Comment by s4cha** [comment]
@jonnyarc @rodribech20 Swift 5.1 & Xcode 11 support was pushed in 4.1.2 on October 2. https://github.com/Yummypets/YPImagePicker/releases/tag/4.1.2
Are you still experiencing the issue?

**Comment by jonnyarc** [comment]
Thank you this issue was resolved.
