### ISSUE TITLE
Library video preview not completely scroll

### ISSUE THREAD

**Issue by YogendraPatel** [Yummypets/YPImagePicker#396]
**Describe the bug**
When i select video from library, that video has no scrolling completely in preview

**To Reproduce**
Select video from library

**Expected behavior**
Properly scroll in all side and perfect crop square video

**Screenshots**

**Environment (please complete the following information):**
 - Device: iPhone5s
 - OS: iOS10.3
 - Xcode Version 10.0
 - Swift Version 4.2

**Installation Type**
 - Cocoapods

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
