### ISSUE TITLE
Video in landscape not rotating to portrait mode.

### ISSUE THREAD

**Issue by mustafaqutbuddin** [Yummypets/YPImagePicker#398]
Video captured through camera stays in landscape mode and the orientation doesn't change.

![IMG_69378A6ACD9A-1](https://user-images.githubusercontent.com/13258829/65950268-2bd24900-e457-11e9-9e79-68153012f29d.jpeg)

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
