### ISSUE TITLE
camera issue

### ISSUE THREAD

**Issue by Zedd0202** [Yummypets/YPImagePicker#4]
Now that I've used the library, where's the button to take a picture on the camera screen?

**Comment by Zedd0202** [comment]
I received the icon, but it does not seem to apply.

**Comment by s4cha** [comment]
@Zedd0202,

Looks like there's an issue with resources and the cocoa pods integration.
I need to look into it. In the meantime, Carthage integration works fine :)

PS: Please excuse the late reply I was on holiday :)

**Comment by s4cha** [comment]
@Zedd0202 2.0.1 should fix your issue :)
