### ISSUE TITLE
Video Overlap issue.

### ISSUE THREAD

**Issue by Salmancs43** [Yummypets/YPImagePicker#400]
![WhatsApp Image 2019-10-03 at 6 05 00 PM](https://user-images.githubusercontent.com/23050315/66129215-e6557d80-e608-11e9-840d-f2b175158f05.jpeg)
Hi 
Thanks for amazing library. I am using the version 4.1.2 and I found one issue. When I select a video and after selection I select another video then the second video appears in the background of the first video in a  pause mode and first video is still there and play as it is. Red lines in the image show's the area of the first video.

**Comment by Sehyris** [comment]
I'm having the same issue... Please let me know if you find a workaround.

**Comment by dieptx** [comment]
How to padding `Cancel` and `Next` button in navigation bar with the edge ? Plz help me, thanks

**Comment by Sehyris** [comment]
@oTranXuanDiep - I'm not having that issue. But I saw your screenshot and looks like you are using the default presentation style, could you try with 'fullScreen' option?

**Comment by dieptx** [comment]
> @oTranXuanDiep - I'm not having that issue. But I saw your screenshot and looks like you are using the default presentation style, could you try with 'fullScreen' option?

@Sehyris I saw modalPresentationStyle set fullscreen when init with custom configuration at https://github.com/Yummypets/YPImagePicker/blob/53ac8ef10460f87d86c710db2b76b9e06a083086/Source/YPImagePicker.swift#L49 :(.

**Comment by Salmancs43** [comment]
> How to padding `Cancel` and `Next` button in navigation bar with the edge ? Plz help me, thanks

I didn't change anything in code for padding.

**Comment by Salmancs43** [comment]
> I'm having the same issue... Please let me know if you find a workaround.

Sure and let me know if you find any solution

**Comment by dieptx** [comment]
> > How to padding `Cancel` and `Next` button in navigation bar with the edge ? Plz help me, thanks
> 
> I didn't change anything in code for padding.

Ohhh. Thank you!!! I tried to override `viewWillAppear` of YPPickerVC and customize navigation bar so my issue was resolved.

**And how can i change double tap to select or deselect image to single tap when enable multiple selection images? That behavior likes images selection of Messenger app**

**Comment by Sehyris** [comment]
@Salmancs43 did you find any solution for this?

**Comment by boboxiaodd** [comment]
i think the reason is the secord video is from iCloud

**Comment by riazhazan** [comment]
@Salmancs43 Did you find a solution for this?

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
