### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by midhun-tw** [Yummypets/YPImagePicker#401]
**Describe the bug**
The app is not asking for gallery access permission

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Xcode Version [e.g. 9.4.1]
 - Swift Version [e.g. 4.1]

**Installation Type**
 - Carthage
 - Cocoapods
 - Manual

**Additional context**

**Comment by kira2015** [comment]
![image](https://user-images.githubusercontent.com/14231117/67667054-ff531380-f9a7-11e9-9160-8f3312a6a992.png)

**Comment by s4cha** [comment]
Hi @midhun-tw & @kira2015 this has been identified and will be fixed in the next version, hopefully next week.
Thanks a lot for your patience 🙏

**Comment by s4cha** [comment]
This has been fixed by https://github.com/Yummypets/YPImagePicker/pull/386 :)
