### ISSUE TITLE
Changing shot button icon does not change.

### ISSUE THREAD

**Issue by Clint1994** [Yummypets/YPImagePicker#402]
I'm trying to change the camera shot button from green to black. I've edited the button color, however when I try changing the icon image it stays the same ( green) every time.

` shotButton.setImage(YPConfig.icons.capturePhotoImage, for: .normal)`

`public var capturePhotoImage: UIImage = imageFromBundle("Capture")`

I changed the name from yp_iconCapture to "Capture" so I could use my own custom image. No luck..

**Comment by mlm249** [comment]
This way seemed to work for me

```
var config = YPImagePickerConfiguration()

...
        
// get capture icon from system icon
let newCapturePhotoImage = UIImage(systemName: "largecircle.fill.circle")?
  .imageWith(newSize: CGSize(width: 168, height: 168))
  .withTintColor(UIColor.label)
?? config.icons.capturePhotoImage
        
config.icons.capturePhotoImage = newCapturePhotoImage

...

let picker = YPImagePicker(configuration: config)
```

**Comment by Clint1994** [comment]
@mlm249  Thank you.

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
