### ISSUE TITLE
cancel button is black 

### ISSUE THREAD

**Issue by Skyb0rg** [Yummypets/YPImagePicker#405]
**Describe the bug**
After creating a new picker the cancel Button is black on black background.
All cancel buttons in the app are now black instead of Blue before.

**To Reproduce**
1. Open Picker
2. Click on not visible "cancel"

**Expected behavior**
dont change color of cancel button

**Environment (please complete the following information):**
 - Device: [e.g. alle iPhones]
 - OS: [ iOS 13.1.2]
 - Xcode Version [11.1]
 - Swift Version [ 5]

**Installation Type**
 - Cocoapods

**Comment by Skyb0rg** [comment]
OK found this in you code:

//If user has not customized the Nav Bar tintColor, then use black.
        ```
if UINavigationBar.appearance().tintColor == nil {
            UINavigationBar.appearance().tintColor  = .black
        }
```

i think this is the "Problem".
Why do you change it global?

**Comment by NikKovIos** [comment]
Fixed https://github.com/Yummypets/YPImagePicker/commit/6839864da946f9baa73fc1de5d4cdd9035ab5ab4
