### ISSUE TITLE
Dark mode customization

### ISSUE THREAD

**Issue by OlegZhuckovich** [Yummypets/YPImagePicker#407]
Thanks for wonderful lib! Are you planning to add dark mode support to the image picker?
It seems like on iOS 13 in dark mode some parts of the picker aren't black and I haven't the ability to customize them...

**Comment by s4cha** [comment]
Hi @OlegZhuckovich Dark mode is on its way for next version. @chrischute worked on it on https://github.com/Yummypets/YPImagePicker/pull/420 :)

**Comment by s4cha** [comment]
@OlegZhuckovich Dark mode is now supported in [4.1.3](https://github.com/Yummypets/YPImagePicker/releases/tag/4.1.3), let me know if that fits your needs :)

**Comment by OlegZhuckovich** [comment]
@s4cha, thanks, it looks wonderful in the last version!

**Comment by s4cha** [comment]
Glad you like it !
