### ISSUE TITLE
In iOS 13 the UI is different : is not full screen. How to fix it?

### ISSUE THREAD

**Issue by zhangfangtaozft** [Yummypets/YPImagePicker#408]
below iOS13 is like this:

![Simulator Screen Shot - iPhone XS Max - 2019-10-23 at 10 51 14](https://user-images.githubusercontent.com/11926205/67352663-27dfa580-f583-11e9-899d-86e5050f7d39.png)
But, in iOS 13 is like this:

![Simulator Screen Shot - iPhone Xs Max - 2019-10-23 at 10 55 05](https://user-images.githubusercontent.com/11926205/67352819-9f153980-f583-11e9-8310-4ab077f3cf5b.png)

but I want to show the page full screen, How can I do?

**Comment by Sehyris** [comment]
Hi @zhangfangtaozft , you just need to change the modal presentation style. Like this:
```
private func showImagePicker() {
	let picker = YPImagePicker(forVideo: true)
	picker.modalPresentationStyle = .overFullScreen
	picker.didFinishPicking { [unowned picker] items, _ in
	    print("\(items)")
	    picker.dismiss(animated: true, completion: nil)
	}
	self.present(picker, animated: true, completion: nil)
}

**Comment by zhangfangtaozft** [comment]
> Hi @zhangfangtaozft , you just need to change the modal presentation style. Like this:
> 
> ```
> private func showImagePicker() {
> 	let picker = YPImagePicker(forVideo: true)
> 	picker.modalPresentationStyle = .overFullScreen
> 	picker.didFinishPicking { [unowned picker] items, _ in
> 	    print("\(items)")
> 	    picker.dismiss(animated: true, completion: nil)
> 	}
> 	self.present(picker, animated: true, completion: nil)
> }
> ```

Thank you,the problem is solved!
