### ISSUE TITLE
Allow the camera to take multiple pictures

### ISSUE THREAD

**Issue by schveiguy** [Yummypets/YPImagePicker#413]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to capture multiple pictures from the camera I am aware of your answers in #172, but I think this is a possible way to achieve it (at least give the option for it).

**Describe the solution you'd like**
Provide a mechanism inside the callback to start the camera again. Right now, my only option is to dismiss the view controller. I'd like to be able to start the camera again. Then the shoot button can be used to capture another picture, and the callback called again. One exits by hitting cancel.

**Describe alternatives you've considered**
I need this functionality, as my app's use case is taking multiple pictures of a specific room. I don't want the user to have to re-tap the "take picture" button. I want him to be able to take pictures until he's satisfied.

**Additional context**

I made the following changes to my copy of your project:

```diff
diff --git a/Source/Pages/Photo/YPCameraVC.swift b/Source/Pages/Photo/YPCameraVC.swift
index 41ccf2b..dc75498 100644
--- a/Source/Pages/Photo/YPCameraVC.swift
+++ b/Source/Pages/Photo/YPCameraVC.swift
@@ -42,6 +42,7 @@ public class YPCameraVC: UIViewController, UIGestureRecognizerDelegate, YPPermis
     }
     
     func start() {
+        v.shotButton.isEnabled = true
         doAfterPermissionCheck { [weak self] in
             guard let strongSelf = self else {
                 return
diff --git a/Source/YPImagePicker.swift b/Source/YPImagePicker.swift
index fc22684..dd01186 100644
--- a/Source/YPImagePicker.swift
+++ b/Source/YPImagePicker.swift
@@ -158,6 +158,14 @@ override open func viewDidLoad() {
         loadingView.fillContainer()
         loadingView.alpha = 0
     }
+
+    public func restartCamera() {
+        picker.restartCamera()
+    }
 }
 
 extension YPImagePicker: ImagePickerDelegate {
diff --git a/Source/YPPickerVC.swift b/Source/YPPickerVC.swift
index f70e644..8a95aad 100644
--- a/Source/YPPickerVC.swift
+++ b/Source/YPPickerVC.swift
@@ -156,6 +156,12 @@ open class YPPickerVC: YPBottomPager, YPBottomPagerDelegate {
     func pagerDidSelectController(_ vc: UIViewController) {
         updateMode(with: vc)
     }
+
+    func restartCamera()
+    {
+        stopCurrentCamera()
+        cameraVC?.start()
+    }
     
     func updateMode(with vc: UIViewController) {
         stopCurrentCamera()
```

This of course is super-hacky, and works for my use case. But having correct support for it in the actual project would be very nice to use.

**Comment by asimrazakhan** [comment]
I wants to have two button on the image capture view, can you help me achieving this.

**Comment by schveiguy** [comment]
@asimrazakhan take a look at the code and see if you can duplicate the button setup. It shouldn't be too difficult. I'm happy with my hack for this, so not going to really put any more time into it.

**Comment by andreyyudin** [comment]
@asimrazakhan were you able to add another button or find an alternative library?

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
