### ISSUE TITLE
Moved & Zoomed photo in crop mode is moving when touching Done button

### ISSUE THREAD

**Issue by thierrybucco** [Yummypets/YPImagePicker#416]
When I touch Done button, cropped photo (moved) is moving before closing YPCropView.
Take a look at my recorded screen.

[RPReplay_Final1573103726.MP4.zip](https://github.com/Yummypets/YPImagePicker/files/3817969/RPReplay_Final1573103726.MP4.zip)

**Comment by s4cha** [comment]
@thierrybucco Wow this is very weird indeed. Can you reproduce the issue with the sample project provided? 
PS: please excuse the late reply 🙏

**Comment by cclaflin89** [comment]
The crop rectangle moves when tapping `Save` or `Cancel`. I tested in version 4.4.0

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
