### ISSUE TITLE
Missing Done Button

### ISSUE THREAD

**Issue by Emefar** [Yummypets/YPImagePicker#417]
<img width="402" alt="Screenshot at Nov 07 12-11-40" src="https://user-images.githubusercontent.com/36764954/68375844-a24e1f00-0158-11ea-8394-2f1e1f6710fe.png">

I cannot save photos. Video saving is working nice but not working save image. I am using Xcode 11.1 and i tried ios 13.1.2 and 13.1.3. How can i save selected image?

**Comment by jinjinbary** [comment]
This problem is due to ios 13.1 dark mode.
 inpo.list -> user interface style -> light
This solves the problem.

**Comment by Emefar** [comment]
I am not using dark mode. I am already using light mode. And i added light mode at info.plist but nothing changed. @jinjinbary If you fix problem, i can donate you.

**Comment by jinjinbary** [comment]
@Emefar sorry,
Before I run the above solution
Update xcode to 11.2 or 11.2.1 and rebuild project
This is all I can give

**Comment by Emefar** [comment]
@jinjinbary I am already building Xcode 11.2 and i updated phone os version to 13.2.2 but still i cannot see next icon. But when i pick select video, i can click next icon. And this is my picker func.

    func showPicker(){
        var config = YPImagePickerConfiguration()
        config.library.onlySquare = true
        
        let picker = YPImagePicker(configuration: config)
        picker.didFinishPicking { [unowned picker] items, _ in
            
            picker.dismiss(animated: true, completion: nil)
        }
        present(picker, animated: true, completion: nil) 
    }

**Comment by s4cha** [comment]
@Emefar do you experience this issue with the sample project `YPImagePickerExample` provided as well ?

**Comment by Emefar** [comment]
@s4cha YPImagePickerExample is working fine. And i created new project and YPImagePicker is worked fine too. But it is not working my project. I'm using you library, just i added new bottom button for done ;)

**Comment by RobSwish** [comment]
Could it be that you are setting the tint to white? 

`config.colors.tintColor` = .white

You may even be setting your tint globally for your whole app. 

`UINavigationBar.appearance().tintColor = .white`

Your nav is white, so you can't see it? I recommend using the "Debug view hierarchy" tool. You'll most likely see that the button is there as you can tap it, but it's the wrong colour.

**Comment by s4cha** [comment]
@Emefar I suggest you try the latest https://github.com/Yummypets/YPImagePicker/releases/tag/4.2.0 release. This probably fixes your issue along with other nice improvements. Let me know how this goes :)

**Comment by UtkuDalmaz** [comment]
I am having the same problem and I don't know how it happened. It just disappeared. It only happens in ios13 not ios12

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
