### ISSUE TITLE
ios13.1 can't find nextbutton in filterpage 

### ISSUE THREAD

**Issue by jinjinbary** [Yummypets/YPImagePicker#419]
ios 13.1
i can't find nextbutton in filterselectpage

**Comment by Emefar** [comment]
@NikKovIos Please answer. I cannot find too. I cannot save photos.

**Comment by jinjinbary** [comment]
This problem is due to ios 13.1 dark mode.
 inpo.list -> user interface style -> light
This solves the problem.

**Comment by NikKovIos** [comment]
The problem is because of color.

**Comment by s4cha** [comment]
@jinjinbary @Emefar Cant you try to reproduce your issue with the sample project from master? this should be fixed with the dark mode support coming in the next version :)

**Comment by Emefar** [comment]
@s4cha I think is not relevant dark mode. I am not using dark mode. Btw i am using force white mode.

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
