### ISSUE TITLE
How can I get both the original and cropped image?

### ISSUE THREAD

**Issue by relaxsus** [Yummypets/YPImagePicker#42]

**Comment by s4cha** [comment]
@relaxsus This is not possible at the moment but this should be pretty straightforward to implement.
I will let you know when this is available :)

**Comment by s4cha** [comment]
@relaxsus, Thinking about it, I am quite curious. If the user cropped their picture, why exactly do you need the original ? I am genuinely curious about the use case :)

**Comment by NikKovIos** [comment]
Good question. I don't either understand why it could be needed. Only to safe the original into the album, but there is already such a functional.

**Comment by s4cha** [comment]
@relaxsus Could you give us a bit more info about the use case? 
Thanks,

**Comment by relaxsus** [comment]
Customer requirements. Send to the server two pictures (original and cropped). I solved this question.

**Comment by NikKovIos** [comment]
@relaxsus How did you solved it?

**Comment by s4cha** [comment]
https://github.com/Yummypets/YPImagePicker/releases/tag/3.0.0 🎉

**Comment by s4cha** [comment]
@relaxsus 
`3.0.0` now has  `originalImage: UIImage` & `modifiedImage: UIImage?` which should solve your use case. The `originalImage` takes into account the crop made in the Library though.
Closing this for now, feel free to reopen :)

**Comment by zunjae** [comment]
Would it be possible to get the truly original image, not taking into account the crop? I've spent countless hours just to get the library to give me the actual image before crop.
