### ISSUE TITLE
What is the reason why YPPhotoFiltersVC's background color is red?

### ISSUE THREAD

**Issue by touyu** [Yummypets/YPImagePicker#421]
Hi, Thank you for the useful library.

Can YPPhotoFiltersVC's background color be changed by the user?
Why is it red by default?

**Comment by s4cha** [comment]
Hi @touyu,
Pretty unexpected that the view would be red. Do you experience this in the `YPImagePickerExample` sample project provided as well?
You can modify this via the `YPImagePickerConfiguration` object like so:
```swift
config.colors.filterBackgroundColor = .blue
```
Let me know if that works :)

**Comment by touyu** [comment]
It was fixed by commit of https://github.com/Yummypets/YPImagePicker/commit/9ac91d1d36617507bd05215273ff45ef90fdf007
Thank you .
