### ISSUE TITLE
How to convert a PHAsset object to YPMediaItem? Is there a way to do this?

### ISSUE THREAD

**Issue by rahulrvarma** [Yummypets/YPImagePicker#422]
Hi,

I have an object of PHAsset and want to covert that to an object of YPMediaItem because I have an array of YPMediaItem.
Need urgent help!!

Thanks in advance

**Comment by rahulrvarma** [comment]
Hi @s4cha @NikKovIos 
Please help on this. This is urgent. I have to launch the app and just waiting for this.
I am using - pod 'YPImagePicker', '~> 3.4.0' as the project does not supports above Swift 4.0

Thank you

**Comment by NikKovIos** [comment]
Hello! I don't remember if it supports the initialization with PHAsset in 3.4.0 version. If not, you can copy the cureent project and translate to swift 4 by yourself. In YPMediaItem you would find initializators with PHAsset.

**Comment by s4cha** [comment]
Hi @rahulrvarma I'm afraid`3.4.0` version didn't support initializing a `YPMediaItem` with a `PHAsset`. This is only supported in later versions. My best bet would be for you to integrate the library manually with the code so that you can edit it to your needs. 
Hope it helps

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
