### ISSUE TITLE
crop

### ISSUE THREAD

**Issue by midhun-tw** [Yummypets/YPImagePicker#423]
Please include option for users to crop their pictures with custom sizes with adjust crop height width with dragging

**Comment by mendesbarreto** [comment]
This feature will be very helpful.

**Comment by jensonjohn001** [comment]
+1 needed

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
