### ISSUE TITLE
Gap between navigation bar and collection view

### ISSUE THREAD

**Issue by TapanRaut** [Yummypets/YPImagePicker#424]
when i am navigatin to "YPSelectionsGalleryVC.swift" , there is a gap between navigation bar and collection view.

![Simulator Screen Shot - iPhone 8 Plus - 2019-11-20 at 02 02 34](https://user-images.githubusercontent.com/11292204/69273394-4a0a2900-0bfe-11ea-95b1-038060b29d77.png)

**Comment by s4cha** [comment]
@TapanRaut Could you give a bit more details about your setup so that we can reproduce it on our end please?

**Comment by TapanRaut** [comment]
Hi,

   Sorry for the late response. Actually when i am selecting more than one
image from library and clicking the next button. This type of error is
happening, If i will select only one image then no issue is there.Because
for only one image it navigating  me to the filterView.

 I am using xcode 11, swift 4.2, ios 13. Same problem also with ios 12 and
xcode 10. In iphone 5s it is working fine, but in iphone 8+, this type of
issue occurring. Same problem for simulator(iphone 8+ and 11 pro max). But
in 5s simulator it is working fine. I am using cocoapods.

Thanks & Regards

**Comment by Mattesackboy** [comment]
Same problem here

**Comment by s4cha** [comment]
Hi @TapanRaut & @Mattesackboy I am able to reproduce the issue when installing:
- Install 4.1.3 via Cocoapods or Carthage
- iPhone 8 plus simulator (iOS 13) (iOS 12 works fine)
- Somehow the bug is not there when testing with the `YPImagePickerExample` Project
 This is quite mysterious I am going to investigate and report back when I know more.

**Comment by s4cha** [comment]
Ok I found that the issue comes from `hidesStatusBar` config entry in iOS13.
Setting `config.hidesStatusBar = false` should solve your issue in the meantime :)

**Comment by s4cha** [comment]
This has been fixed and will be available in the next version (this week)

**Comment by s4cha** [comment]
This is now live in https://github.com/Yummypets/YPImagePicker/releases/tag/4.2.0 :)
