### ISSUE TITLE
Crash when selecting library

### ISSUE THREAD

**Issue by TapanRaut** [Yummypets/YPImagePicker#425]
When i am clicking on library button, the app crash.Getting fatal error.

at the following code i am getting the error: -
 var topHeight: CGFloat {
        get { return v.assetViewContainerConstraintTop.constant }
        set {
            if newValue >= v.assetZoomableViewMinimalVisibleHeight - v.assetViewContainer.frame.height {
                v.assetViewContainerConstraintTop.constant = newValue
            }
        }
    }

**Comment by s4cha** [comment]
Hi @TapanRaut Could you give me some more information on the environment, the more details the better:  Installation type (Carthage/cocoapods/ manually) Library version, Xcode Version etc.
Also are you able to reproduce the issue in the sample project provided as well ?  Thanks a lot in advance.

**Comment by s4cha** [comment]
Hi @TapanRaut is this still happening in the latest https://github.com/Yummypets/YPImagePicker/releases/tag/4.2.0 release ?
