### ISSUE TITLE
Turn on/off Multiselect by configuration

### ISSUE THREAD

**Issue by irosenb** [Yummypets/YPImagePicker#428]
I would love a way to turn on multiselect through the config object.

**Comment by s4cha** [comment]
@irosenb Could you describe in more details your use case please ?

**Comment by BossOz** [comment]
I think there is already this feature.
I'm using this
```
pickerConf.library.maxNumberOfItems = allowMultipleSelection ?? false ? 5 : 1
pickerConf.library.minNumberOfItems = 1
```
This is working for me.
Hope this help.

**Comment by jinthislife** [comment]
By setting defaultMultipleSelection as true or false, you can turn it on or off.

For example,

    var config = YPImagePickerConfiguration()
    config.library.defaultMultipleSelection = true
    config.library.maxNumberOfItems = 10

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
