### ISSUE TITLE
How to use in Swift5.2

### ISSUE THREAD

**Issue by gu0315** [Yummypets/YPImagePicker#429]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Xcode Version [e.g. 9.4.1]
 - Swift Version [e.g. 4.1]

**Installation Type**
 - Carthage
 - Cocoapods
 - Manual

**Additional context**

**Comment by s4cha** [comment]
@gu0315 Swift 5.2 is not officially released yet so it's not supported at the moment. could you explain why you need Swift 5.2 at the moment ?

**Comment by s4cha** [comment]
@gu0315 have you tried the latest release 4.2.0 
https://github.com/Yummypets/YPImagePicker/releases/tag/4.2.0 ?

**Comment by Abhishek224** [comment]
The support from stevia has been removed from pod for higher versions of swift.
So just this can be fixed by integrating stevia as a package dependency solution to the project. this fixes it all.

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
