### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by NikKovIos** [Yummypets/YPImagePicker#43]
let imageOutput = AVCaptureStillImageOutput()
![2018-03-06 22 01 21](https://user-images.githubusercontent.com/16647690/37052296-f168e080-2189-11e8-8abe-07a097303062.png)
let data = AVCaptureStillImageOutput.jpegStillImageNSDataRepresentation(buffer!)
`'AVCaptureStillImageOutput' was deprecated in iOS 10.0: Use AVCapturePhotoOutput instead`
v.flashButton.setImage(flashImage(forAVCaptureFlashMode: device.flashMode), for: .normal)
`'flashMode' was deprecated in iOS 10.0: Use AVCapturePhotoSettings.flashMode instead.`

**Comment by s4cha** [comment]
@NikKovIos Nice catch, YPImagePicker's target is still 9.0 at the moment to remain inclusive but as soon as we drop iOS 9 I'm all for changing to the new apis. What do you think?

**Comment by NikKovIos** [comment]
It would be necessary to fix them sooner or later. But people use this lib and already get this errors. Why not to fix it now so.

**Comment by s4cha** [comment]
@NikKovIos Sure, `AVCapturePhotoOutput` won't be available in iOS 9 so we'll need to have both in parallel for a while. When we finally drop iOS9 we'll just have to remove the  ` if #available(iOS 10.0, *)` clause. Sooner is better yep :)

**Comment by NikKovIos** [comment]
Yes)

**Comment by s4cha** [comment]
OK @NikKovIos I started researching and experimenting with AVCapturePhotoOutput today and I'll push the first code changes for discussion on a branch tomorrow :)

**Comment by s4cha** [comment]
@NikKovIos I guess we can close this now that 2.8.0 is out :)

**Comment by NikKovIos** [comment]
Yeah!

**Comment by 5fcgdaeb** [comment]
I see that there is the `PreiOS10PhotoCapture` class inside the Pod (4.4.0 version) and that still spits out multiple warnings. The actual issue is closed but the warnings will always remain with this approach.

Just figured out that XCode doesn't provide any means to silence these warnings. All good!
