### ISSUE TITLE
Appearance() break the colors in all the app in which the library is added

### ISSUE THREAD

**Issue by gaetano78** [Yummypets/YPImagePicker#430]
In the file YImagePicker.swift, the lines:

 if UINavigationBar.appearance().tintColor == nil {
          UINavigationBar.appearance().tintColor  = .black
  }

Break the UI of my app, as the line  "UINavigationBar.appearance().tintColor  = .black" change the color of backbutton in all my navigation controllers. I think you should not use appearance, as it is a global things. In my case, I just commented the line and made some changes to my code, but commenting the line could not be the solution in every case.

Thanks anyway for the wonderful library!

Thanks

**Comment by s4cha** [comment]
@gaetano78 thanks a ton for reporting this serious issue 🙏. Will let you know once a fix is issued

**Comment by s4cha** [comment]
@gaetano78 This is now fixed in https://github.com/Yummypets/YPImagePicker/releases/tag/4.2.0
