### ISSUE TITLE
Fatal error when picking recently deleted photo from  library

### ISSUE THREAD

**Issue by jakubradzik** [Yummypets/YPImagePicker#432]
**Describe the bug**
When picking photo from library and switching app to system gallery app I delete the photo I just picked with the picker. The list below picked image updates but the photo itself doesn't disappear. When clicking 'next' button app crashes - 403 line of YPLibraryVC class - fatalError() in guard let.
Is there a way to commit the crash?

**To Reproduce**
1. Open picker
2. Select photo from gallery
3. Go to iOS photo gallery app
4. Deleted photo You picked in picker in your app
5. Click next button in picker
6. App crashes

**Expected behavior**
Change the selected photo to the most recent one (deleted one is still displayed)

**Environment (please complete the following information):**
 - Device: [iPhoneXR]
 - OS: [iOS 13.1.3]
 - Xcode Version [11.1]
 - Swift Version [4.2]

**Installation Type**
 - Cocoapods

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
