### ISSUE TITLE
White screen shown on camera view of video recorder.

### ISSUE THREAD

**Issue by Hitesh0321** [Yummypets/YPImagePicker#433]
**To Reproduce**
by tapping on video option from bottom some works fine but some shows white screen on camera portion.
![WhatsApp Image 2019-12-18 at 12 09 19 AM](https://user-images.githubusercontent.com/28647621/71024617-531de580-212b-11ea-8dd5-9467d22e5194.jpeg)

**Environment (please complete the following information):**
 - Device: iPhone7
 - OS: iOS13.2
 - Xcode Version 11.1
 - Swift Version 4.2

**Installation Type**
 - Cocoapods

**Comment by s4cha** [comment]
Thanks for reporting this will be tracked here: https://github.com/Yummypets/YPImagePicker/issues/404
