### ISSUE TITLE
Default to iOS13 system icons

### ISSUE THREAD

**Issue by RobSwish** [Yummypets/YPImagePicker#434]
I'd like to suggest defaulting to the new iOS13 icon provided by Apple when they are available and if the icons have not been overridden. They look great and there's an icon for everything.

**Comment by s4cha** [comment]
Hi @RobSwish That is definitely a road we want to take. We have to support previous versions so this would only be available for iOS13 devices. I'm quite busy at the moment but feel free to take a crack at it with a PR :)

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
