### ISSUE TITLE
Report bug : Remove image not working

### ISSUE THREAD

**Issue by metawin99** [Yummypets/YPImagePicker#438]
**Describe the bug**
removeImage  in YPSelectionsGalleryVC nor working

**To Reproduce**
1. Go to 'Gallery'
2. Click on Pick image.'
3. delete image
4. not working

**Environment (please complete the following information):**
 - Device: [e.g. iPhoneX]
 - OS: [e.g. iOS12.2]
 - Xcode Version [e.g. 11.3]
 - Swift Version [e.g. 5]

**Installation Type**
 - Cocoapods
 - Manual

**Comment by app-arianamini** [comment]
Replace this method in YPSelectionsGalleryVC with:

`    @objc
    private func removeButtonDidClick(sender: UIButton) {
        guard let cell = sender.superview?.superview as? UICollectionViewCell, let indexPath = v.collectionView.indexPath(for: cell) else {
            return
        }
        items.remove(at: indexPath.row)
        v.collectionView.performBatchUpdates({
            v.collectionView.deleteItems(at: [indexPath])
        }, completion: { [weak self] _ in
            guard let `self` = self else { return }
            if self.items.isEmpty {
                self.navigationController?.popViewController(animated: true)
            }
        })
    }`

**Comment by app-arianamini** [comment]
Replace this method in YPSelectionsGalleryVC with:

```
@objc private func removeButtonDidClick(sender: UIButton) { 
    guard let cell = sender.superview?.superview as? UICollectionViewCell, 
    let indexPath = v.collectionView.indexPath(for: cell) else { 
        return 
    } 

    items.remove(at: indexPath.row) v.collectionView.performBatchUpdates({ 
        v.collectionView.deleteItems(at: [indexPath]) 
    }, completion: { [weak self] _ in 
        guard let `self` = self else { return } 
        if self.items.isEmpty { 
            self.navigationController?.popViewController(animated: true) 
        } 
    }) 
}
```

**Comment by s4cha** [comment]
@metawin99  thanks for noticing and letting us know :) @app-arianamini Thanks for issuing a fix !

**Comment by s4cha** [comment]
This has just been fixed on master and will be available later today :)

**Comment by s4cha** [comment]
This is now live in https://github.com/Yummypets/YPImagePicker/releases/tag/4.2.0
