### ISSUE TITLE
showsVideoInLibrary

### ISSUE THREAD

**Issue by pngo-hypewell** [Yummypets/YPImagePicker#44]
How to scroll up/down with rectangle video in library

**Comment by s4cha** [comment]
@pngo-hypewell I'm not sure I understand well, you would like to crop videos into squares right?
Unfortunately, this feature is not implemented, at least yet :)

**Comment by pngo-hypewell** [comment]
@s4cha  Thanks for your reply.
I mean in YPImagePicker screen, the scroll is disable when I load a video from Library. The video preview is square, so in case I load a rectangle video, the bottom is lost. Is it possible for me to enable scroll to see any part of video ?
It doesn't happen when I load a image.

**Comment by s4cha** [comment]
Alright indeed the preview being square, parts of the video is lost when previewing.
As you might have seen, the output video will still be the correct though, uncropped.
This looks like a very welcome addition :) I am going to look at what it implies in terms of code and will keep you posted.

**Comment by s4cha** [comment]
@pngo-hypewell would an aspect fit preview work for you ? No scroll but white banners in the case of a rectangle video. The scroll would seem misleading since the library doesn't crop videos.

**Comment by s4cha** [comment]
![img_0470](https://user-images.githubusercontent.com/1812953/37103965-c6e9f37e-222b-11e8-8a7b-16b72474ca33.PNG)

that would look like this

**Comment by s4cha** [comment]
The fix is in the starting blocks here https://github.com/Yummypets/YPImagePicker/pull/45/files :)

**Comment by pngo-hypewell** [comment]
@s4cha: thanks so much for your quick fix.
The crop videos into squares is also a perfect feature at this time. Hope you guys can implement it soon. Someone made it in PryntTrimmerView
https://github.com/prynt/PryntTrimmerView

**Comment by s4cha** [comment]
@pngo-hypewell your fix is now available in 2.7.2 https://github.com/Yummypets/YPImagePicker/releases/tag/2.7.2
Concerning the video crop we're going to track this in a new issue, thanks a ton for you help :)
