### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by mkals** [Yummypets/YPImagePicker#440]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mkals** [comment]
Hello, any chance of making this package available for installation through the new Swift Package Manager?

**Comment by s4cha** [comment]
Hi @mkals Unfortunately Swift Package manager doesn't (yet) support resources, such as images xibs, or .strings files for translations. One hacky way would be to put all the resources files in the source code: 
- Transform xibs to pure code (easy and desirable)
- Find a way to use translations via code (no strings files)
- Replace images by code generated assets (via paint code for example)
Considering the number of changes required, I decided to wait for SPM to support resources, which hopefully should come in the near future.

**Comment by mkals** [comment]
Thanks a lot for your answer, it makes a lot of sense to wait under these circumstances! Hopefully, support for resources is added soon. Thanks!
