### ISSUE TITLE
Video Recording Not working , switching the tab

### ISSUE THREAD

**Issue by taimoorsuleman** [Yummypets/YPImagePicker#441]
**Describe the bug**
Video Recording Not working, switching the tab
**To Reproduce**
1. Open Picker
2. Click on Video button , to record video
3. Click on Photo Button
4. Now again click on Video Button, Start Video recording, But Buttons updates but video recording not started

**Expected behavior**

**Comment by s4cha** [comment]
Thanks for reporting this will be tracked here: https://github.com/Yummypets/YPImagePicker/issues/404

**Comment by userSV** [comment]
Have you got any fix for this issue? I am facing the same issue randomly.

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
