### ISSUE TITLE
shot button/record button are hidden on iOS 12 in the latest version (4.1.3)

### ISSUE THREAD

**Issue by rbecharast-chwy** [Yummypets/YPImagePicker#442]
**Describe the bug**
I updated to latest version (from 4.1.2 to 4.1.3) the shot button and record button disappeared on photo/video tabs for iOS 12. In iOS 13 is working. 

**Screenshots**
![IMG_5439](https://user-images.githubusercontent.com/823023/72000592-669c0800-3222-11ea-97c1-5e1f64e2566f.PNG)
![IMG_5438](https://user-images.githubusercontent.com/823023/72000594-669c0800-3222-11ea-8dfd-833b65798aa2.PNG)

**Environment:**
 - Device: iPhone X
 - OS: iOS 12.3.1
 - Xcode Version 11.2.1
 - Swift Version 5

**Comment by rbecharast-chwy** [comment]
Also I could not see the rotate camera button and flash button. Thanks

**Comment by NikKovIos** [comment]
There is 2022 year outside🎉 Old outdated issues are closing. Please search if there are already existing issues with the same problem before opening new ☮
