### ISSUE TITLE
A working model in SwiftUI please !

### ISSUE THREAD

**Issue by TilakMaddy** [Yummypets/YPImagePicker#456]
I am always frustrated when it comes to integrating pre-made Swift projects into Swift UI projects because the code always seems to break.

I want a working model that I can call in SwiftUI directly like ...
`YummyPets(config: config) 
      .onPickedItems { items in
              ......
             ......
      }
`

As an alternative , I tired creating a struct extending `UIViewControllerRepresenable` and failed miserably that I have posted github issue [here](https://github.com/Yummypets/YPImagePicker/issues/455) 

#455

**Comment by DJDrama** [comment]
I've successfully implemented picker in swiftui by looking at the issue you mentioned.
Just using state and binding variables, we can get the selected image from the uirepresentable.

**Comment by TilakMaddy** [comment]
Wow ! 🤩  that was so quick mate 🥇 :)

**Comment by DJDrama** [comment]
@TilakMaddy 1 year has past. time moves fast

**Comment by denzeltinashe** [comment]
> @TilakMaddy 1 year has past. time moves fast

lmao, 2 years

**Comment by TilakMaddy** [comment]
> > @TilakMaddy 1 year has past. time moves fast
> 
> lmao, 2 years

its not Feb yet, so more like 11 months ...
