### ISSUE TITLE
Picker is dismissed automatically if noPhoto even though user can always take a picture!

### ISSUE THREAD

**Issue by carmelogallo** [Yummypets/YPImagePicker#458]
Hey guys!

I've just faced which I think is a wrong user experience. In case the device has no photo the picker is automatically dismissed even though I have set the picker with the possibility to take a photo with the camera. 

I just add this work around in`YPPickerVC` replacing `noPhotosForOptions()` method with the follow one:
```swift
public func noPhotosForOptions() {
    guard (!controllers.contains { return $0 is YPCameraVC || $0 is YPVideoCaptureVC }) else {
        self.imagePickerDelegate?.noPhotos()
        return
    }

    self.dismiss(animated: true) {
        self.imagePickerDelegate?.noPhotos()
    }
}
```

Hope I can find it in the next release!!!

**Comment by 1262068532** [comment]
Hi I also noticed this issue, however your above code doesn't work. Any suggestions?

**Comment by carmelogallo** [comment]
For me it is working. No clue why for you doesn't.

**Comment by sharjeelahmed** [comment]
@cikpis did you find the solution ? . the above code doesn't work for me as well

**Comment by NikKovIos** [comment]
https://github.com/Yummypets/YPImagePicker/releases/tag/5.2.1 should fix this.
