### ISSUE TITLE
i want to select multiple picture from library.

### ISSUE THREAD

**Issue by Afrah-Tayyab** [Yummypets/YPImagePicker#460]
want to select multiple picture from library.

i want to select multiple pictures from library and as given code in the example i am doing same. i.e

            for item in items {
                switch item {
                case .photo(let photo):
                    print(photo)
                    
 ------------->  self.imagesList.append((photo.asset?.image)!)
the code infant of arrow making an issue that asset as no member image. i want to get images and assign to the array of images.

**Comment by h3x22** [comment]
I also have the same problem, can u help me ? @s4cha

**Comment by NikKovIos** [comment]
Check the last version please.
