### ISSUE TITLE
Black space on video after recorded via YPImagePicker

### ISSUE THREAD

**Issue by UtkuDalmaz** [Yummypets/YPImagePicker#465]
I have a problem when a video recorded via YPImagePicker, check this video please 

https://drive.google.com/open?id=1p7dBU6w-i_VE8adQPscO0tinV0Sh5yqW

There is a strange black space under the video and it is not in expected sizes

**Comment by OmegaWulf** [comment]
I'm seeing the same issue.

**Comment by UtkuDalmaz** [comment]
Anyone here? @s4cha

**Comment by dillonsvincent** [comment]
I'm also experiencing this only with videos taken with YPPicker, It looks like it's cutting off the top portion of the video. It not only does this in the trim preview but also in the final video as well.

**Comment by cwestMobile** [comment]
Plus one!

**Comment by fantasma10** [comment]
Plus one!

**Comment by fantasma10** [comment]
Plus one!

**Comment by UtkuDalmaz** [comment]
I guess this project is no longer maintained

**Comment by Amang-dezhi** [comment]
Find this line of code:         
let t1 = CGAffineTransform(translationX: clipVideoTrack.naturalSize.height, y: -(clipVideoTrack.naturalSize.width - clipVideoTrack.naturalSize.height) / 2)

and change it to:
        let t1 = CGAffineTransform(translationX: clipVideoTrack.naturalSize.height, y: 0)

**Comment by UtkuDalmaz** [comment]
> Find this line of code:
> let t1 = CGAffineTransform(translationX: clipVideoTrack.naturalSize.height, y: -(clipVideoTrack.naturalSize.width - clipVideoTrack.naturalSize.height) / 2)
> 
> and change it to:
> let t1 = CGAffineTransform(translationX: clipVideoTrack.naturalSize.height, y: 0)

Thanks It worked!

**Comment by Amang-dezhi** [comment]
> > Find this line of code:
> > let t1 = CGAffineTransform(translationX: clipVideoTrack.naturalSize.height, y: -(clipVideoTrack.naturalSize.width - clipVideoTrack.naturalSize.height) / 2)
> > and change it to:
> > let t1 = CGAffineTransform(translationX: clipVideoTrack.naturalSize.height, y: 0)
> 
> Thanks It worked!

I think, if
"YPConfig.onlySquareImagesFromCamera" is true, then 
let t1 = CGAffineTransform(translationX: clipVideoTrack.naturalSize.height, y: -(clipVideoTrack.naturalSize.width - clipVideoTrack.naturalSize.height) / 2)
is right; when it's false, then we should use:
let t1 = CGAffineTransform(translationX: clipVideoTrack.naturalSize.height, y: 0)

**Comment by UtkuDalmaz** [comment]
@s4cha can you please update the project with this fix?

**Comment by NikKovIos** [comment]
https://github.com/Yummypets/YPImagePicker/issues/528
Fixed 46abe69
