### ISSUE TITLE
Func defaultMultipleSelection not working

### ISSUE THREAD

**Issue by metawin99** [Yummypets/YPImagePicker#467]
**Describe the bug**
set confix app
config.library.defaultMultipleSelection = true

**To Reproduce**
1. Go camera

**Expected behavior**
multiple selection show default

**Screenshots**

**Environment (please complete the following information):**
 - Device: [e.g. iPhoneX]
 - OS: [e.g. iOS12]
 - Xcode Version [e.g. 11.3]
 - Swift Version [e.g. 5]

**Installation Type**
 - Manual

**Additional context**

**Comment by jinthislife** [comment]
Did you set maxNumberOfItems as well?
For example, 

        var config = YPImagePickerConfiguration()
        config.library.defaultMultipleSelection = true
        config.library.maxNumberOfItems = 10
