### ISSUE TITLE
Add SPM Support

### ISSUE THREAD

**Issue by Ganesh623** [Yummypets/YPImagePicker#469]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zrfrank** [comment]
Upvote for SPM support!

**Comment by s4cha** [comment]
Hi, Swift package manager support is one of the main goals on the roadmap.
At the moment SPM does not support resources in packages (xibs/fonts/images).
I have to check if there is a way to bypass this limitation until SPM supports resources, which is on their roadmap. Until then we need to be patient :)

**Comment by andr-ec** [comment]
Xcode 12 now includes the latest SPM which allows us to include resources! Any timeline for SPM in this project? Thanks!

**Comment by NikKovIos** [comment]
https://github.com/Yummypets/YPImagePicker/releases/tag/5.0.0
