### ISSUE TITLE
Black video from library after compress

### ISSUE THREAD

**Issue by brhoomjs** [Yummypets/YPImagePicker#474]
**Describe the bug**
Some .MP4 videos selected from the library sent by WhatsApp. After select it turned fully black with audio.
![IMG_5496](https://user-images.githubusercontent.com/12615977/78600301-c3c84980-7863-11ea-9559-988f79bc539b.PNG)

**Environment**
 - Device: [iPhone 11 Pro]
 - OS: [13.4]
 - Xcode Version [11.4]
 - Swift Version [5.0]

**Installation Type**
 - Cocoapods

**Comment by xxKRASHxx** [comment]
The same, not only for the WhatsApp , but for edited videos from gallery.

**Comment by xxKRASHxx** [comment]
@brhoomjs  have you tried on a real device? Seems the issue reproduces only on a simulator

**Comment by LeenaTekani** [comment]
Same issue faced when I tried to pick the boomerang videos with 3 second

**Comment by nastasiupta** [comment]
@xxKRASHxx  This issue happens on a real device as well.
I have the same issue with the compression.
Here is a video that I received on WhatsApp:
https://drive.google.com/file/d/1bHEs-iUAS-qPYFiqOeHKFm0aZyBxJEso/view?usp=sharing

**Comment by brhoomjs** [comment]
> @brhoomjs have you tried on a real device? Seems the issue reproduces only on a simulator

For all devices with all versions.

**Comment by turk-jk** [comment]
I have the same problem with real devices. Mainly I have seen it to happen in videos that were recorded on Android device. not always. but very frequently with this set up.

**Comment by brhoomjs** [comment]
> I have the same problem with real devices. Mainly I have seen it to happen in videos that were recorded on Android device. not always. but very frequently with this set up.

Thanks :)
