### ISSUE TITLE
Xcode 11.4

### ISSUE THREAD

**Issue by ArmyXomuiL** [Yummypets/YPImagePicker#475]
Cannot build by Xcode 11.4.
Xcode 11.2 - all ok on the same code.

<img width="980" alt="Снимок экрана 2020-04-16 в 02 23 56" src="https://user-images.githubusercontent.com/8521655/79398483-777ab900-7f89-11ea-9d36-65bd60660e07.png">

**Comment by Abhishek224** [comment]
Any updates on this ??

**Comment by s4cha** [comment]
This is an annoying problem happening when using pre-built frameworks, here via Carthage.
What happens is that Carthage frameworks were built with a different version of Xcode (there are so many out there !). A useful command to know is `carthage update [LibName] --no-use-binaries`, which builds the Carthage dependency with the local version of Xcode :).
In our case we need to do
```
carthage update Stevia --no-use-binaries
carthage update PryntTrimmerView --no-use-binaries
```
This should solve the build, let me know if that worked on your side :)

**Comment by s4cha** [comment]
I just pushed the fix with libraries built with latest Xcode (11.5)

**Comment by Abhishek224** [comment]
The support from stevia has been removed from pod for higher versions of swift.
So just this can be fixed by integrating stevia as a package dependency solution to the project. this fixes it all.

**Comment by s4cha** [comment]
Yep indeed, @Abhishek224 can you confirm that Cocoapods supports embedded Swift Package manager dependencies? If so this is a no-brainer indeed :)

**Comment by s4cha** [comment]
We need to make sure this works with Carthage as well. I am going to experiment and will report back !

**Comment by s4cha** [comment]
@Abhishek224 PryntTrimmerView does not support SPM at the moment, and it has embedded resources, which prevents adding support. On simple solution might be to manually link it.

**Comment by Abhishek224** [comment]
Agreed to the approach, though once I would to like to play around that as well. Will post here if any updates

**Comment by s4cha** [comment]
Libs have been updated for Xcode 11.6, closing this for now, we'll track the rest in separate issues.
