### ISSUE TITLE
How can i display the picker with some set of images selected?

### ISSUE THREAD

**Issue by userSV** [Yummypets/YPImagePicker#476]
I am displaying the picker and when the user selects some images and then dismiss the picker, I want to present the picker again with the last images selected as pre-selected on picker. Does the current functionality supports it? or is there any approach to do that.

**Comment by s4cha** [comment]
@userSV this is supported via the `config.library.preselectedItems = selectedItems` in the ExampleProject.
However it seems like there is a bug (at least in 4.3.0) version

**Comment by s4cha** [comment]
`config.library.preselectedItems` should work fine as of 4.3.1, let me know how it goes :)
