### ISSUE TITLE
Next button disable by default 

### ISSUE THREAD

**Issue by aaparth** [Yummypets/YPImagePicker#477]
**Describe the bug**
When the gallery view is open and the first image is selected then at that time the Next Button is disabled as it should be enabled.

**To Reproduce**
Check the attached image

**Expected behavior**
Next button should be enabled by default

**Screenshots**

[https://drive.google.com/file/d/1f4KMI5RxpyDnbP3PXCL0gPXoUWJyn9Su/view?usp=sharing](url)

**Environment:**
 - Device: iPhone11
 - OS: iOS 13.4.1
 - Xcode Version XCode 11.3.1
 - Swift Version 5

**Installation Type**
 - Cocoapods

**Comment by s4cha** [comment]
@aaparth Good catch, could you share your config please? On my side it looks like the suspect is ` config.library.preselectedItems`

**Comment by s4cha** [comment]
This should be fixed in 4.3.1, let me know :)

**Comment by aaparth** [comment]
> @aaparth Good catch, could you share your config please? On my side it looks like the suspect is ` config.library.preselectedItems`

@s4cha 

here is my config

        var config = YPImagePickerConfiguration()
        config.shouldSaveNewPicturesToAlbum = false
        config.startOnScreen = .library
        config.screens = [.library, .photo, .video]
        config.showsPhotoFilters = true
        config.showsVideoTrimmer = true
        config.maxCameraZoomFactor = 2.0
        
        config.video.compression = AVAssetExportPresetMediumQuality//AVAssetExportPreset640x480
        config.video.fileType = .mp4//.mov
        config.video.recordingTimeLimit = 600.0
        config.video.minimumTimeLimit = 3.0
        config.video.trimmerMaxDuration = 600.0
        config.video.libraryTimeLimit = 600.0
        config.video.trimmerMinDuration = 3.0
        config.library.mediaType = .photoAndVideo
        config.library.maxNumberOfItems = 10 - self.arrImages.filter{$0.isServer == true}.count
        config.library.minNumberOfItems = 1
        config.library.isSquareByDefault = false
        config.gallery.hidesRemoveButton = false
        config.targetImageSize = .original
        config.library.preselectedItems = selectedYPItems
        let YPPicker = YPImagePicker(configuration: config)
