### ISSUE TITLE
Crash in YPLibraryVC.multipleSelectionButtonTapped() 

### ISSUE THREAD

**Issue by keyhan76** [Yummypets/YPImagePicker#478]
**Environment (please complete the following information):**
 - Device: iPhone 7 Plus
 - OS: 13.3.1
 - Xcode Version 11.4.0
 - Swift Version 5.2

**Installation Type**
 - Cocoapods

**Additional context**
There is no additional log file. Just got this crash report in Crashlytics and it's on line 149 of YPLibraryVC.swift .

**Comment by NikKovIos** [comment]
Sorry, it's not enough info to fix it. Thanks for your time :)
