### ISSUE TITLE
Additions and changes in LIB (Discussion)

### ISSUE THREAD

**Issue by NikKovIos** [Yummypets/YPImagePicker#48]
I've created this issue in order to tell what i did updated for my project. And maybe something of this could be extracted to the public api.

Strings:
- All `ypLocalized` strings.

Images:  
- arrow.image = imageFromBundle("arrow_down_dotted")
- videoStartImage = imageFromBundle("record")
- videoStopImage = imageFromBundle("record_on")
- v.flipButton.setImage(imageFromBundle("rotate"), for: .normal)

Different:
- alignHorizontally(label-arrow)
- Camera buttons layout (but this is specail case)
- Don't hide status bar
- Color of the selected items (multiple selection image and in right top corner)

**Comment by s4cha** [comment]
@NikKovIos 
Having an api entry point to change images and texts sounds like a good addition to me.
The last three bullet points might be more delicate to have a customisation entry point for but I'; not against it per se.
If you have already done such a thing, would you mind issue a Pull request?
Thank you so much for your involvement in the project so far, you rock!

**Comment by s4cha** [comment]
@NikKovIos as discussed together I'm going to start with the text customisation on the `textCustomization` branch, I'll have you review it once done :)

**Comment by NikKovIos** [comment]
#47

**Comment by NikKovIos** [comment]
> What do you think about add a feature which allowing us to draw (or blur) on the image we just took.
> If i want to hide something on the image for example, like a face or some text.

https://github.com/Yummypets/YPImagePicker/issues/91

**Comment by NikKovIos** [comment]
Got to look at `YPHelpers.swift` and rebase this functions from global to YPHelpers struct. Because global functions is a bad practice.

**Comment by NikKovIos** [comment]
Should move the video fetching to the last step and async, because when selecting big video, the interface is unnecessary holding.

**Comment by s4cha** [comment]
@NikKovIos can we close this ?

**Comment by NikKovIos** [comment]
Yes
