### ISSUE TITLE
Recorded portrait video is rotated on selection

### ISSUE THREAD

**Issue by ManuelEMR** [Yummypets/YPImagePicker#483]
After choosing a recorded portrait video, the video's thumbnail is getting rotated, also when I try to upload this video anywhere else it's also rotated.

Why is this happening or how can I disabled it?

**Comment by cimonk** [comment]
I have this problem too.
Could any one help us?

Updated:
I found the point, if it set as below, it will get the wrong orientation video
> config.video.compression = AVAssetExportPresetPassthrough

But if it set as below, it will get the correct orientation video
> config.video.compression = AVAssetExportPreset640x480

or
> config.video.compression = AVAssetExportPresetMediumQuality

Is your problem same with it?

**Comment by latheesh9796** [comment]
I have this problem as well. Is there anything that can be done?

**Comment by mikebryant71** [comment]
@s4cha 
Hey, I've been having this issue too, tested on iPhone X - iOS 13.5.1
### Steps to reproduce: 
1. Take a video in portrait with the camera app
2. Open up YPImagePicker in library mode
3. Select recorded video.
4. Video will be oriented the wrong way


 I found a fix based off the AVMutableVideoComposition documentation

Adding `videoCompositionTrack.preferredTransform = transform` on line 119 in LibraryMediaManager.swift

https://developer.apple.com/library/archive/qa/qa1744/_index.html
> Important: If you export a video composition with an AVAssetExportSession object and specify the AVAssetExportPresetPassthrough export preset to let all tracks pass through, the transform defined in the video composition instruction (AVMutableVideoCompositionLayerInstruction) will not be applied. You must change the export preset to one that defines a video format (AVAssetExportPresetMediumQuality, for example) for the transform to be applied.
> 
> Otherwise, if you specify the AVAssetExportPresetPassthrough export option to let all tracks pass through but you still want to set a transform on the composition, **set the preferredTransform property on the composition tracks** as described above.

**Comment by riazhazan** [comment]
I do have the same issue. Any Solutions so far?

**Comment by riazhazan** [comment]
> @s4cha
> Hey, I've been having this issue too, tested on iPhone X - iOS 13.5.1
> 
> ### Steps to reproduce:
> 1. Take a video in portrait with the camera app
> 2. Open up YPImagePicker in library mode
> 3. Select recorded video.
> 4. Video will be oriented the wrong way
> 
> I found a fix based off the AVMutableVideoComposition documentation
> 
> Adding `videoCompositionTrack.preferredTransform = transform` on line 119 in LibraryMediaManager.swift
> 
> https://developer.apple.com/library/archive/qa/qa1744/_index.html
> 
> > Important: If you export a video composition with an AVAssetExportSession object and specify the AVAssetExportPresetPassthrough export preset to let all tracks pass through, the transform defined in the video composition instruction (AVMutableVideoCompositionLayerInstruction) will not be applied. You must change the export preset to one that defines a video format (AVAssetExportPresetMediumQuality, for example) for the transform to be applied.
> > Otherwise, if you specify the AVAssetExportPresetPassthrough export option to let all tracks pass through but you still want to set a transform on the composition, **set the preferredTransform property on the composition tracks** as described above.

Yes. This worked for me also. This can be merged to master and deploy.
