### ISSUE TITLE
Avoid compression

### ISSUE THREAD

**Issue by DanielZanchi** [Yummypets/YPImagePicker#484]
Is there any way to avoid video compression?

I only need to get the thumbnail of a video, the compression is slow and I will not use the video anyway.

**Comment by hezhez** [comment]
I was looking also for an answer to this issue, how can i skip compression ?

**Comment by nastasiupta** [comment]
I have the same issue with the compression.
Here is a video that I received on WhatsApp:
https://drive.google.com/file/d/1bHEs-iUAS-qPYFiqOeHKFm0aZyBxJEso/view?usp=sharing

**Comment by nastasiupta** [comment]
@s4cha  @NikKovIos  any thoughts on this guys :)? For a recorded video of 1 minute, it takes about 30-35  seconds to fetch...

**Comment by NikKovIos** [comment]
By now there are no functional to avoid compression. I think it should be an enum to select what type we need. But without compression we can not crop.

**Comment by s4cha** [comment]
Hi @DanielZanchi @hezhez @nastasiupta 
I think th option you're looking for is:
```swift
config.video.compression = AVAssetExportPresetPassthrough
```
as per the Apple documentation states
```swift
/* This export option will cause the media of all tracks to be passed through to the output exactly as stored in the source asset, except for
   tracks for which passthrough is not possible, usually because of constraints of the container format as indicated by the specified outputFileType.
   This option is not included in the arrays returned by -allExportPresets and -exportPresetsCompatibleWithAsset. */
```
I tried on my side with a big video and it seems to do the trick. It will also bypass crop since it gives the raw video. It is not instantaneous for long videos but it seems to be 10x faster than when using compression presets. 
Let me know if that works on your side :)

**Comment by s4cha** [comment]
@DanielZanchi have you been able to try out `AVAssetExportPresetPassthrough` ?

**Comment by DanielZanchi** [comment]
> @DanielZanchi have you been able to try out `AVAssetExportPresetPassthrough` ?

Yes. It works fine

**Comment by nastasiupta** [comment]
> @DanielZanchi have you been able to try out `AVAssetExportPresetPassthrough` ?

Yes, works fine with AVAssetExportPresetPassthrough ;)

**Comment by ralspatel** [comment]
Why there are delays if I pick 2 videos and tap on the next button
