### ISSUE TITLE
Order is not respected when selecting multiple video

### ISSUE THREAD

**Issue by tony-halloapp** [Yummypets/YPImagePicker#488]
If multiple selection is enabled and multiple videos are selected (ie. 10 videos) the order in which they are selected are not respected in didFinishPicking

Note: The ordering for images work fine

**Comment by Ludotrico** [comment]
I agree, I wonder why this is the case?

**Comment by heitara** [comment]
I’ll investigate this and get back to you. Could be something minor.

**Comment by Ludotrico** [comment]
Ok keep me updated and lmk if I can help.

> I’ll investigate this and get back to you. Could’ve something minor.

**Comment by Ludotrico** [comment]
@heitara @mendesbarreto @s4cha Any ideas? Multiple selection that incorporates images and videos scrambles the order.

**Comment by heitara** [comment]
@Ludotrico could you share exact steps. For example: open example app. Pick 5 images and 5 videos. The order is 2v,2i,3i... expected order is 1i,2i,3i...

**Comment by tony-halloapp** [comment]
If there are 5 images and 5 videos and the picked order is
1v, 2v, 3v, 4v, 5v, 1i, 2i, 3i, 4i, 5i
the expected order should be the same but it almost never end up that way, especially if the videoes are large

guessing that it could be when a large video is selected it takes time to either transpose the video or just put it into the array so if the user picks an image or smaller video right after, that item gets done first and gets put into the array earlier

**Comment by heitara** [comment]
I found the problem. @tony-halloapp @Ludotrico  could you guys check the following version using the sample project? https://github.com/Yummypets/YPImagePicker/pull/533 
You can find a working version here - https://github.com/heitara/YPImagePicker/tree/feature/issue-488

**Comment by Ludotrico** [comment]
@heitara thank you for investigating! I just pasted your changes in my project that is currently running the up to date version of the master. Unfortunately the problem persists. Images seem to always be placed before videos, disregarding order.

https://youtu.be/LonRlghD8-w

@tony-halloapp same on your end?

**Comment by NikKovIos** [comment]
@heitara Does https://github.com/Yummypets/YPImagePicker/pull/533 fix that?

**Comment by heitara** [comment]
@NikKovIos exactly. The sort function keeps the selection order "stable".

**Comment by NikKovIos** [comment]
@heitara so 488 mr i can close?

**Comment by heitara** [comment]
Yes, please.
