### ISSUE TITLE
Module compiled error

### ISSUE THREAD

**Issue by CivelXu** [Yummypets/YPImagePicker#489]
Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2.2 compiler: /Users/civelxu/Downloads/YPImagePicker-master/Carthage/Build/iOS/Stevia.framework/Modules/Stevia.swiftmodule/x86_64.swiftmodule

**Comment by Abhishek224** [comment]
The support from stevia has been removed from pod for higher versions of swift.
So just this can be fixed by integrating stevia as a package dependency solution to the project. this fixes it all.

**Comment by Haibo-Zhou** [comment]
I get the same issue, so how could I fix this?

**Comment by Abhishek224** [comment]
For now you may add stevia as a dependency in SPM to get it ongoing.

**Comment by Haibo-Zhou** [comment]
> For now you may add stevia as a dependency in SPM to get it ongoing.

Thx, it is fixed, however there is another one - "Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2.2 compiler: /Users/Chuck/Downloads/YPImagePicker-master/Carthage/Build/iOS/PryntTrimmerView.framework/Modules/PryntTrimmerView.swiftmodule/x86_64.swiftmodule".

It seems that PryntTrimmerView has no SWP support now.

**Comment by Abhishek224** [comment]
Yes the PryntTrimmerView has no SPM support, you can add it manually to get it working.. I did not had much of need for prynt trimmer framework.. so

**Comment by Haibo-Zhou** [comment]
> Yes the PryntTrimmerView has no SPM support, you can add it manually to get it working.. I did not had much of need for prynt trimmer framework.. so

Noted! I want to have a run on the example project of YPImagePicker to see what it is worked like. And to decide if I use it or native Core Image. Well, I care about only images effect too:) So I may try to remove the prynt trimmer things from example code.

**Comment by s4cha** [comment]
Hi, please see https://github.com/Yummypets/YPImagePicker/issues/475

**Comment by NikKovIos** [comment]
https://github.com/Yummypets/YPImagePicker/releases/tag/5.0.0
