### ISSUE TITLE
in version 2.7.1 the status bar disappear on all iphones but iphone x

### ISSUE THREAD

**Issue by MehdiBrandoMahdloo** [Yummypets/YPImagePicker#49]

**Comment by s4cha** [comment]
@MehdiMahdloo Good catch! I guess hiding the status bar made sense to leave more room for the rest of the UI.  iPhone X having the notch, hiding the status bar would'nt have such a benefit.
Actually, Instagram keeps it too on iPhone X's. 
Let me know what you think :)

**Comment by MehdiBrandoMahdloo** [comment]
I think you should make it optional for all devices.
Not every UI gets well with a View where the status bar completely disappears.
It’s just a suggestion but it may help someone :)

**Comment by s4cha** [comment]
@MehdiMahdloo I like the idea of an opt out feature, definitely makes sense, and shouldn't be too hard to implement.
I'll let you know when there's news on this front :)

**Comment by MehdiBrandoMahdloo** [comment]
Thank you so much. I’ve found a quick “turn around” trick.
In my app i’ve removed the ability of a view to manage the status bar (in my plist), and set a global status bar in AppDelegate.
But it may be useful to have the option to make it disappear or appear, based on the UI you have. Anyway, thank you :)

**Comment by s4cha** [comment]
@MehdiMahdloo thanks for your time and ideas! I'm going to take a look and will let you know if there's related news :)

**Comment by s4cha** [comment]
@MehdiMahdloo You can now set `config.hidesStatusBar = false` to prevent the status bar from hiding starting 2.7.3  https://github.com/Yummypets/YPImagePicker/releases/tag/2.7.3

Hope this helps :)

**Comment by MehdiBrandoMahdloo** [comment]
I’ve updated the library yesterday. It’s great to see you’ve introduced the possibility to set the status bar.
Thank you so much and keep on the great job. :)

**Comment by s4cha** [comment]
@MehdiMahdloo  Thanks for the kind words! can we close this ?

**Comment by MehdiBrandoMahdloo** [comment]
Definitely
