### ISSUE TITLE
Wrong NavigationBar layout in iOS 13 with "card" presentation style

### ISSUE THREAD

**Issue by carmelogallo** [Yummypets/YPImagePicker#491]
Hey guys, 

as described in the title, I get a wrong navigation bar layout in iOS when I present the picker not in fullscreen. 

See attached picture:
![IMG_74588BA1AB4D-1](https://user-images.githubusercontent.com/895478/82754625-70d43280-9dce-11ea-9084-8e36c79bfcf3.jpeg)

The weird part is that with an iPhone with top notch like iPhone X or 11 I don't have the problem. It only occurs on iPhone with iOS 13 and model without top notch so previous of iPhone X.

Any clue of what is going on?

**Comment by glaphi** [comment]
Did you set modalPresentationStyle = .fullScreen 
before presenting this controller?

**Comment by carmelogallo** [comment]
No because the whole point is to have it with the new iOS 13 presentation style. And as I said, works perfectly on iPhone X, Xr, Xs and 11. 

I guess something is off in the way you handle the layout. I’d check there :)

**Comment by NikKovIos** [comment]
Show your code how you present picker. Also check the example - i test it on iPhoneSE and it works well.

**Comment by ljs19923** [comment]
@cikpis did you find a solution ? I have the same problem.. with my ios 13, iphone 11 pro

**Comment by carmelogallo** [comment]
My mistake was that I was presenting the picker inside another UINavigationController :)

**Comment by carmelogallo** [comment]
I'm closing this and sorry for not doing this before, cheers!

**Comment by ljs19923** [comment]
@cikpis what do you mean ? Because i have the same error, and i dont find any solutions

**Comment by carmelogallo** [comment]
@JulienLevallois https://github.com/Yummypets/YPImagePicker/issues/491#issuecomment-649533935

**Comment by ljs19923** [comment]
The bug appears if the viewcontroller which presents the picker is itself a viewcontroller presenting, so it's really weird. I dont understand how to resolve that


I have this flow : 

NavigationController1 -> VC1 -> present with formSheet style -> VC2 -> present with formSheet style -> YPImagePicker

In this case I have the bug…

If I have this flow : 

NavigationController1 -> VC1 -> present with formSheet style -> YPImagePicker

I don’t have the bug

And with this last flow, I don’t have the bug too 

NavigationController1 -> VC1 -> pushViewcontrller -> VC2 -> present with formSheet style -> YPImagePicker

@cikpis
