### ISSUE TITLE
Option to remove the photo preview in library for easier multiple selection

### ISSUE THREAD

**Issue by justColbs** [Yummypets/YPImagePicker#495]
**Describe the solution you'd like**
The selected photo preview when viewing Library can take up a lot of space. I would love to be able to remove that so that all the photos will fill the view and multiple selection will be faster and easier. 

Would this be considered if I submitted a PR for it?

**Comment by s4cha** [comment]
@justColbs, this has been asked before https://github.com/Yummypets/YPImagePicker/issues/481. I'm all for it! If you can issue a PR that would be amazing 😍

**Comment by justColbs** [comment]
@s4cha Got it! I'm not able to submit a PR at the moment, but would love to see it. Sorry for the duplicate!
