### ISSUE TITLE
Memory issue for 4k 60fps video (5min ~1GB)

### ISSUE THREAD

**Issue by nastasiupta** [Yummypets/YPImagePicker#498]
**Describe the bug**
I have one video recorded before, using an iPhone 11 (4K 60 FPS video length about 5 mins and 30 seconds).
Works fine with small videos (2mins)

**To Reproduce**
1. Go to 'Camera' app
2. Switch to Video and select 4K and 60FPS (default is HD and 30FPS)
2. Record a video ... 5 mins (
3. Open your app, add media (video)
4. Select the video that you recorded.
5. After a while, the app crashes with this the following debug logs:
This happens right after I select the video:
2020-06-03 14:55:18 [GatekeeperXPC] Connection to assetsd was interrupted - assetsd exited, died, or closed the photo library
This happens after SDK video processing:
2020-06-03 15:02:35 [AVAsset loadValuesAsynchronouslyForKeys:completionHandler:] invoked with unrecognized keys (
    size
).
Message from debugger: Terminated due to memory issue

**Expected behavior**
No crash... 

**Screenshots**
-

**Environment (please complete the following information):**
 - Device: iPhone 11 
 - OS: 13.4.1
- SDK version: 4.2.1
 - Xcode Version: Version 11.4.1 (11E503a)
 - Swift Version: 5

**Installation Type**
 - Cocoapods

**Additional context**
-

**Comment by s4cha** [comment]
This is discussed in https://github.com/Yummypets/YPImagePicker/issues/484
