### ISSUE TITLE
Crash on `YPImagePickerConfiguration()`

### ISSUE THREAD

**Issue by keyhan76** [Yummypets/YPImagePicker#509]
After updating to latest version of library from version 4.0.0, it crashes on 'YPImagePickerConfiguration()'.
Xcode Version: 11.5 (11E608c)
Swift: 5.2
iOS: 13.5

**Comment by szdkkk** [comment]
TRY to clean your project and rebuild. I met this problem when upgrading from 4.2.1 to 4.3.1

**Comment by keyhan76** [comment]
@szdkkk ok sure,thanks👍🏻
