### ISSUE TITLE
Black screen when Video tab selected

### ISSUE THREAD

**Issue by IhorChernysh** [Yummypets/YPImagePicker#512]
Hello!
The problem is - when switching the tabs, the screen is black when selected 'Video' tab. Any ideas about it?

**Comment by tarasChernysh** [comment]
I have the same problem. I see that if I used to `attachmentConfig.screens = [.library, .video]` then video recording worked as expected. But when I use `attachmentConfig.screens = [.library, .photo, .video]` then video recording don't work - I see either black screen or frosen screen. Could anybody help me please?

**Comment by BhavikWings** [comment]
I have also same problem. When I switching from .photo to .video then blank screen appears but when I am switching between .library to .video then it will work. Could anybody help me please?

**Comment by nickeyzzz** [comment]
Made a pull request for this, but some attention of creators required.

**Comment by NikKovIos** [comment]
Please check last release and reopen if still can reproduce with description of concrete steps to reproduce :)
