### ISSUE TITLE
viewwillappear  not called when dismiss picker

### ISSUE THREAD

**Issue by fukemy** [Yummypets/YPImagePicker#517]
hello, i have notification register in viewwillappear class (my Viewcontroller), then destroy it on viewwilldisapper. But i checked when show present picker -> viewwilldisapper called, but when dismiss -> viewwillappear not called. Can you help me know the problem?

**Comment by heitara** [comment]
I guess, you face this on iOS 13. This is related to the new VC behavior. You should read more about different workarounds - https://stackoverflow.com/questions/56568967/detecting-sheet-was-dismissed-on-ios-13

Please, close the issue if this helps you to solve your problem.

**Comment by fukemy** [comment]
worked now thanks
