### ISSUE TITLE
Handle the Limited Photos Library (WWDC 20 Update) 

### ISSUE THREAD

**Issue by andreyyoshua** [Yummypets/YPImagePicker#519]
**Is your feature request related to a problem? Please describe.**
We got an update from WWDC20 that we need to handle limited photos library in our app like it is said on this video https://developer.apple.com/videos/play/wwdc2020/10652/

**Describe the solution you'd like**
Please provide the solution for new permission to handle this Limited Photo library in iOS 14 above

**Comment by roarapps** [comment]
Yes Please!!

**Comment by NikKovIos** [comment]
Added 89acc4c3bea687f53e7b05a9adab08153f158721
