### ISSUE TITLE
Incompatible Swift version 5.2

### ISSUE THREAD

**Issue by data-augur** [Yummypets/YPImagePicker#520]
HI,
The framework is not compatible with swift 5.2. I am currently on swift 5.2 and unable to use it.

**Comment by heitara** [comment]
@data-augur what exactly is the problem? Which part is not working, could you be a bit more specific?

**Comment by timothyerwin** [comment]
@heitara it doesn't build on xcode 12

**Comment by heitara** [comment]
Ok. I'll check it.

**Comment by s4cha** [comment]
@data-augur are you still having the issue? If so could you detail a bit more please?

**Comment by heitara** [comment]
I've checked the latest master and it builds fine using iOS 14. Anything wrong on your end?
