### ISSUE TITLE
Add Support to add library through Swift Dependency Manager and Update Read.me file respectively.

### ISSUE THREAD

**Issue by HananMehmood5** [Yummypets/YPImagePicker#526]

**Comment by s4cha** [comment]
Hi, this is definitely something that we want to support. We have resources that prevented us to use SPM.
This might change soon with the advancements of SPM (binary support for example)

**Comment by s4cha** [comment]
This is already tracked here: https://github.com/Yummypets/YPImagePicker/issues/469
