### ISSUE TITLE
Video has a black bar at the bottom when "config.onlySquareImagesFromCamera = false"

### ISSUE THREAD

**Issue by solomonkim2002** [Yummypets/YPImagePicker#528]
**Describe the bug**
Video has a black bar at the bottom when "config.onlySquareImagesFromCamera = false"

**To Reproduce**
1. set config.onlySquareImagesFromCamera = false
2. Take a video with the camera
3. On the trim video/choose cover page, the video has a black bar attached below it
4. The black bar does not disappear

**Expected behavior**
The video should play perfectly fine without a black bar below it.

**Screenshots**
![Screenshot 2020-07-24 at 1 58 50 AM](https://user-images.githubusercontent.com/63892321/88375950-588e7e80-cd51-11ea-83fc-d7795ca5ee81.png)

**Environment (please complete the following information):**
 - Device: [e.g. iPhone8]
 - OS: [e.g. iOS13.0]

**Installation Type**
 - Cocoapods

**Additional context**

**Comment by VishalSharma91** [comment]
@BballerKim facing same issue, any update on it?
I think there was white UI on the top of it which is transparent after config.onlySquareImagesFromCamera = false, and getting in middle of recording! @s4cha any help here?

**Comment by solomonkim2002** [comment]
@VishalSharma91 I was unable to find a solution, were you? @NikKovIos any advice by any chance

**Comment by alimirzamani** [comment]
I have the same problem. Should we wait for an update?

**Comment by NikKovIos** [comment]
Fixed 46abe699ec11a7d32898f3cddb64d98fee32e8cf
