### ISSUE TITLE
video not open

### ISSUE THREAD

**Issue by AnkitGhoniya** [Yummypets/YPImagePicker#534]
i have set below code to open video recording but open default "Library & photo" as per below ss.

CODE: 
@IBAction func btnCameraClicked(_ sender: UIButton) {
        
        var config = YPImagePickerConfiguration()
        // [Edit configuration here ...]
        // Build a picker with your configuration
        let picker = YPImagePicker(configuration: config)
        
        config.video.compression = AVAssetExportPresetHighestQuality
        config.video.fileType = .mov
        config.video.recordingTimeLimit = 60.0
        config.video.libraryTimeLimit = 60.0
        config.video.minimumTimeLimit = 3.0
        config.video.trimmerMaxDuration = 60.0
        config.video.trimmerMinDuration = 3.0
        
       /* Multiple media implementation */
        picker.didFinishPicking { [unowned picker] items, cancelled in
            
            if cancelled {
                print("Picker was canceled")
                picker.dismiss(animated: true, completion: nil)
                return
            }
            _ = items.map { print("🧀 \($0)") }
            
            self.selectedItems = items
            for item in items {
                switch item {
                case .photo(let photo):
                    print(photo)
                case .video(let video):
                    print(video)
                   
                }
            }
            picker.dismiss(animated: true, completion: nil)
        }
      
        present(picker, animated: true, completion: nil)
}
![WhatsApp Image 2020-08-06 at 1 25 07 AM](https://user-images.githubusercontent.com/17406081/89457905-bffdf280-d783-11ea-96a4-ecca3815483d.jpeg)

**Comment by s4cha** [comment]
Hi @AnkitGhoniyam you need to set
```swift
 config.screens = [.library, .photo, .video]  /* Defines which screens are shown at launch, and their order. Default value is `[.library, .photo]` */
```
