### ISSUE TITLE
Memory overhead

### ISSUE THREAD

**Issue by VitaliiDeveloper** [Yummypets/YPImagePicker#535]
**Describe the bug**
If in your library would be a large image like:
https://eoimages.gsfc.nasa.gov/images/imagerecords/73000/73751/world.topo.bathy.200407.3x21600x21600.C1.png
App gonna be terminate!

**To Reproduce**
Download image to the library:
https://eoimages.gsfc.nasa.gov/images/imagerecords/73000/73751/world.topo.bathy.200407.3x21600x21600.C1.png
Let the YPImagePicker open it in the list of images

**Environment (please complete the following information):**
 - Device: XS MAX
 - OS:  ios 13.6
 - Xcode Version 13.6
 - Swift Version 5

**Installation Type**
 - Cocoapods

**Comment by Ludotrico** [comment]
I experience the same thing. The app also terminates if you scroll too quickly through the library and you have big files stored.

**Comment by VitaliiDeveloper** [comment]
@Ludotrico Well, I can fix all of this problem with the memory problem later. Or maybe somebody will do this early :)

**Comment by s4cha** [comment]
@VitaliiDeveloper if you have fix ideas, that'd be amazing :)

**Comment by NikKovIos** [comment]
@VitaliiDeveloper any updates?

**Comment by VitaliiDeveloper** [comment]
> @VitaliiDeveloper any updates?

No. Because haven't time to fix this bug. It not high priority in the general. Not so a lot of users gonna be using large images witch gonna be terminate the app.

**Comment by NikKovIos** [comment]
Closing. All activity about memory would be there https://github.com/Yummypets/YPImagePicker/issues/658
