### ISSUE TITLE
Where is the option for multiple selection of Image/Video?

### ISSUE THREAD

**Issue by PawanManjani** [Yummypets/YPImagePicker#54]
Where is the option for multiple selection of **Image/Video**?

**Comment by s4cha** [comment]
@PawanManjani It is not supported at the moment but we're working on it. You can track advancement here : https://github.com/Yummypets/YPImagePicker/pull/47

**Comment by PawanManjani** [comment]
@s4cha Thanks for responding, When you guys will complete this multiple selection feature?

**Comment by s4cha** [comment]
@PawanManjani hopefully by the end of the month :)

**Comment by NikKovIos** [comment]
@PawanManjani you can take a participation in it ;)

**Comment by PawanManjani** [comment]
@s4cha you will complete with both image and video multiple selection??

**Comment by NikKovIos** [comment]
@PawanManjani yes

**Comment by PawanManjani** [comment]
Okay, Please update me once you update it...

**Comment by PawanManjani** [comment]
Hey @s4cha  have to uploaded a new version with multiple selection?

**Comment by s4cha** [comment]
@PawanManjani not yet, NikKovIos is on it. By the way @NikKovIos, don't hesitate if you need a hand on something :)

**Comment by NikKovIos** [comment]
Yes. Im gonna make it at this or next week.

**Comment by devender54321** [comment]
ok thanks we are waiting for it. Also work for Edit option (like brightness) like Instagram to make this third party complete

**Comment by Didar1994** [comment]
Hi! Have you finished multiple selection feature? Really looking forward to it!

**Comment by NikKovIos** [comment]
@Didar1994 The basic implementation is finished, you can fetch it directly from the multipleSelection branch. But it still in development.

**Comment by devender54321** [comment]
not found . Multiple selection for images and video

**Comment by goribchat** [comment]
can i use the multiple selection option?

**Comment by NikKovIos** [comment]
The multiple selection is under construction currently. Also there would be add a video trimming and cover image fetching features **from the box** 😀

To use it in pre release mode, write in your podfile:
`pod 'YPImagePicker', :git => 'https://github.com/Yummypets/YPImagePicker.git', :branch => 'multipleSelection' # Instagramm like image picker`

Thumbs up if helped!

**Comment by goribchat** [comment]
Okay.. please inform once the multiple selection is done..

**Comment by goribchat** [comment]
Hey NikKovIos it is fine. but can you help me to send the multiple image to another viewController. previously i am using ImagePickerController, and i sent the image in the doneButtonDidPress. where to implement that particular code here? i have found that   When pressing "Next"  done() function is calling but i am unable to send the image. please help

**Comment by goribchat** [comment]
Sir here's no any delegate or method that returns selected image. Can you help me regarding this matter

**Comment by NikKovIos** [comment]
@goribchat The way to do it with multiple selection is like this:

```swift
config.delegate = self
let picker = YPImagePicker(configuration: config)
present(picker, animated: true, completion: nil)

extension VC: YPImagePickerDelegate {
    func imagePicker(_ imagePicker: YPImagePicker, didSelect items: [YPMediaItem]) {
        _ = items.map { print("🧀 \($0.type)") }
    }
    
    func imagePickerDidCancel(_ imagePicker: YPImagePicker) {}
}
```

**Comment by s4cha** [comment]
https://github.com/Yummypets/YPImagePicker/releases/tag/3.0.0 🎉

**Comment by PawanManjani** [comment]
@s4cha You are Awesome

**Comment by s4cha** [comment]
@PawanManjani Thank this guy -> @NikKovIos . Thanks for your patience :)
