### ISSUE TITLE
Support UIDocumentPickerViewController (apple rejects approval since no support for Files folder files)

### ISSUE THREAD

**Issue by deeplinkage** [Yummypets/YPImagePicker#540]
We need to support UIDocumentPickerViewController in order for this app to be approved by app store.

I have been rejected and that is the reason. This is now enforced as new policy to use new features like iCloud and Files App.

Here is a message from Apple:

Guideline 2.5.15 - Performance - Software Requirements

We noticed that your app enables users to view and select files, but it does not include functionality to allow users to view or select items from the Files app and the user's iCloud documents, as required by the App Store Review Guidelines.

Next Steps

To resolve this issue, please revise your app to allow users to view and select items from the Files app and the user's iCloud documents.

**Comment by Ludotrico** [comment]
This is definitively of utmost importance, no one wants to build apps for the simulator

**Comment by deeplinkage** [comment]
Any update?

**Comment by s4cha** [comment]
This is really strange. I think dozens of apps using this picker got approved recently (ours included). You should be able to make an appeal in the meantime.

**Comment by NikKovIos** [comment]
It's not reproducing in my side. If you have such a problem, please make a PR with link to this issue.
