### ISSUE TITLE
PHAuthorizationStatus.limited is not handled on iOS 14

### ISSUE THREAD

**Issue by haojin2020** [Yummypets/YPImagePicker#542]
**Describe the bug**
PHAuthorizationStatus.limited is not handled on iOS 14

**To Reproduce**
1. Select "Select photos" from the privacy confirm dialog.

**Expected behavior**

**Screenshots**
<img width="284" alt="Screenshot" src="https://user-images.githubusercontent.com/66354606/90479614-85239380-e161-11ea-9d98-fb88f0442d3d.png">

**Environment (please complete the following information):**
 - Device: Simulator
 - OS: iOS 14
 - Xcode Version: Version 12.0 beta 4 (12A8179i)

**Installation Type**
 - Cocoapods

**Additional context**

**Comment by mazharulbelal** [comment]
Can't run the example project.  occurs the same issue. "Type 'PHAuthorizationStatus' has no member 'limited'".

Environment
Xcode Version: 11.6 (11E708)
Device: Simulator
OS: 13.6

**Comment by NikKovIos** [comment]
Added
