### ISSUE TITLE
Does this picker is also supported in iPadOS

### ISSUE THREAD

**Issue by userSV** [Yummypets/YPImagePicker#544]
I have an app which needs to be built in both iOS and iPad, and I am already using this picker in iOS app. So, is there any way that this can be used in iPad app as well.

**Comment by NikKovIos** [comment]
Just try :)

**Comment by userSV** [comment]
can't use it because the UI is completely distorted. Is there any other alternative for this?

**Comment by nickeyzzz** [comment]
Looks absolutely fine for me. I believe you can use it for iPad.

**Comment by userSV** [comment]
@nickeyzzz did you change some configurations for iPad? and are you using latest version. Can you please share the screenshot like how is it looking at your side.

**Comment by userSV** [comment]
Finally I got how to configure this with widthOniPad property for iPad.
`let preferredContentSize = CGSize(width: self.view.frame.size.width, height: 600)
        YPImagePickerConfiguration.widthOniPad = preferredContentSize.width`

**Comment by nickeyzzz** [comment]
Sorry for late reply, I've just checked on iPad 2, even without your fix - looks fine just out of the box. But I have a problem when rotating the iPad.
Also got problem with video.
https://github.com/Yummypets/YPImagePicker/issues/549
