### ISSUE TITLE
Xcode 12: Cannot convert value of type 'CMTime' to type 'NSValue' in coercion

### ISSUE THREAD

**Issue by grantespo** [Yummypets/YPImagePicker#563]
I am using v `4.3.1`

Upon updating Xcode to 12, I cannot build my app!

This error occurs in ThumbSelectorView.swift Line 141
**Cannot convert value of type 'CMTime' to type 'NSValue' in coercion**

<img width="912" alt="Screen Shot 2020-09-16 at 5 33 41 PM" src="https://user-images.githubusercontent.com/19721824/93394845-d8f9c900-f842-11ea-97ef-23090fa361d8.png">

**Comment by timothyerwin** [comment]
I'm getting the same problem...when I fixed this I got a lot of other build errors for YPImagePicker:

e.g.

```
/Pods/YPImagePicker/Source/Pages/Photo/PostiOS10PhotoCapture.swift:53:36: Value of type 'AVCapturePhotoOutput' has no member 'supportedFlashModes'

/Pods/YPImagePicker/Source/Pages/Photo/PostiOS10PhotoCapture.swift:53:66: Cannot infer contextual base in reference to member 'auto'
```

**Comment by colbylim** [comment]
@grantespo 
Modify [time as NSValue] to [NSValue(time: time)]
generator?.generateCGImagesAsynchronously(forTimes: **[NSValue(time: time)]**,

@timothyerwin
Occurs only in the simulator.

#if arch(i386) || arch(x86_64)
settings.flashMode = .off
#else
if let deviceInput = deviceInput {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if deviceInput.device.isFlashAvailable {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;switch currentFlashMode {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case .auto:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if photoOutput.supportedFlashModes.contains(.auto) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;settings.flashMode = .auto
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case .off:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if photoOutput.supportedFlashModes.contains(.off) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;settings.flashMode = .off
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;case .on:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if photoOutput.supportedFlashModes.contains(.on) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;settings.flashMode = .on
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;}
}
#endif

its work for me.

**Comment by grantespo** [comment]
@colbylim thanks that worked,
but to fixup timothy's issue, I just removed the flash code altogether since i am only using the image picker.

**Comment by CreatorMetaSky** [comment]
if use cocoapods, you can add this line to your podfile:

```ruby
pod 'PryntTrimmerView', :git => 'https://github.com/HHK1/PryntTrimmerView.git'
```

**Comment by CreatorMetaSky** [comment]
please see the pull request: https://github.com/Yummypets/YPImagePicker/pull/565

**Comment by fukemy** [comment]
nope, change pod code is not good solution
