### ISSUE TITLE
please update pod for ios 14

### ISSUE THREAD

**Issue by fukemy** [Yummypets/YPImagePicker#572]
after update ios14, i got this error 

<img width="1164" alt="Screen Shot 2020-09-23 at 20 29 16" src="https://user-images.githubusercontent.com/8202437/94019035-83419580-fddb-11ea-8826-ecace15ef421.png">

**Comment by almet88** [comment]
https://github.com/Yummypets/YPImagePicker/issues/563 this helps, but generally, pod needs to be updated, it crashes when user cancels selection and Apple Review team says that it crashes, but I can't find where.

**Comment by fukemy** [comment]
@almet88 use firebase analystic to check problem bro

**Comment by almet88** [comment]
It crashes on line 183 in file YPLibraryVC if user does not give access to any photo in Limited photo access mode.

**Comment by fukemy** [comment]
i think u can request permission before using library each time

**Comment by almet88** [comment]
Yes, but it crashes if user gives LIMITED permission, then iOS 14 shows him his gallery to choose photos that he allows app to use and if user doesn't choose any photo, app crashes since it tries to create the asset from the first photo from library (I think for preview or smth like that)

**Comment by NikKovIos** [comment]
Crash reproduced only with `defaultMultipleSelection == true`.
Fixed 89acc4c3bea687f53e7b05a9adab08153f158721
