### ISSUE TITLE
v4.4.0 does not compile with Xcode 11.7

### ISSUE THREAD

**Issue by gcamp806** [Yummypets/YPImagePicker#580]
**Describe the bug**
Compiler error: Type 'PHAuthorizationStatus' has no member 'limited'

**To Reproduce**
Build an app which uses v4.4.0, the compiler will error on YPLibraryVC.swift line 247.

**Expected behavior**
No compiler errors in the YPImagePicker library

**Screenshots**
![Screen Shot 2020-10-02 at 9 14 41 AM](https://user-images.githubusercontent.com/903819/94933277-cc56b100-048f-11eb-8f9c-ba5f48b60413.png)

**Environment (please complete the following information):**
 - Device: N/A
 - OS: 10.15.7
 - Xcode Version 11.7
 - Swift Version 5.2.4

**Installation Type**
 - Cocoapods

**Additional context**

**Comment by soujohnreis** [comment]
+1 to this

**Comment by NikKovIos** [comment]
@soujohnreis @gcamp806 
Please add a Pull Request where it would be something like `if #available(iOS 14.0, *) {`

**Comment by gcamp806** [comment]
@NikKovIos  PR #581 submitted!

**Comment by foobar98** [comment]
@NikKovIos When can we expect this to be released?

**Comment by rbecharast-chwy** [comment]
@NikKovIos When can we expect this to be released?
