### ISSUE TITLE
Crash on deselecting limited access image (iOS 14).

### ISSUE THREAD

**Issue by petrykDima** [Yummypets/YPImagePicker#584]
**Describe the bug**
Picker crashing after deselecting previous photos and selecting new ones in limited access. If the user has chosen limited access to his media files, after restarting the application and calling the picker, he can supplement his selected media files or leave them in the form in which they were selected during the previous session. If the user chooses to supplement his choice, and in the native controller for selecting media files deselects the previous available media files and instead selects new ones, you will notice that after he confirms his choice by clicking on the Done button, the image used for the preview and crop on **YPLibraryVC** will differ from which he can choose at the bottom of the screen. After clicking on the Next button, the picker will crash. The crash occurs somewhere around YPImagePicker/YPLibraryVC.swift, line 474. 

**To Reproduce**
Steps to reproduce the behavior.
1. Launch the application.
2. Call YPImagePicker.
3. On access selection pop-up window, select "Select Photos ...".
4. Select any photo.
5. Сonfirm the selection by clicking the Done button in the upper right corner.
6. Restart application.
7. Call YPImagePicker.
8. On access selection pop-up window, select "Select More Photos ...".
9. Deselect the previously selected photo.
10. Select any new photo.
11. Сonfirm the selection by clicking the Done button in the upper right corner.
12. Press Next on YPLibraryVC.
13. Picker crashing.

**Expected behavior**
1. New images are available for selection at the bottom of YPLibraryVC.
2. Image used for the preview and crop displays the selected photo.
3. Picker doesn't crash.

**Environment**
 - Device: iPhone Xs Max
 - OS: 14.0.1
 - Xcode Version : Version 12.0 (12A7209)
 - Swift Version: 5

**Installation Type**
 - Cocoapods

**Comment by choiks14** [comment]
same here

**Comment by petrykDima** [comment]
Ask user permission for use photos, before open Controller. 
It helped me.

**Comment by NikKovIos** [comment]
Should be fixed now in master. Check 88cf5f9 please.
