### ISSUE TITLE
add swift package manager

### ISSUE THREAD

**Issue by Maxvit5** [Yummypets/YPImagePicker#588]
Hi
please add swift package manager

**Comment by norbdev** [comment]
In the 4.4.0 they added but I get this error:

> https://github.com/Yummypets/YPImagePicker has no Package.swift manifest for version 4.4.0

@s4cha

**Comment by cloke** [comment]
@Maxvit5 This is supported, but you have to specify the branch. https://github.com/Yummypets/YPImagePicker branch `spm`. I missed the specify branch part in the readme at first and kept thinking it was broken.

**Comment by NikKovIos** [comment]
https://github.com/Yummypets/YPImagePicker/releases/tag/5.0.0
