### ISSUE TITLE
Not Working for swift 3

### ISSUE THREAD

**Issue by devender54321** [Yummypets/YPImagePicker#59]
your code is not updated for version 1.2.1 and also there is no Edit option like Instagram . Please update it for swift3 and multiple image selection is not working.

**Comment by robertodias180** [comment]
@devender54321 the current version is 2.7.2. 
What the min iOS version you are supporting? From version 1.2.1 onward it is iOS9+ only.

**Comment by devender54321** [comment]
I am using iOS 10.3.2 , And using code 1.2.1 of your framework.

**Comment by s4cha** [comment]
@devender54321 multiple image selection is not available at the moment, we are working on it :)

**Comment by devender54321** [comment]
And What about the Edit Option like Instagram

**Comment by NikKovIos** [comment]
https://github.com/Yummypets/YPImagePicker/pull/47

**Comment by NikKovIos** [comment]
https://github.com/Yummypets/YPImagePicker/pull/47

**Comment by s4cha** [comment]
@devender54321 not sure I understand what edit means, do you mean the filters ?

**Comment by devender54321** [comment]
No sir the two option found in Instagram Filter and Edit (Brightness)

**Comment by s4cha** [comment]
Edit is not supported neither at the moment but feel free to contribute :) update your version to 2.7.X to get the latest updates.
