### ISSUE TITLE
White Bar offset in Library

### ISSUE THREAD

**Issue by MHX792** [Yummypets/YPImagePicker#6]
When the camera starts first and then you change to the library, there is a white bar ontop of the first row of library images (roughly 40pt). It goes away if you scroll down.

**Comment by s4cha** [comment]
@MHX792 , Thanks for noticing that.
This is a problem indeed :/
I am going  to look into it.

PS : Please excuse the late reply I was on holiday :)

**Comment by s4cha** [comment]
@MHX792 
This should be solved in https://github.com/Yummypets/YPImagePicker/releases/tag/2.0.0

Let me know if that solves it on your side :)

**Comment by MHX792** [comment]
Thanks, but can't test it yet, because 2.0.0 is not pushed to cocoapods yet and I don't use Carthage.

**Comment by s4cha** [comment]
@MHX792 I'm going to take a look at Cocoapods integration :)

**Comment by s4cha** [comment]
@MHX792 2.0.1 should fix the issue :)

**Comment by s4cha** [comment]
@MHX792 Were you able to make it work?
