### ISSUE TITLE
Crash after delete image from photo library

### ISSUE THREAD

**Issue by carmelogallo** [Yummypets/YPImagePicker#61]
iOS 11.2.x
iPhone X

Hey guys, I found this issue. If you are in library section in YPImagePicker and go to native photo library of the device and delete an image, the app crash when you come back to it.

**Comment by s4cha** [comment]
@cikpis this bug is supposed to have been fixed as well :)

**Comment by carmelogallo** [comment]
- YPImagePicker (2.6.0):
    - SteviaLayout (~> 4.2.0)

**Comment by carmelogallo** [comment]
I'm using cocoapods
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.3'
inhibit_all_warnings!
use_frameworks!

target 'YPImagePickerTester' do
pod 'YPImagePicker'
end
```

**Comment by carmelogallo** [comment]
I had to update my cocoapod master repo. Now I have the 2.7.2

**Comment by s4cha** [comment]
Awesome! Cheers 👍
