### ISSUE TITLE
Header "Stevia-Swift.h" not found

### ISSUE THREAD

**Issue by umangbista2** [Yummypets/YPImagePicker#615]
**bug**
Unable to run the project.

**Screenshots**

![Screenshot 2020-12-03 at 4 24 30 PM](https://user-images.githubusercontent.com/27769844/101006625-35899c00-3587-11eb-8dc0-493680939354.png)

**Environment:**
 - Device: [e.g. iPhone7]
 - OS: [e.g. iOS13.1.3]
 - Xcode Version [e.g. 12.2]
 - Swift Version [e.g. 5.3.1]

**Comment by afaqsaqi** [comment]
Do you find any solution to this problem?

**Comment by NikKovIos** [comment]
Should be fixed.
