### ISSUE TITLE
Camera is not enabled after going back from filter + crash

### ISSUE THREAD

**Issue by carmelogallo** [Yummypets/YPImagePicker#62]
iOS 11.2.x
iPhone X

Hey guys, I found this issue. If you are in filter view after you took a photo and go back, the camera is not activate so it seems that is frozen. Also, if you tap on shot button it will crash.

**Comment by s4cha** [comment]
Hey @cikpis what version of the picker are you using? Because this bug is supposed to have been fixed already :)

**Comment by carmelogallo** [comment]
- YPImagePicker (2.6.0):
    - SteviaLayout (~> 4.2.0)

**Comment by carmelogallo** [comment]
I'm using cocoapods
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.3'
inhibit_all_warnings!
use_frameworks!

target 'YPImagePickerTester' do
pod 'YPImagePicker'
end
```

**Comment by carmelogallo** [comment]
I had to update my cocoapod master repo. Now I have the 2.7.2
