### ISSUE TITLE
Can not run example app by "pod try YPImagePicker"

### ISSUE THREAD

**Issue by vietstone-ng** [Yummypets/YPImagePicker#620]
**Describe the bug**
Can not run example app by "pod try YPImagePicker"

**To Reproduce**
1. Open Terminal, run "pod try YPImagePicker"
2. In Xcode, run target "YPImagePickerExample"
3. There're 3 errors reported by Xcode: 

> /var/folders/27/r58hlzls7n9bbgz_n5xg19p40000gn/T/CocoaPods/Try/YPImagePicker/YPImagePickerExample/YPImagePickerExample.xcodeproj Building for iOS, but the linked and embedded framework 'Stevia.framework' was built for iOS + iOS Simulator.
> 
> /var/folders/27/r58hlzls7n9bbgz_n5xg19p40000gn/T/CocoaPods/Try/YPImagePicker/YPImagePickerExample/YPImagePickerExample.xcodeproj Building for iOS, but the linked and embedded framework 'PryntTrimmerView.framework' was built for iOS + iOS Simulator.
> 
> /var/folders/27/r58hlzls7n9bbgz_n5xg19p40000gn/T/CocoaPods/Try/YPImagePicker/Source/Filters/YPFiltersView.swift:9:8: Module compiled with Swift 5.3 cannot be imported by the Swift 5.3.2 compiler: /var/folders/27/r58hlzls7n9bbgz_n5xg19p40000gn/T/CocoaPods/Try/YPImagePicker/Carthage/Build/iOS/Stevia.framework/Modules/Stevia.swiftmodule/arm64.swiftmodule

**Expected behavior**
The app is opend on device

**Screenshots**
<img width="1512" alt="Screen Shot 2020-12-22 at 15 22 15" src="https://user-images.githubusercontent.com/744353/102866226-7c253480-4469-11eb-9f2d-69eb291d25df.png">

**Environment (please complete the following information):**
 - Device: iPhone6s plus
 - OS: iOS8.1
 - Xcode Version 13.7
 - Swift Version 5.3.2

**Comment by musakokcen** [comment]
I also have the same issue!

"Module compiled with Swift 5.3 cannot be imported by the Swift 5.3.2 compiler"

**Comment by vietstone-ng** [comment]
Does anyone know how to fix this? As I'm using this cool pod, I'm trying to make a PR to fix this issue. But it seems that these frameworks were added in a way I don't know.
