### ISSUE TITLE
YPImagePickerExample Xcode 12 build error

### ISSUE THREAD

**Issue by IrelDev** [Yummypets/YPImagePicker#623]
**Describe the bug**
Cannot build YPImagePickerExample because of the following error:
Building for iOS, but the linked and embedded framework 'PryntTrimmerView.framework' was built for iOS + iOS Simulator.

**Environment:**
 - Device: iPhone 6s real device, iPhone 12 Pro Max simulator
 - OS: 14.3
 - Xcode Version: 14.3 & 14.2
 - Swift Version: 5.3

**Comment by niteshgupta27** [comment]
plz add PryntTrimmerView.framework' pod in podfile

**Comment by vietstone-ng** [comment]
@niteshgupta27 Can you describe in more detail?. I'm trying to make a PR for this issue, but it seems the framework was added in a way that I don't know.
