### ISSUE TITLE
After record video nothing happened 

### ISSUE THREAD

**Issue by rezamagnet** [Yummypets/YPImagePicker#624]
**Describe the bug**
after record video nothing happened

**To Reproduce**

Use these code:
var config = YPImagePickerConfiguration()
config.video.fileType = .mp4
config.video.compression = AVAssetExportPresetLowQuality
config.screens = [.library, .photo, .video]
config.library.mediaType = .photoAndVideo
let picker = YPImagePicker(configuration: config)
present(picker, animated: true)

1- after present going to video section
2- record video and nothing happened 

**Expected behavior**
after record video exportAsynchronously not called in your code as I check.

**Environment (please complete the following information):**
 - Device: iPhone 11
 - OS: 14.3
 - Xcode Version 12.3
 - Swift Version 5.3

**Installation Type**
 - Cocoapods

**Additional context*
I think it's Xcode bugs I checked other project and check in exportAsynchronously, but nothing happened

**Comment by rezamagnet** [comment]
it was iOS bug even screen recording on my iOS device doesn't work, after i know this bug, I restart my phone and everything goes fine but this takes me some times to understand the solution.

I'm using iOS 14.3

**Comment by chang-guofeng** [comment]
I meet the same issue even after restart my phone..

it says:
[ImageManager] First stage of an opportunistic image request returned a non-table format image, this is not fatal, but it is unexpected

iOS 12.5.4 

Any one knows what's happing?
