### ISSUE TITLE
Couldn't install YPImagePicker via Swift Package Manager

### ISSUE THREAD

**Issue by Ahmad-Mawdoo3-Khwaja** [Yummypets/YPImagePicker#626]
I'm trying to install this library via SPM, but I got error below.

<img width="719" alt="Screen Shot 2021-01-12 at 12 13 53 PM" src="https://user-images.githubusercontent.com/69298052/104300991-d09f5b00-54cf-11eb-9b30-dec7c1bf0692.png">

 - iOS
 - Xcode
 - Swift

**Installation Type**
 - SPM

**Comment by iKK001** [comment]
same here - please add the necessary manifest. Thank you

**Comment by norbdev** [comment]
> A first version of SPM support is available : package https://github.com/Yummypets/YPImagePicker **branch spm**.
![Képernyőfotó 2021-04-14 - 10 46 47](https://user-images.githubusercontent.com/11431750/114681736-b9f6e300-9d0e-11eb-89e5-6cea626f1d62.png)

**Comment by NikKovIos** [comment]
https://github.com/Yummypets/YPImagePicker/releases/tag/5.0.0
