### ISSUE TITLE
[QUESTION] Is it possible to change the buttons image and texts font/text? 

### ISSUE THREAD

**Issue by carmelogallo** [Yummypets/YPImagePicker#63]
Hey guys, nice work with this project!

I was wondering if is there a possibility to customised the UI Objects like it was possible in Fusuma?

**Comment by s4cha** [comment]
@cikpis Thanks for the kind words !
Latest release (2.7.3) will enable you to customize wordings :
https://github.com/Yummypets/YPImagePicker/releases/tag/2.7.3

As for UI elements they're not (yet) but this is definitely on our shorterm roadmap, we will keep you posted :) There is an ongoing discussion here: https://github.com/Yummypets/YPImagePicker/issues/48

Side note, in the meantime there might be way a hacky way to replace the image resources manually 🤓

**Comment by carmelogallo** [comment]
Nice! Do you know when the 2.7.3 is out? And the 2.x.x for the UI elements?

**Comment by s4cha** [comment]
@cikpis the Carthage version is up and I'm trying to get the pod out at the moment but having a hard time with the wifi (I'm in the train) :) So hopefully in a few hours when I get home !

**Comment by carmelogallo** [comment]
nice! I guess the one for the ui elements is gonna happen later right?

**Comment by s4cha** [comment]
yep, hopefully by the end of the month :)

**Comment by carmelogallo** [comment]
👍

**Comment by s4cha** [comment]
2.7.3 is up on cocoapods https://cocoapods.org/pods/YPImagePicker :)

**Comment by carmelogallo** [comment]
awesome! waiting the one for the UI then!

**Comment by NikKovIos** [comment]
The continue of discussion here https://github.com/Yummypets/YPImagePicker/issues/48
