### ISSUE TITLE
installing via cocoapods still 2.4.1

### ISSUE THREAD

**Issue by aspek** [Yummypets/YPImagePicker#64]
Hello sir, Pods is still old version

**Comment by NikKovIos** [comment]
It is ok there. https://cocoapods.org/?q=ypimage
I think you didn't updated your pods. 
`pod update`

**Comment by aspek** [comment]
I'm not sure about my pods version. But I've updated on last month for sure.
Maybe the cause is `[!] Failed to connect to GitHub to update the CocoaPods/Specs specs repo - Please check if you are offline, or that GitHub is down`

**Comment by NikKovIos** [comment]
The problem is on your side. Try to update cocoapods repo.

**Comment by s4cha** [comment]
@aspek have you tried running `pod repo update` ?

**Comment by aspek** [comment]
@s4cha Yes I have,It always `Failed to connect to GitHub` However I have solved my problem. It came from my Pods issue. spent for hour for fix this :( 
Thanks all you guys

**Comment by s4cha** [comment]
@aspek With pleasure! Glad that it's fixed :) Can we close this ?

**Comment by aspek** [comment]
Oh, I forgot it.
