### ISSUE TITLE
Video preprocessing too long without progress indicator

### ISSUE THREAD

**Issue by marvukusic** [Yummypets/YPImagePicker#642]
**Describe the issue**
Issue is that longer compressed videos take too much time to transition to trimming screen after recording end with no UI elements like activity/progress indicator. 

**To Reproduce**
Start recording a video. Stop after 3 minutes. Observe how long it takes to transition to trimming screen.

**Possible solution**
Add activity/progress indicator between recording and trimming screens.

**Additional context**
Tested on iPhone XS with iOS 14.4.
1 minute video with AVAssetExportPresetMediumQuality takes about 7 seconds and 3 minute video about 20 seconds. 
When quality is set to AVAssetExportPresetPassthrough, delay is significantly shorter.

**Comment by riazhazan** [comment]
I fixed the same issue like this. Modified the YPLoaders.swift & YPVideoCaptureHelper.swift 
----------------------------------

YPLoaders.swift
==============
struct YPLoaders {
    static var defaultLoader: UIBarButtonItem {
        let spinner = UIActivityIndicatorView(style: .gray)
        if let spinnerColor = YPConfig.colors.navigationBarActivityIndicatorColor {
            spinner.color = spinnerColor
        } else {
            if #available(iOS 13, *) {
                let spinnerColor = UIColor { trait -> UIColor in
                    return trait.userInterfaceStyle == .dark ? .white : .gray
                }
                spinner.color = spinnerColor
            }
        }
        spinner.startAnimating()
        return UIBarButtonItem(customView: spinner)
    }
    
    static var fullScreenLoader: UIView {
        let spinner = UIActivityIndicatorView(style: .gray)
        if let spinnerColor = YPConfig.colors.navigationBarActivityIndicatorColor {
            spinner.color = spinnerColor
        } else {
            if #available(iOS 13, *) {
                let spinnerColor = UIColor { trait -> UIColor in
                    return trait.userInterfaceStyle == .dark ? .white : .gray
                }
                spinner.color = spinnerColor
            }
        }
        spinner.startAnimating()
        let frame =  UIScreen.main.bounds
        let indicatorView = UIView(frame: frame)
        spinner.center = indicatorView.center
        indicatorView.backgroundColor = UIColor.black.withAlphaComponent(0.3)
        indicatorView.addSubview(spinner)
        return indicatorView
    }
}

YPVideoCaptureHelper.swift
====================


public func fileOutput(_ captureOutput: AVCaptureFileOutput,
                           didFinishRecordingTo outputFileURL: URL,
                           from connections: [AVCaptureConnection],
                           error: Error?) {
        if YPConfig.onlySquareImagesFromCamera {
            **let indicator = YPLoaders.fullScreenLoader
            UIApplication.shared.keyWindow?.addSubview(indicator)**
            YPVideoProcessor.cropToSquare(filePath: outputFileURL) { [weak self] url in
                indicator.removeFromSuperview()
                guard let _self = self, let u = url else { return }
                _self.didCaptureVideo?(u)
            }
        } else {
            self.didCaptureVideo?(outputFileURL)
        }
        timer.invalidate()
    }



@marvukusic  Hope this may help you

**Comment by marvukusic** [comment]
@riazhazan Ok, I'll try that. Thx.

**Comment by timothyerwin** [comment]
@riazhazan can you fix the code formatting?

**Comment by NikKovIos** [comment]
https://github.com/Yummypets/YPImagePicker/releases/tag/5.2.1 seems that there is already fixed.
