### ISSUE TITLE
Can not update pod's code to 4.4.0

### ISSUE THREAD

**Issue by said13** [Yummypets/YPImagePicker#644]
After pod install/update terminal says that 4.4.0 is installed, but the code is old. For example in `YPLibraryVC.swift` the `refreshMediaRequest` function is without `preSelectItemOnMultipleSelection` bug fixing code.
I have as issue with pod updating or this Is a library issue?

**Comment by ibrahimzakarya** [comment]
me too

**Comment by said13** [comment]
`  pod 'YPImagePicker', :git => 'https://github.com/Yummypets/YPImagePicker'`
fixed the issue
