### ISSUE TITLE
Trimming indicator disappears after a few seconds

### ISSUE THREAD

**Issue by ghost** [Yummypets/YPImagePicker#656]
**Describe the bug**
After you’re done recording a video, you’re redirected to the ‘Trim’ screen. But when You tap ‘next’ it seems as if you’re redirected to this same exact screen for the second time.

**To Reproduce**
1. Record something for 10s, tap the red stop button
2. You’ll be redirected to the ‘Trim’ screen, tap the ‘Next’ button
And after a few seconds, the loading animation is gone and You can click it again. For longer videos, this takes a while so a user may be convinced that something's not working properly.

**Expected behavior**
After You click the button 'Next', the indicator is displayed till the trimming is finished so the user knows that something is happening.

**Screenshots**

https://user-images.githubusercontent.com/49237349/114011574-a9092600-9865-11eb-95f9-d34d0ad22fb9.mov

**Environment (please complete the following information):**
 - Device: iPhone 11 PRO 13.3.1, iPhone 6s iOS 14.4.1

**Installation Type**
 - Cocoapods

**Comment by NikKovIos** [comment]
@anderiss Thank you for such a good explanation! Seems that in https://github.com/Yummypets/YPImagePicker/releases/tag/5.2.1 it's already fixed.
