### ISSUE TITLE
Update SPM and Stevia version

### ISSUE THREAD

**Issue by norbdev** [Yummypets/YPImagePicker#657]
Please update the "spm" branch and the Stevia version.

**Comment by rudsberg** [comment]
I would also highly appreciate if the spm branch was updated to the latest version on master. Are there plans of doing that or to include support for SPM on master branch?  @NikKovIos @kiyot @s4cha 
We are developing an app that is going to be released in August and we need the #575 fix that was included in the 4.5.0 release when going live. 

Cheers. Loving the library, amazing work.

**Comment by SeNeO** [comment]
Is there any news on this? I'm using SPM too and the last release on this branch is almost one year old.

**Comment by NikKovIos** [comment]
About update to SPM can help only @s4cha

**Comment by okiookio** [comment]
please add this Package.swift :


// swift-tools-version:5.3
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "YPImagePicker",
    defaultLocalization: "en",
    platforms: [
        .iOS(.v13),
    ],
    products: [
        // Products define the executables and libraries a package produces, and make them visible to other packages.
        .library(
            name: "YPImagePicker",
            targets: ["YPImagePicker"]),
    ],
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        // .package(url: /* package url */, from: "1.0.0"),
        .package(name:"Stevia", url: "https://github.com/freshOS/Stevia", .upToNextMajor(from: "4.7.3")),
        .package(name:"PryntTrimmerView", url: "https://github.com/HHK1/PryntTrimmerView", .upToNextMajor(from: "4.0.2")),
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages this package depends on.
        .target(
            name: "YPImagePicker",
            dependencies: [
                "Stevia",
                "PryntTrimmerView"
            ],
            path: "Source",
            resources: [
                .process("Resources"),
            ]),
        .testTarget(
            name: "YPImagePickerTests",
            dependencies: ["YPImagePicker"]),
    ]
)

**Comment by NikKovIos** [comment]
Check https://github.com/Yummypets/YPImagePicker/releases/tag/5.0.0
