### ISSUE TITLE
Losing image quality in filter screen.

### ISSUE THREAD

**Issue by carmelogallo** [Yummypets/YPImagePicker#66]
Take a look at the screen shot. I have zoomed the photo and tapped on next.

![image uploaded from ios 1](https://user-images.githubusercontent.com/895478/37674847-0fb6bad6-2c74-11e8-9069-c0c0175eac6e.jpg)
![image uploaded from ios](https://user-images.githubusercontent.com/895478/37674848-0fcf73c8-2c74-11e8-9d50-1b2e9e315612.jpg)

**Comment by s4cha** [comment]
@cikpis this looks like a duplicate of https://github.com/Yummypets/YPImagePicker/issues/33
We are going to track it there if you don't mind :)

**Comment by carmelogallo** [comment]
👍
