### ISSUE TITLE
Square video cropping

### ISSUE THREAD

**Issue by cclaflin89** [Yummypets/YPImagePicker#660]
I'm not sure it's a bug. When I choose a video from the library in square view (button at the bottom left of preview area), I'm getting a full-screen video.
So when I play the video with AVPlayerViewController, it shows full-screen video. Not square cropped.
How can I get a cropped video?

I tested with the sample project in this repo and the version I tried is 4.5.0.

Device: iPhone X
Swift 5.3
Xcode: 12.5
iOS 14.5.1
Pod: 1.10.1

**Comment by NikKovIos** [comment]
Main discussion in https://github.com/Yummypets/YPImagePicker/issues/665.
