### ISSUE TITLE
choose video in iPhone simulator its failed 

### ISSUE THREAD

**Issue by amit123ios** [Yummypets/YPImagePicker#667]
**Describe the bug**
When I choose video in iPhone simulator its failed , and shows this error-

Export of the video failed : Optional(Error Domain=AVFoundationErrorDomain Code=-11800 "The operation could not be completed" UserInfo={NSLocalizedFailureReason=An unknown error occurred (-12212), NSLocalizedDescription=The operation could not be completed, NSUnderlyingError=0x600000f96a90 {Error Domain=NSOSStatusErrorDomain Code=-12212 "(null)"}})
YPLibraryVC -> selectedMedia -> Problems with fetching videoURL.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Xcode Version [e.g. 9.4.1]
 - Swift Version [e.g. 4.1]

**Installation Type**
 - Carthage
 - Cocoapods
 - Manual

**Additional context**

**Comment by awerudev** [comment]
@amit123ios Any update? I am getting the same error.

**Comment by NikKovIos** [comment]
If you wouldn't correctly fill the steps to reproduce, we couldn't help.

**Comment by josephelkhoury** [comment]
Hello,

I'm having the exact same error but not for all videos. Some videos are being rejected but I don't understand why.

Any help?

**Comment by NikKovIos** [comment]
https://user-images.githubusercontent.com/16647690/148675060-e1c8b120-4b30-41aa-856a-00aaaca97a5b.mp4

In https://github.com/Yummypets/YPImagePicker/releases/tag/5.2.1 works well.
