### ISSUE TITLE
Refresh of Library

### ISSUE THREAD

**Issue by justdan0227** [Yummypets/YPImagePicker#671]
How do you go about selecting another image from the library that isn't in your current selected list - aka select and image and then call YPImagePicker again - Library just shows what you added the first time.  I have to exit the app and restart to get the message about adding items to your list.

**Comment by dan085** [comment]
Hello @justdan0227  Do you Have any solution? Regards!

**Comment by NikKovIos** [comment]
Check 246cdf8fb440b9dce4bff233f54d6871ee0656bb if the bug still occures.
If yes, use `Bug report` template to create an issue.

**Comment by ArMouReR** [comment]
@justdan0227 @dan085 Have you found solution to this problem ?
