### ISSUE TITLE
Weird arrow icon and ability to change font title in Gallery

### ISSUE THREAD

**Issue by MehdiBrandoMahdloo** [Yummypets/YPImagePicker#68]
So, I just found out that the little “down arrow” icon in the gallery/library screen, is not an icon but a whole screenshot cropped.
I’ve looked closely to the icon and found out that the background isn’t transparent but a sort of grey, and i’ve decided to export it to Sketch. 
Opening the icon in Sketch made me discover a very weird thing. 
The icons, is a huge screenshot of a chat, cropped with a mask.
This is why the icon itself is huge in size (400kg circa). 

Can I suggest you to use a pdf icon with transparent background, instead of the actual “arrow down” icon?

Another thing:
The gallery/library navigation bar title font is Regular in weight. It should be Medium to be “in line” with the iOS overall GUI.
Can you please give us the ability to change the font weight?

Thank you so much for this awesome library.

**Comment by s4cha** [comment]
@MehdiMahdloo , nice Catch!
This makes a lot of sense, I'll keep you posted when any of this improves :)

**Comment by MehdiBrandoMahdloo** [comment]
Can’t wait

**Comment by s4cha** [comment]
@MehdiMahdloo you should be good in version 2.8.1 -> https://github.com/Yummypets/YPImagePicker/releases/tag/2.8.1
Enjoy !
