### ISSUE TITLE
Replace PHPhotoLibrary.requestAuthorization(_:) with PHPhotoLibrary.requestAuthorization(for:handler:)

### ISSUE THREAD

**Issue by SeNeO** [Yummypets/YPImagePicker#680]
As of iOS 14.0 `requestAuthorization(_:)` and `authorizationStatus()` are now deprecated they should be replace by `requestAuthorization(for:handler:)`and `authorizationStatus(for:)`.

**Comment by NikKovIos** [comment]
Check c3e9343b21c1e1b147eb41eb0f2c191ff394910d
