### ISSUE TITLE
Update pods

### ISSUE THREAD

**Issue by NeRo8** [Yummypets/YPImagePicker#687]
Hi every one, can you change in file podspec  resources onto resource_bundle. Now I have problem

> error:` Multiple commands produce '/Users/nero/Library/Developer/Xcode/DerivedData/ClearProject-dphrfligijzsvxggowqadmippyjb/Build/Products/Debug-iphonesimulator/ClearProject.app/Assets.car':

> Target 'ClearProject' (project 'ClearProject') has compile command with input '/Users/nero/Documents/VSCode/ClearProject/ios/ClearProject/Images.xcassets'

> That command depends on command in Target 'ClearProject' (project 'ClearProject'): script phase “[CP] Copy Pods Resources”

I read about this error, and find this post [How to fix Multiple commands produce](https://newbedev.com/can-t-assign-xcassets-to-the-main-target-on-xcode-11)

**Comment by NikKovIos** [comment]
Hello, please, create a PR.

**Comment by NikKovIos** [comment]
Seems that it's not a problem of this pod.

**Comment by fukemy** [comment]
how did u solved this?
