### ISSUE TITLE
xCode 13, iOS 15 Wrong NavBar background color

### ISSUE THREAD

**Issue by vladggordiichuk** [Yummypets/YPImagePicker#690]
Please, adjust YPImagePicker to work on iOS 15.

![Simulator Screen Shot - iPhone 12 Pro - 2021-09-09 at 18 45 23](https://user-images.githubusercontent.com/25669477/132724575-448455de-dc3d-4671-9acf-a83f2d42bfea.png)

**Comment by justdan0227** [comment]
Seeing this as well.  Please update

**Comment by justdan0227** [comment]
I did notice that if you add

let picker = YPImagePicker(configuration: config)
        picker.navigationBar.tintColor = .white
        
that you at least get the CANCEL button back.  However, can't get the Library Titles (which is a button) to show up yet?

**Comment by justdan0227** [comment]
And to fix the library title color (for now) inside of 

**open class YPPickerVC:**

you need to change 

```
func setTitleViewWithTitle(aTitle: String) {
        let titleView = UIView()
        titleView.frame = CGRect(x: 0, y: 0, width: 200, height: 40)
        
        let label = UILabel()
        label.text = aTitle
        label.textColor = .white //  <-----
```

**Comment by s4cha** [comment]
Hey, this is an annoying change on Xcode13/iOS15. Until we update the library. here is the fix:
```swift
 let navBarAppearance = UINavigationBarAppearance()
navBarAppearance.configureWithOpaqueBackground()
picker.navigationBar.scrollEdgeAppearance = navBarAppearance
```
source: https://developer.apple.com/forums/thread/682420

**Comment by KeWangKW** [comment]
I solved the problem by modifying the code

![image](https://user-images.githubusercontent.com/24774145/136129990-72a104ba-8614-4b12-9ee2-403869c1bdf2.png)

**Comment by sahbazali** [comment]
If you use YPImagePicker in multiple place you can add convenience init method and use it for wrapping navigation bar changes. (At least until the problem being fixed inside framework)

```
extension YPImagePicker {
    convenience init(pickerConfig: YPImagePickerConfiguration) {
        self.init(configuration: pickerConfig)
        if #available(iOS 15.0, *) {
            let appearance = navigationBar.standardAppearance
            appearance.configureWithOpaqueBackground()
            navigationBar.scrollEdgeAppearance = appearance
        }
    }
}
```

**Comment by NikKovIos** [comment]
Please check last release. I don't have such a problem in ios 15.

**Comment by NikKovIos** [comment]
Feel free to reopen if still exist with link to this issue.
