### ISSUE TITLE
Portrait (Vertical) Cropping?

### ISSUE THREAD

**Issue by gintechsystems** [Yummypets/YPImagePicker#691]
**Is your feature request related to a problem? Please describe.**
When specifying the crop rectangle ratio, it only works horizontally.

**Describe the solution you'd like**
We should be able to specify if the crop ratio is going to be used horizontally or vertically.

**Describe alternatives you've considered**
I did fork the YPImagePicker library and began editing the YPCropView file.

**Comment by tsahi-deri** [comment]
@gintechsystems What do you mean by 'only works horizontally'.
What values are you providing to rectangle ratio ?

If I got you right, my changes [here](https://github.com/Yummypets/YPImagePicker/pull/666) should solve your issue.

**Comment by gintechsystems** [comment]
@tsahi-deri That is exactly what I was talking about. Looks like we both had the same idea going haha. I tried less than 1 but it wasn't working, would always fill the screen and go past the edges. Thanks for working on this. I will close this issue!
