### ISSUE TITLE
Video cover not working fine

### ISSUE THREAD

**Issue by hadouken111** [Yummypets/YPImagePicker#704]
Hello, 
when I try to change the video cover that not really work.
In instagram when you select the cover you can make a cover at any millisecond/moment of the video, but here this is not possible, you can only make a cover at some moment of the video, so I have only 2 or 3 cover possible for a video that made really bad cover quality,  there is possible to change that and make a cover at any moment of the video ?

Thank you so much for you help

**Comment by NikKovIos** [comment]
YPImagePicker use https://github.com/HHK1/PryntTrimmerView for cropping the video and for getting thumbnail for video.
You can contribute in PryntTrimmerView so the YPImagePicker will get this functional too. 🙂
