### ISSUE TITLE
Crash After Permission Disable

### ISSUE THREAD

**Issue by rehannali** [Yummypets/YPImagePicker#708]
**Describe the bug**
The app is crashed if the user disabled permission for photos. And after that tried to capture it, application crashed.

**To Reproduce**
1. Open Application
2. After giving all permission, go back to settings
3. Disable photos permission
4. Tried to capture the picture, it crashes.

**Expected behavior**
It should ask permission and save image instead of crashing

**Environment (please complete the following information):**
 - Device: Any Device
 - OS: 15.1
 - Xcode Version 13
 - Swift Version  5.3

**Installation Type**
 - SPM

**Comment by rehannali** [comment]
If you try it for the first time and the first screen is the camera, it also crashed and then ask for permission rather than first ask for permission and then allow you to capture an image.

**Comment by NikKovIos** [comment]
Try https://github.com/Yummypets/YPImagePicker/releases/tag/5.1.1 it should fix the crash. If found - open the new issue.
