### ISSUE TITLE
Get image source (library/camera)

### ISSUE THREAD

**Issue by Palando** [Yummypets/YPImagePicker#71]
I need to know if the image comes from the camera or from the library. Am I correct that this information is not available at the moment? Would someone add this?

**Comment by s4cha** [comment]
@Palando, You're right, this is not available at the moment but this should be fairly simple to implement so we'll try to it have it in the next version :)

**Comment by Palando** [comment]
That would be great. Thank you.

**Comment by NikKovIos** [comment]
I'll implement it https://github.com/Yummypets/YPImagePicker/pull/47
