### ISSUE TITLE
crash in v5.0.0

### ISSUE THREAD

**Issue by fukemy** [Yummypets/YPImagePicker#711]
i got this error: 
Thread 1: "[<UIView 0x10b6c8720> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key assetViewContainer."

from:
```
extension YPLibraryView {
    
    class func xibView() -> YPLibraryView? {
        let nib = UINib(nibName: "YPLibraryView", bundle: Bundle.local). -> this line
        let xibView = nib.instantiate(withOwner: self, options: nil)[0] as? YPLibraryView
        return xibView
    }
````

**Comment by fukemy** [comment]
![Screen Shot 2021-11-24 at 15 53 55](https://user-images.githubusercontent.com/8202437/143205759-c3110c5e-fee9-40b2-bebf-a616a77e47e2.png)

**Comment by 2jumper3** [comment]
++ ver 5.0.0 
running on 7plus, Xcode Version 13.1 (13A1030d). MacBook Pro M1

**Comment by NikKovIos** [comment]
@fukemy @2jumper3 try https://github.com/Yummypets/YPImagePicker/releases/tag/5.1.1 it should fix the crash. If found - open the new issue.
