### ISSUE TITLE
Allowing the user to select a portion of a library video that is over the maximum length

### ISSUE THREAD

**Issue by pduvall** [Yummypets/YPImagePicker#712]
I'm currently looking to restrict the selected video length to 15 seconds, but without simply truncating the video beyond the first 15 seconds. Is there a configuration that will allow the user to choose a video from their library, and use the trimmer to select exactly which 15 seconds of the video they would like to use? I have tried the following configuration settings:

`config.video.libraryTimeLimit = .infinity`
`config.video.trimmerMaxDuration = 15.0`

But when selecting a video from the library that is longer than 15 seconds, the library just provides the user with the first 15 seconds of the video at which point they are provided with the trimmer interface to trim that segment even further. However, if the user wants to select a 15 second segment from, say, the middle or the end of a long video, that does not appear to be possible.

The current functionality seems counterintuitive to me and indeed is not how the video trimmer in popular applications like Instagram works.

**Comment by NikKovIos** [comment]
YPImagePicker use https://github.com/HHK1/PryntTrimmerView for cropping the video and for getting thumbnail for video.
You can contribute in PryntTrimmerView so the YPImagePicker will get this functional too. 🙂
