### ISSUE TITLE
Stevia Package Version Differences Causing Issues

### ISSUE THREAD

**Issue by gintechsystems** [Yummypets/YPImagePicker#718]
When working in the example project of YPImagePicker, it uses the Swift Package Manager Stevia 5.1.1. This is causing issues when using YPImagePicker through cocoapods in others projects because it uses 4.7.3 but the example is using SPM 5.1.1.

This mainly creates confusion and forces the developer to know which methods are supported in 4.7.3 and which are in 5.1.1 when working with this library.

Write Stevia code that uses methods from 5.1.1 but not 4.7.3. 
An example is button.fillHorizontally(padding: 30)

Pull in the project through cocoapods and see that build compilation fails because the project is using methods that does not exist in 4.7.3.

I recommend to remove cocoapods complete from the project, there is no reason for developers not to start using both at the very least. I know it is not easy to get away from cocoapods since a lot of old libraries haven't moved yet, especially libs that haven't had support in some time.

**Comment by NikKovIos** [comment]
Still a lot of people use cocoapods (so am I) and in our team we don't use SPM because of VPN issues. SPM is too automatic for us.
So I recommend to wait until apple make SPM more effective and convenience.

**Comment by NikKovIos** [comment]
@gintechsystems please try https://github.com/Yummypets/YPImagePicker/releases/tag/5.1.1 and tell if it build ok with SPM or cocoapods.

**Comment by gintechsystems** [comment]
@NikKovIos I will try that and let you know. 

Thanks for clarifying your issues with SPM, I was not aware of those. I am still using cocoapods myself as SPM seems to be very specific about versioning too and you can't easily use a forked version of a library through github.

**Comment by NikKovIos** [comment]
@gintechsystems also SPM is a big problem if you haven't internet connection or it is slow.

**Comment by gintechsystems** [comment]
Yeah you are correct, I personally wish Stevia would allow for cocoapods still with the latest version. They dropped support to early! Maybe someone else has forked it to stay supported on cocoapods, we can investigate that so we don't have two dependency managers.

**Comment by NikKovIos** [comment]
@gintechsystems I've made a PR today https://github.com/freshOS/Stevia/pull/163 Give a like to it ;)
Yes there is one person who did it. Check the network section of Stevia repo.

**Comment by gintechsystems** [comment]
I gave it a like, you said one person did it why don't you use that version in the picker for now until Stevia adds back support? Are you concerned about that person keeping the lib up to date?

**Comment by NikKovIos** [comment]
@gintechsystems because his repo is outdated too. Now I've bringing back old versions of Stevia for cocoapods and SPM. Check new release description.

**Comment by gintechsystems** [comment]
I see. Lets hope Stevia adds back support for cocoapods. I think your listed reasons are fair enough for them to do it. I subscribed so I will be watching the thread as well.

**Comment by NikKovIos** [comment]
@gintechsystems open new issue if find problems.
