### ISSUE TITLE
Handling Cancel Events

### ISSUE THREAD

**Issue by youngvz** [Yummypets/YPImagePicker#72]
Hey everyone, I had a question regarding how to handle the picker when a user decides to press cancel. I'm wondering how I would achieve something like this:

```
picker.didCancel = {  bool in
       // do something here
}
```

Thanks,
V ✌🏼

**Comment by s4cha** [comment]
@youngvz This is not supported at the moment but I add this to the improvements for the next version.
This is not a big deal to implement :)

**Comment by s4cha** [comment]
@youngvz, what would the `bool` used for in your example ?

**Comment by s4cha** [comment]
@youngvz your request will be implemented in https://github.com/Yummypets/YPImagePicker/pull/76
Feel free to chime in the refine the api if needed :)

**Comment by youngvz** [comment]
@s4cha Thanks for the quick response! In hindsight, I don't think I need to handle the bool case!
