### ISSUE TITLE
 Detect if the picture was taken with front camera

### ISSUE THREAD

**Issue by calaforrai** [Yummypets/YPImagePicker#733]
Hello,

it's possible to detect if the picture was taken with the front camera ?
thank for your help

**Comment by heitara** [comment]
Hi! There is nothing specific in this library yet. You are welcome to add it (you can check YPCameraVC line 159).
Also, you can use the image EXIF data or the image resolution to detect if it's the front camera. Read a bit more about such a workaround [here](https://stackoverflow.com/questions/34370865/how-to-detect-if-photo-taken-from-front-camera).

**Comment by calaforrai** [comment]
ok thank you for your answer I will take a look this :)
