### ISSUE TITLE
STILL MAINTAINED ????

### ISSUE THREAD

**Issue by calaforrai** [Yummypets/YPImagePicker#741]
Hello, 
Is the project still maintained because I asked 2 questions, one was a major memory leak problem, none of which was answered
Thank @bithavoc @appfabtech @schveiguy @vietstone-ng @heitara 

Question 1 : #734 (memory Issue)
Question 2 : #733

**Comment by heitara** [comment]
@calaforrai could you link your questions here, please?

**Comment by calaforrai** [comment]
@heitara For a memory problem, I created a custom function, I know it's not an optimized solution and probably not a good solution, but it slightly reduces the memory allocation of the picker, I call this function when I close the picker without selecting a photo and when I select a photo it does not reduce the memory allocation so the memory increases by around 70mb with each photo selection, on the other hand if I do not validate the photo selection and I close the picker the memory only increased by about 10mb
#734 
```
 @objc public func releaseContent(){
        picker.removeFromParent()
        self.selectedItems.removeAll()
        self.selectedPhotos.removeAll()
       
    }
```

Thank for help  @bithavoc @appfabtech @schveiguy @vietstone-ng @heitara

**Comment by heitara** [comment]
I'll investigate and get back to you later today.

**Comment by heitara** [comment]
I've answered to the linked issues. I'll ask @NikKovIos  to close this issue.
