### ISSUE TITLE
Does not compile with XCode 15.0 Beta 2 (13 errors)

### ISSUE THREAD

**Issue by LawrenceNorman** [Yummypets/YPImagePicker#791]
**Describe the bug**
Does not compile with XCode 15.0 Beta 2

**To Reproduce**
Compile with the latest XCode 15 beta 2.

The line:
@available(iOS, obsoleted: 3.0.0, renamed: "video.compression")
    public var videoCompression: String = AVAssetExportPresetHighestQuality
   In YPImagePickerConfiguration.swift results in: Stored properties cannot be marked unavailable with '@available'

**Expected behavior**
To be able to compile

**Installation Type**
 - SPM

**Comment by LawrenceNorman** [comment]
Ah I see the duplicate now.

**Comment by NikKovIos** [comment]
Duplicate https://github.com/Yummypets/YPImagePicker/issues/789
