### ISSUE TITLE
Warning: "Unable to load image data, /var/mobile/Media/DCIM/101APPLE/XXXX.JPG"

### ISSUE THREAD

**Issue by onurgenes** [Yummypets/YPImagePicker#81]
Getting this warning in console.

It happens both JPG and HEIC images.

**Comment by DamascenoRafael** [comment]
The same thing happens to me when I tap some image (not all) in the library. Despite this, everything works normally. Using the v3.0.0 on the iPhone X iOS 11.3

**Comment by s4cha** [comment]
Hi @onurgenes & @DamascenoRafael apparently we're not the only ones experiencing the issue (cf: https://stackoverflow.com/questions/46377824/ios-11-imagemanager-unable-to-load-image-data)
Some say it's an iOS 11 bug. As you said, everything works fine in spite of the warning. I'm going to look into it :)

**Comment by s4cha** [comment]
Looks like a common bug in iOS11, let's close this for now, feel free to reopen.
https://stackoverflow.com/questions/46377824/ios-11-imagemanager-unable-to-load-image-data
https://forums.developer.apple.com/thread/85717

**Comment by s4cha** [comment]
Looking at it I found that replacing 
`CGSize(width: asset.pixelWidth, height: asset.pixelHeight)`
 by
 `PHImageManagerMaximumSize` 
removes the warning log 🎉 in `requestImage` call in `PHCachingImageManager+Extensions`

Woop Woop!

**Comment by onurgenes** [comment]
Thanks! Perfect!

**Comment by s4cha** [comment]
@onurgenes this should be good now :)

**Comment by onurgenes** [comment]
Looks fantastic! Thanks @s4cha !

**Comment by CocoaML** [comment]
- (PHImageRequestID)requestImageForAsset:(PHAsset *)asset targetSize:(CGSize)targetSize contentMode:(PHImageContentMode)contentMode options:(nullable PHImageRequestOptions *)options resultHandler:(void (^)(UIImage *__nullable result, NSDictionary *__nullable info))resultHandler;
使用此方法获取相册中图片时， targetSize 设置过大，导致 控制台报错 ： [ImageManager] Unable to load image data,

解决方案： 调整参数，适当缩小 targetSize

It works for me.
