### ISSUE TITLE
How to Push ImagePicker instead of showing Modally?

### ISSUE THREAD

**Issue by GShushanik** [Yummypets/YPImagePicker#82]
Hi. Thanks for this amazing library. :)
I have one question, 
Can I push ImagePicker to my Navigation Stack, or there's only supported Modal presenting?

**Comment by s4cha** [comment]
Hi @GShushanik, YPImagePicker being UINavigationController itself, you cannot push a UINavigationController inside another one.
This is not supported. It could be in the future but it's not something high priority in our roadmap right now :)

Hope this helps,)

**Comment by NikKovIos** [comment]
You can use something like [this](https://stackoverflow.com/questions/37722323/how-to-present-view-controller-from-right-to-left-in-ios-using-swift) to mimic the push animation.
