### ISSUE TITLE
OnlySquareImages

### ISSUE THREAD

**Issue by NikKovIos** [Yummypets/YPImagePicker#86]
We got three properties in config 
```
    public var onlySquareImages = false
    public var onlySquareImagesFromLibrary = false
    public var onlySquareImagesFromCamera = true
```

Maybe one of them is not necessary? At least we should write if `onlySquareImages` force `onlySquareImagesFromLibrary` to be true or something like that.

**Comment by NikKovIos** [comment]
Oh, sorry, didn't see `unavailable`
So maybe remove this config at all when multiple selection will implemented?
And remove other stale configs too.

**Comment by s4cha** [comment]
@NikKovIos Yes Indeed `onlySquareImages` was the previous setting that then got separated into two different ones. I'm ok with removing it in the next version :)

**Comment by NikKovIos** [comment]
Then i'll remove it in https://github.com/Yummypets/YPImagePicker/pull/47
