### ISSUE TITLE
videos picking is not working

### ISSUE THREAD

**Issue by KazimAhmad** [Yummypets/YPImagePicker#9]
There,
i was having an issue while using your library, nothing happens when it comes to videos neither in the video capturing tab nor when we select a video from the photo album.
it starts the video capturing but on the stop button the video just gets vanished away and nothing significant happens, technically it should take the video to the filter view and then to the main view like instagram.
can you please look into this and help me out ?
thanks

**Comment by s4cha** [comment]
@KazimAhmad ,
This sounds weird to say the least !
We're using the lib in production for white some time and such a thing never happened to us before :/
Are you having the issue in your app or in the example project provided ?
Concerning the filters, this is only for photos (at least for the moment).

Cheers,

**Comment by s4cha** [comment]
@KazimAhmad are you still having the issue? I can't reproduce it on my side :/

**Comment by Vivekthakur647** [comment]
Hello i have an issue regarding videos , whenever view select video it wont preview like instagram , just creating its thumbnail and also after selecting video it wont go to filterVC .
Suggest me or correct me if i'm wrong

**Comment by Vivekthakur647** [comment]
![screen shot 2018-01-23 at 3 06 07 pm](https://user-images.githubusercontent.com/25250207/35268386-fc23922e-004e-11e8-8022-72ccd3bd0330.png)

**Comment by s4cha** [comment]
@Vivekthakur647 it is weird, Video preview works fine on my side both on device and simulator :/

Could you please elaborateon theses points: 

- Version of the picker are you using
- Provide me the video so that I can try on my side with the same file
- Simulator type
- iOS Version

Concerning the filters, this is normal, the feature is only enabled for photos at the moment :)

Cheers,

**Comment by s4cha** [comment]
@Vivekthakur647 any updates on this?

**Comment by NikKovIos** [comment]
Closed due to lack of activity. Feel free to reopen.
