### ISSUE TITLE
Let's create more than a crop, draw on the image

### ISSUE THREAD

**Issue by meditrine** [Yummypets/YPImagePicker#91]
Hey,

What do you think about add a feature which allowing us to draw (or blur) on the image we just took.
If i want to hide something on the image for example, like a face or some text.

All best :)

**Comment by NikKovIos** [comment]
Great feature! You can add a PR with it)

**Comment by meditrine** [comment]
Lack of time for the moment,
But I am saving this repo, it is interesting
If anyone would like to do it, feel free of course :)
