### ISSUE TITLE
Buttons are not showing

### ISSUE THREAD

**Issue by fsalom** [Yummypets/YPImagePicker#99]
Hi, I am using YPImagePicker for my project but when I access to it, all buttons in the navigation and in the toolbar are not showing. 

<img width="1003" alt="captura de pantalla 2018-04-25 a las 14 02 41" src="https://user-images.githubusercontent.com/6815781/39244609-6cc4020e-4891-11e8-98d5-227793ebba8a.png">

My code is quite simple:
```
var config = YPImagePickerConfiguration()
        config.onlySquareImagesFromLibrary = false
        config.onlySquareImagesFromCamera = true
        config.libraryTargetImageSize = .original
        config.usesFrontCamera = true
        config.showsFilters = true
        config.shouldSaveNewPicturesToAlbum = true
        config.albumName = "Roadstr"
        config.screens = [.library, .photo]
        config.startOnScreen = .library
        config.showsCrop = .rectangle(ratio: 1)
        config.wordings.libraryTitle = "Select Photo"
        config.wordings.cameraTitle = "Camera"
        config.hidesStatusBar = true

let picker = YPImagePicker(configuration: config)
            picker.didSelectImage = { [unowned picker] img in
                self.images.append(img)
                self.collectionImages.reloadData()
                picker.dismiss(animated: true, completion: nil)
            }
            self.present(picker, animated: true, completion: nil)
```

I must be doing something bad but I can not find it, do you have any idea what is happening?

**Comment by NikKovIos** [comment]
Please, create a separate project from the scratch and upload it in .zip archive here.

**Comment by fsalom** [comment]
After 2 hours debugging I found what was the problem. It was not related with the library, it works great. Sorry for the inconvenience

**Comment by samiibnauf** [comment]
what was the problem reason? I'm facing the same

**Comment by rajabpour** [comment]
I have same problem, let us to know... PLZ. 
@fsalom

**Comment by rajabpour** [comment]
> what was the problem reason? I'm facing the same

I found that,
You must add YPImagePicker library to "Link Binary with Library"   ;)
![untitled](https://user-images.githubusercontent.com/2610676/47354330-51919280-d6cb-11e8-94a5-76be0813042f.png)
